### ISSUE TITLE
Unpickling Error for Special Characters in OggZipDataset

### ISSUE THREAD

**Issue by vieting** [rwth-i6/returnn#1013]
This came up in #1012. I have a hack to fix this because I don't need the transcriptions in my use case, so this is not urgent.

I faced a problem during unpickling with some Vietnamese characters in the transcriptions inside the OggZipDataset. That was with python3.8 and a recent RETURNN version. I'm not sure though if this is actually a problem of RETURNN or rather a problem of the data used. The original transcription data contains `k<200e>ý` which is then also used in the RASR corpus. I used the bliss-to-oggzip tool to dump an ogg.zip file, which then contains `k\u200eý`. When reading that file in RETURNN, we get the byte string `b'k\\u200e\xc3` which is invalid and apparently leads to the error.

```
parse error: str escaped: char 'u' in pos 728483
parse error: dict|set: char '2' in pos 728484
parse error: list: char '0' in pos 728485
Unhandled exception <class 'AssertionError'> in thread <_MainThread(MainThread, started 140135024781056)>, proc 19544.

Thread current, main, <_MainThread(MainThread, started 140135024781056)>:
(Excluded thread.)

That were all threads.
EXCEPTION
Traceback (most recent call last):
[...]
  File ".../returnn/returnn/datasets/audio.py", line 132, in OggZipDataset.__init__
    line: self._data = self._collect_data()
    locals:
      self = <local> <OggZipDataset 'dev_ogg' epoch=None>
      self._data = <local> !AttributeError: 'OggZipDataset' object has no attribute '_data'
      self._collect_data = <local> <bound method OggZipDataset._collect_data of <OggZipDataset 'dev_ogg' epoch=None>>
  File ".../returnn/returnn/datasets/audio.py", line 191, in OggZipDataset._collect_data
    line: zip_data = self._collect_data_part(zip_index)
    locals:
      zip_data = <not found>
      self = <local> <OggZipDataset 'dev_ogg' epoch=None>
      self._collect_data_part = <local> <bound method OggZipDataset._collect_data_part of <OggZipDataset 'dev_ogg' epoch=None>>
      zip_index = <local> 0
  File ".../returnn/returnn/datasets/audio.py", line 164, in OggZipDataset._collect_data_part
    line: data = literal_eval(self._read("%s.txt" % self._names[zip_index], zip_index))  # type: typing.List[typing.Dict[str]]
    locals:
      data = <not found>
      literal_eval = <local> <function literal_eval at 0x7f732c6a61f0>
      self = <local> <OggZipDataset 'dev_ogg' epoch=None>
      self._read = <local> <bound method OggZipDataset._read of <OggZipDataset 'dev_ogg' epoch=None>>
      self._names = <local> ['out.ogg'], _[0]: {len = 7}
      zip_index = <local> 0
  File ".../returnn/returnn/util/literal_py_to_pickle.py", line 24, in literal_eval
    line: raw_pickle = py_to_pickle(s)
    locals:
      raw_pickle = <not found>
      py_to_pickle = <global> <function py_to_pickle at 0x7f732c6a6280>
      s = <local> b'[\n{\'text\': \'c\xc3\xa2n n\xe1\xba\xb7ng \xc4\x91\xc6\xb0\xe1\xbb\xa3c \xc3\xa1p d\xe1\xbb\xa5ng l\xc3\xa0 m\xe1\xbb\xa9c c\xc3\xa2n n\xe1\xba\xb7ng cao h\xc6\xa1n c\xe1\xbb\xa7a tr\xe1\xbb\x8dng l\xc6\xb0\xe1\xbb\xa3ng th\xe1\xbb\xb1c v\xc3\xa0 kh\xe1\xbb\x91i l\xc6\xb0\xe1\xbb\xa3ng quy \xc..., len = 1194265
  File "...returnn/returnn/util/literal_py_to_pickle.py", line 48, in py_to_pickle
    line: assert res == 0, "there was some error"
    locals:
      res = <local> 1
AssertionError: there was some error
```

**Comment by vieting** [comment]
I cannot share the whole corpus files, but here are excerpts of the relevant segment.
[vietnamese_corpus.ogg.txt](https://github.com/rwth-i6/returnn/files/8342267/vietnamese_corpus.ogg.txt)
[vietnamese_corpus.xml.gz](https://github.com/rwth-i6/returnn/files/8342271/vietnamese_corpus.xml.gz)

**Comment by albertz** [comment]
This was because 16 bit unicode chars were not supported in py-to-pickle. This is fixed now.
