### ISSUE TITLE
Batch Info for Reduce Layer

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/returnn#1048]
I am having a problem with flattening, when trying to use `"loss": "as_is"`. I think what happens is that the flatten operation is passed upwards but [batch = LayerBase.get_recent_layer().get_batch_info()](https://github.com/rwth-i6/returnn/blob/68d77464848b891f3b3d8588da0d46502be5bbcf/returnn/tf/util/data.py#L3358) returns the unpacked batch dim, but I don't really know the details on the flattening and how it is done in RETURNN. It should be related to #906. 

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    -- code not available --
  File "/u/hilmes/experiments/tts_new_sis/recipe/i6_private/users/hilmes/old/gauss_up.py", line 295, in test_returnn_loss
    line: net.get_total_loss()
    locals:
      net = <local> <TFNetwork '' train>
      net.get_total_loss = <local> <bound method TFNetwork.get_total_loss of <TFNetwork '' train>>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn/tf/network.py", line 1274, in TFNetwork.get_total_loss
    line: self.maybe_construct_objective()
    locals:
      self = <local> <TFNetwork '' train>
      self.maybe_construct_objective = <local> <bound method TFNetwork.maybe_construct_objective of <TFNetwork '' train>>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn/tf/network.py", line 1259, in TFNetwork.maybe_construct_objective
    line: self._construct_objective()
    locals:
      self = <local> <TFNetwork '' train>
      self._construct_objective = <local> <bound method TFNetwork._construct_objective of <TFNetwork '' train>>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn/tf/network.py", line 1241, in TFNetwork._construct_objective
    line: self._flatten_layer_with_losses()
    locals:
      self = <local> <TFNetwork '' train>
      self._flatten_layer_with_losses = <local> <bound method TFNetwork._flatten_layer_with_losses of <TFNetwork '' train>>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn/tf/network.py", line 1568, in TFNetwork._flatten_layer_with_losses
    line: new_out_template = new_out_template.copy_add_dim_by_tag(new_out.get_batch_dim_tag(), unbroadcast=True, axis=0)
    locals:
      new_out_template = <local> Data{'data', [F|F'feat'(1)]}
      new_out_template.copy_add_dim_by_tag = <local> <bound method Data.copy_add_dim_by_tag of Data{'data', [F|F'feat'(1)]}>
      new_out = <local> Data{'data:data_flat_output', [B&Packed{'time'},F|F'feat'(1)]}
      new_out.get_batch_dim_tag = <local> <bound method Data.get_batch_dim_tag of Data{'data:data_flat_output', [B&Packed{'time'},F|F'feat'(1)]}>
      unbroadcast = <not found>
      axis = <not found>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn/tf/util/data.py", line 3476, in Data.copy_add_dim_by_tag
    line: return self.copy_add_batch_dim(batch_dim_axis=axis, batch=batch_info, dim_tag=dim_tag)
    locals:
      self = <local> Data{'data', [F|F'feat'(1)]}
      self.copy_add_batch_dim = <local> <bound method Data.copy_add_batch_dim of Data{'data', [F|F'feat'(1)]}>
      batch_dim_axis = <not found>
      axis = <local> 0
      batch = <not found>
      batch_info = <local> None
      dim_tag = <local> Dim{B}
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn/tf/util/data.py", line 3378, in Data.copy_add_batch_dim
    line: assert dim_tag.batch == batch
    locals:
      dim_tag = <local> Dim{B}
      dim_tag.batch = <local> BatchInfo{B, Packed{'time'}}
      batch = <local> BatchInfo{B}
AssertionError
```

A test case for this (with returnn_common generated mean_l1) would be this: 

```python
def test_as_is_loss():
  from returnn.tf.util.data import batch_dim, SpatialDim, FeatureDim
  time_dim = SpatialDim("time")
  feature_dim = FeatureDim("feat", 1)
  config = Config({"extern_data": {"data": {"dim_tags": (batch_dim, time_dim, feature_dim), "dtype": "float32"}},
                   "behavior_version": 12},)
  net_dict = {
  'exp': {
    'class': 'activation',
    'from': 'data:data',
    'activation': 'exp',
    'out_shape': {batch_dim, time_dim, feature_dim}
  },
  'mean_absolute_difference': {
    'class': 'subnetwork',
    'from': [],
    'subnetwork': {
      'sub': {
        'class': 'combine',
        'from': ['base:exp', 'base:data:data'],
        'kind': 'sub',
        'out_shape': {batch_dim, time_dim, feature_dim}
      },
      'abs': {
        'class': 'activation',
        'from': 'sub',
        'activation': 'abs',
        'out_shape': {batch_dim, time_dim, feature_dim}
      },
      'reduce': {
        'class': 'reduce',
        'from': 'abs',
        'mode': 'mean',
        'axis': feature_dim,
        'out_shape': {batch_dim, time_dim}
      },
      'output': {
        'class': 'copy',
        'from': 'reduce',
        'out_shape': {batch_dim, time_dim}
      }
    },
    'loss': 'as_is',
    'out_shape': {batch_dim, time_dim},
  },
}
  with make_scope():
    net = TFNetwork(config=config, train_flag=True)
    net.construct_from_dict(net_dict)
    net.get_total_loss()
```

**Comment by albertz** [comment]
(Just note that I will probably be quite busy the next 2 weeks, so maybe you could debug and fix this yourself.)

**Comment by Atticus1806** [comment]
As a small update: It seems to be related to the `ReduceLayer`. 
Adding a check for ReduceLayer in `_check_push_flattening_to_inputs_for_layer_simple` just like for `SourceLayer` and `InternalLayer` is a workaround, but will result in no layers being flattened in this example, which also is not correct or at least optimal I think. 
Next step is to find out what goes wrong in the `ReduceLayer` case and how to fix it.

**Comment by albertz** [comment]
But why introducing a workaround? Why not just fixing the problem? Such workaround is probably more difficult than the correct fix.

**Comment by Atticus1806** [comment]
> Why not just fixing the problem?

Because I dont know what the exact problem is. I know that it is correlated to the `ReduceLayer` but I dont know whether its only the reduce layer. 
I was away last week so I only started working on it again today and I am currently still trying to understand the flatten code, what fails for `ReduceLayer` and what would be the correct part there. Maybe I am missing something obvious, but right now a fix is not clear for me.
