### ISSUE TITLE
Missing Batch Info during Returnn Network construction via NNetConstructor 

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/returnn#1069]
I am not 100% sure where to post this Issue, but since it happens during construction via `ReturnnCommonSerializer` and the code is here I will post it here. 
Constructing a returnn_common config with said serializer causes Returnn to crash early during construction:
```
EXCEPTION
Traceback (most recent call last):
  File "/u/hilmes/experiments/tts_new_sis/work/i6_core/tools/git/CloneGitRepositoryJob.ClTwHzgXqVmV/output/repository/rnn.py", line 11, in <module>
    line: main()
    locals:
      main = <local> <function main at 0x7ff41540ef70>
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.ClTwHzgXqVmV/output/repository/returnn/__main__.py", line 657, in main
    line: execute_main_task()
    locals:
      execute_main_task = <global> <function execute_main_task at 0x7ff41540ee50>
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.ClTwHzgXqVmV/output/repository/returnn/__main__.py", line 455, in execute_main_task
    line: engine.init_train_from_config(config, train_data, dev_data, eval_data)
    locals:
      engine = <global> <returnn.tf.engine.Engine object at 0x7ff32f837520>
      engine.init_train_from_config = <global> <bound method Engine.init_train_from_config of <returnn.tf.engine.Engine object at 0x7ff32f837520>>
      config = <global> <returnn.config.Config object at 0x7ff42aaf8d00>
      train_data = <global> <MetaDataset 'train' epoch=1>
      dev_data = <global> <MetaDataset 'dev' epoch=1>
      eval_data = <global> None
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.ClTwHzgXqVmV/output/repository/returnn/tf/engine.py", line 1056, in Engine.init_train_from_config
    line: self.init_network_from_config(config)
    locals:
      self = <local> <returnn.tf.engine.Engine object at 0x7ff32f837520>
      self.init_network_from_config = <local> <bound method Engine.init_network_from_config of <returnn.tf.engine.Engine object at 0x7ff32f837520>>
      config = <local> <returnn.config.Config object at 0x7ff42aaf8d00>
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.ClTwHzgXqVmV/output/repository/returnn/tf/engine.py", line 1121, in Engine.init_network_from_config
    line: self._init_network(net_desc=net_dict, epoch=self.epoch)
    locals:
      self = <local> <returnn.tf.engine.Engine object at 0x7ff32f837520>
      self._init_network = <local> <bound method Engine._init_network of <returnn.tf.engine.Engine object at 0x7ff32f837520>>
      net_desc = <not found>
      net_dict = <local> {'ctc_aligner_ctc_loss': {'class': 'copy', 'from': 'ctc_loss', 'loss': 'as_is', 'out_shape': {Dim{B}}}, 'ctc_aligner_mean_squared_difference_reduce': {'class': 'copy', 'from': 'mean_squared_difference', 'loss': 'as_is', 'loss_opts': {'scale': 0.5}, 'out_shape': {Dim{'audio_features_time'[B?]}, Di..., len = 19
      epoch = <local> None
      self.epoch = <local> 1
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.ClTwHzgXqVmV/output/repository/returnn/tf/engine.py", line 1295, in Engine._init_network
    line: extern_data.init_from_config(config=self.config, auto_create_placeholders=not use_dataset_pipeline)
    locals:
      extern_data = <local> <ExternData data={}>
      extern_data.init_from_config = <local> <bound method ExternData.init_from_config of <ExternData data={}>>
      config = <not found>
      self = <local> <returnn.tf.engine.Engine object at 0x7ff32f837520>
      self.config = <local> <returnn.config.Config object at 0x7ff42aaf8d00>
      auto_create_placeholders = <not found>
      use_dataset_pipeline = <local> False
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.ClTwHzgXqVmV/output/repository/returnn/tf/network.py", line 68, in ExternData.init_from_config
    line: self.data[key] = Data(name=key, auto_create_placeholders=auto_create_placeholders, **init_args)
    locals:
      self = <local> <ExternData data={}>
      self.data = <local> {}
      key = <local> 'audio_features', len = 14
      Data = <global> <class 'returnn.tf.util.data.Data'>
      name = <not found>
      auto_create_placeholders = <local> True
      init_args = <local> {'dim_tags': (Dim{B}, Dim{'audio_features_time'[B?]}, Dim{F'audio_features_feature'(80)}), 'dtype': 'float32', 'time_dim_axis': 1, 'available_for_inference': False}
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.ClTwHzgXqVmV/output/repository/returnn/tf/util/data.py", line 2778, in Data.__init__
    line: self.sanity_check(assume_complete=False)
    locals:
      self = <local> Data{'audio_features', [B?,T|'audio_features_time'[B?],F|F'audio_features_feature'(80)], available_for_inference=False}
      self.sanity_check = <local> <bound method Data.sanity_check of Data{'audio_features', [B?,T|'audio_features_time'[B?],F|F'audio_features_feature'(80)], available_for_inference=False}>
      assume_complete = <not found>
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.ClTwHzgXqVmV/output/repository/returnn/tf/util/data.py", line 2876, in Data.sanity_check
    line: assert tag.batch == tag.dyn_size_ext.batch
    locals:
      tag = <local> Dim{'audio_features_time'[B?]}
      tag.batch = <local> BatchInfo{B(-1)}
      tag.dyn_size_ext = <local> Data{'audio_features_dim0_size', [B?], dtype='int32'}
      tag.dyn_size_ext.batch = <local> None
AssertionError

```

The generated returnn config (leaving out the generated returnn part with datasets only showing returnn common part) generates this code, which to me looks good:
```python
sys.path.insert(
    0,
    "/u/hilmes/experiments/tts_new_sis/work/i6_core/tools/git/CloneGitRepositoryJob.1PthpathLjCM/output/returnn_common/..",
)
from returnn_common import nn

sys.path.insert(0, os.path.dirname(__file__))
import resource
import sys

try:
    resource.setrlimit(resource.RLIMIT_STACK, (2**29, -1))
except Exception as exc:
    print(f"resource.setrlimit {type(exc).__name__}: {exc}")
sys.setrecursionlimit(10**6)

speaker_labels_time = nn.SpatialDim("speaker_labels_time", None)
audio_features_feature = nn.FeatureDim("audio_features_feature", 80)
speaker_labels_indices = nn.FeatureDim("speaker_labels_indices", 251)
phonemes_indices = nn.FeatureDim("phonemes_indices", 43)
phonemes_time = nn.SpatialDim("phonemes_time", None)
audio_features_time = nn.SpatialDim("audio_features_time", None)
audio_features = nn.Data(
    name="audio_features",
    available_for_inference=True,
    dim_tags=[nn.batch_dim, audio_features_time, audio_features_feature],
    sparse_dim=None,
)
phonemes = nn.Data(
    name="phonemes",
    available_for_inference=True,
    dim_tags=[nn.batch_dim, phonemes_time],
    sparse_dim=phonemes_indices,
)
speaker_labels = nn.Data(
    name="speaker_labels",
    available_for_inference=True,
    dim_tags=[nn.batch_dim, speaker_labels_time],
    sparse_dim=speaker_labels_indices,
)
audio_features_args = audio_features.get_kwargs()
audio_features_args.pop("name")
phonemes_args = phonemes.get_kwargs()
phonemes_args.pop("name")
speaker_labels_args = speaker_labels.get_kwargs()
speaker_labels_args.pop("name")

extern_data = {
    "audio_features": audio_features_args,
    "phonemes": phonemes_args,
    "speaker_labels": speaker_labels_args,
}

from i6_private.users.hilmes.nar_tts.models.ctc_aligner import CTCAligner

from i6_private.users.hilmes.nar_tts.models.ctc_aligner import construct_network


network_kwargs = {
    "net_module": CTCAligner,
    "audio_data": audio_features,
    "label_data": speaker_labels,
    "phoneme_data": phonemes,
    "audio_time_dim": audio_features_time,
    "label_time_dim": speaker_labels_time,
}


def get_network(epoch, **kwargs):
    nn.reset_default_root_name_ctx()
    net = construct_network(epoch, **network_kwargs)
    return nn.get_returnn_config().get_net_dict_raw_dict(net)
```
```python
def construct_network(
  epoch: int,
  net_module: nn.Module,
  phoneme_data: nn.Data,  # phoneme labels
  duration_data: nn.Data,  # durations
  label_data: nn.Data,  # speaker labels
  audio_data: nn.Data,  # target speech
  time_dim: nn.Dim,  # phoneme time dim
  label_time_dim: nn.Dim,  # speaker_label time
  speech_time_dim: nn.Dim,  # audio features time
  duration_time_dim: nn.Dim,  # durations time
  **kwargs):
  net = net_module(**kwargs)
  out = net(text=nn.get_extern_data(phoneme_data),
            durations=nn.get_extern_data(duration_data),
            speaker_labels=nn.get_extern_data(label_data),
            target_speech=nn.get_extern_data(audio_data),
            time_dim=time_dim,
            label_time=label_time_dim,
            speech_time=speech_time_dim,
            duration_time=duration_time_dim
  )
  out.mark_as_default_output()

  return net
```

@albertz @JackTemaki any ideas what goes wrong here? Manual construction as below works, so the model itself should be fine.
```python
serializer = nn.ReturnnConfigSerializer(name_ctx_network)
base_string = serializer.get_base_extern_data_py_code_str()
network_string = serializer.get_ext_net_dict_py_code_str(net, ref_extern_data_dims_via_global_config=True,
                                                             with_imports=True)
```

**Comment by albertz** [comment]
I now moved the issue over to RETURNN itself. It looks like the fix in #1068 is purely on RETURNN side, and I think no change in returnn-common is needed anymore. Even if not, I think it is more useful to have the issue here, as we have changes/fixes on RETURNN side in any case.

**Comment by albertz** [comment]
@Atticus1806 
I also added the returnn-common test `test_returnn_config_direct_construction` now.
Can you verify that it works for you now?

**Comment by Atticus1806** [comment]
The linear layer test works now. But I am getting a weird different error on both my other networks now. I am not sure if this is related to this issue. There seems to be some issue in `obj_diff_str`, but from the error message the diffs seem not to have diffs (e.g.  `value_self = <local> {Dim{F'audio_features_feature'(80)}: Dim{F'dec_linear'(80)}}` vs. `value_other = <local> {Dim{F'audio_features_feature'(80)}: Dim{F'dec_linear'(80)}}`) in the representation so maybe the difference in `.batch` is causing this and I am not sure if just the diff function is simply wrongly crashing and this is intended to happen or whats going on there. If you say its not related I can open a new issue. 

```python
EXCEPTION
Traceback (most recent call last):
  File "/u/hilmes/experiments/tts_new_sis/work/i6_core/tools/git/CloneGitRepositoryJob.rYBuJf2ULa45/output/repository/rnn.py", line 11, in <module>
    line: main()
    locals:
      main = <local> <function main at 0x147f9a8fce50>
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.rYBuJf2ULa45/output/repository/returnn/__main__.py", line 657, in main
    line: execute_main_task()
    locals:
      execute_main_task = <global> <function execute_main_task at 0x147f9a8fcd30>
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.rYBuJf2ULa45/output/repository/returnn/__main__.py", line 456, in execute_main_task
    line: engine.train()
    locals:
      engine = <global> <returnn.tf.engine.Engine object at 0x147f660f8d90>
      engine.train = <global> <bound method Engine.train of <returnn.tf.engine.Engine object at 0x147f660f8d90>>
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.rYBuJf2ULa45/output/repository/returnn/tf/engine.py", line 1449, in Engine.train
    line: self.init_train_epoch()
    locals:
      self = <local> <returnn.tf.engine.Engine object at 0x147f660f8d90>
      self.init_train_epoch = <local> <bound method Engine.init_train_epoch of <returnn.tf.engine.Engine object at 0x147f660f8d90>>
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.rYBuJf2ULa45/output/repository/returnn/tf/engine.py", line 1474, in Engine.init_train_epoch
    line: self.init_new_network(new_network_desc)
    locals:
      self = <local> <returnn.tf.engine.Engine object at 0x147f660f8d90>
      self.init_new_network = <local> <bound method Engine.init_new_network of <returnn.tf.engine.Engine object at 0x147f660f8d90>>
      new_network_desc = <local> {'ctc_model_mean_absolute_difference_reduce': {'class': 'copy', 'from': 'mean_absolute_difference', 'loss': 'as_is', 'out_shape': {Dim{'phonemes_time'[B(-1)]}, Dim{B}}}, 'ctc_model_mean_absolute_difference_0_reduce': {'class': 'copy', 'from': 'mean_absolute_difference_0', 'loss': 'as_is', 'out_sh..., len = 23
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.rYBuJf2ULa45/output/repository/returnn/tf/engine.py", line 1382, in Engine.init_new_network
    line: print("reinit because network description differs. Diff:",
                dict_diff_str(self.network.layers_desc, net_desc), file=log.v3)
    locals:
      print = <builtin> <built-in function print>
      dict_diff_str = <local> <function dict_diff_str at 0x147f9a9615e0>
      self = <local> <returnn.tf.engine.Engine object at 0x147f660f8d90>
      self.network = <local> <TFNetwork '' train=<tf.Tensor 'globals/train_flag:0' shape=() dtype=bool>>
      self.network.layers_desc = <local> {'ctc_model_mean_absolute_difference_reduce': {'class': 'copy', 'from': 'mean_absolute_difference', 'loss': 'as_is', 'out_shape': {Dim{'phonemes_time'[B]}, Dim{B}}}, 'ctc_model_mean_absolute_difference_0_reduce': {'class': 'copy', 'from': 'mean_absolute_difference_0', 'loss': 'as_is', 'out_shape'..., len = 23
      net_desc = <local> {'ctc_model_mean_absolute_difference_reduce': {'class': 'copy', 'from': 'mean_absolute_difference', 'loss': 'as_is', 'out_shape': {Dim{'phonemes_time'[B(-1)]}, Dim{B}}}, 'ctc_model_mean_absolute_difference_0_reduce': {'class': 'copy', 'from': 'mean_absolute_difference_0', 'loss': 'as_is', 'out_sh..., len = 23
      file = <not found>
      log = <global> <returnn.log.Log object at 0x147f9a9955e0>
      log.v3 = <global> <returnn.log.Stream object at 0x147f661968e0>
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.rYBuJf2ULa45/output/repository/returnn/util/basic.py", line 1111, in dict_diff_str
    line: return obj_diff_str(DictAsObj(self), DictAsObj(other))
    locals:
      obj_diff_str = <global> <function obj_diff_str at 0x147f9a961550>
      DictAsObj = <global> <class 'returnn.util.basic.DictAsObj'>
      self = <local> {'ctc_model_mean_absolute_difference_reduce': {'class': 'copy', 'from': 'mean_absolute_difference', 'loss': 'as_is', 'out_shape': {Dim{'phonemes_time'[B]}, Dim{B}}}, 'ctc_model_mean_absolute_difference_0_reduce': {'class': 'copy', 'from': 'mean_absolute_difference_0', 'loss': 'as_is', 'out_shape'..., len = 23
      other = <local> {'ctc_model_mean_absolute_difference_reduce': {'class': 'copy', 'from': 'mean_absolute_difference', 'loss': 'as_is', 'out_shape': {Dim{'phonemes_time'[B(-1)]}, Dim{B}}}, 'ctc_model_mean_absolute_difference_0_reduce': {'class': 'copy', 'from': 'mean_absolute_difference_0', 'loss': 'as_is', 'out_sh..., len = 23
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.rYBuJf2ULa45/output/repository/returnn/util/basic.py", line 1094, in obj_diff_str
    line: s += ["  " + line for line in dict_diff_str(value_self, value_other).splitlines()]
    locals:
      s = <local> ["attrib 'concat' dict differs:", "  attrib 'from' differ. self: (('enc_lstm_fw', Dim{F'enc_lstm_dim'(256)}), ('enc_lstm_bw', Dim{F'enc_lstm_dim'(256)})), other: (('enc_lstm_fw', Dim{F'enc_lstm_dim'(256)}), ('enc_lstm_bw', Dim{F'enc_lstm_dim'(256)}))", "  attrib 'out_shape' differ. self: {Dim{'ph..., len = 530, _[0]: {len = 29}
      line = <not found>
      dict_diff_str = <global> <function dict_diff_str at 0x147f9a9615e0>
      value_self = <local> {'class': 'reinterpret_data', 'set_dim_tags': {Dim{F'audio_features_feature'(80)}: Dim{F'dec_linear'(80)}}, 'from': 'data:audio_features', 'out_shape': {Dim{'audio_features_time'[B(-1)]}, Dim{B}, Dim{F'dec_linear'(80)}}}
      value_other = <local> {'class': 'reinterpret_data', 'set_dim_tags': {Dim{F'audio_features_feature'(80)}: Dim{F'dec_linear'(80)}}, 'from': 'data:audio_features', 'out_shape': {Dim{'audio_features_time'[B(-1)]}, Dim{B}, Dim{F'dec_linear'(80)}}}
      splitlines = <not found>
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.rYBuJf2ULa45/output/repository/returnn/util/basic.py", line 1111, in dict_diff_str
    line: return obj_diff_str(DictAsObj(self), DictAsObj(other))
    locals:
      obj_diff_str = <global> <function obj_diff_str at 0x147f9a961550>
      DictAsObj = <global> <class 'returnn.util.basic.DictAsObj'>
      self = <local> {'class': 'reinterpret_data', 'set_dim_tags': {Dim{F'audio_features_feature'(80)}: Dim{F'dec_linear'(80)}}, 'from': 'data:audio_features', 'out_shape': {Dim{'audio_features_time'[B(-1)]}, Dim{B}, Dim{F'dec_linear'(80)}}}
      other = <local> {'class': 'reinterpret_data', 'set_dim_tags': {Dim{F'audio_features_feature'(80)}: Dim{F'dec_linear'(80)}}, 'from': 'data:audio_features', 'out_shape': {Dim{'audio_features_time'[B(-1)]}, Dim{B}, Dim{F'dec_linear'(80)}}}
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.rYBuJf2ULa45/output/repository/returnn/util/basic.py", line 1094, in obj_diff_str
    line: s += ["  " + line for line in dict_diff_str(value_self, value_other).splitlines()]
    locals:
      s = <local> ["attrib 'out_shape' differ. self: {Dim{'audio_features_time'[B(-1)]}, Dim{B}, Dim{F'dec_linear'(80)}}, other: {Dim{'audio_features_time'[B(-1)]}, Dim{B}, Dim{F'dec_linear'(80)}}", "attrib 'set_dim_tags' dict differs:"], _[0]: {len = 176}
      line = <not found>
      dict_diff_str = <global> <function dict_diff_str at 0x147f9a9615e0>
      value_self = <local> {Dim{F'audio_features_feature'(80)}: Dim{F'dec_linear'(80)}}
      value_other = <local> {Dim{F'audio_features_feature'(80)}: Dim{F'dec_linear'(80)}}
      splitlines = <not found>
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.rYBuJf2ULa45/output/repository/returnn/util/basic.py", line 1111, in dict_diff_str
    line: return obj_diff_str(DictAsObj(self), DictAsObj(other))
    locals:
      obj_diff_str = <global> <function obj_diff_str at 0x147f9a961550>
      DictAsObj = <global> <class 'returnn.util.basic.DictAsObj'>
      self = <local> {Dim{F'audio_features_feature'(80)}: Dim{F'dec_linear'(80)}}
      other = <local> {Dim{F'audio_features_feature'(80)}: Dim{F'dec_linear'(80)}}
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.rYBuJf2ULa45/output/repository/returnn/util/basic.py", line 1078, in obj_diff_str
    line: value_self = getattr(self, attrib, not_specified)
    locals:
      value_self = <not found>
      getattr = <builtin> <built-in function getattr>
      self = <local> <returnn.util.basic.DictAsObj object at 0x147ea5244df0>
      attrib = <local> Dim{F'audio_features_feature'(80)}
      not_specified = <local> <not-specified>
TypeError: getattr(): attribute name must be string
```
