### ISSUE TITLE
Unable to run the demo model for IAM dataset

### ISSUE THREAD

**Issue by harshgrovr** [rwth-i6/returnn#108]
I do not have gpu in my system hence running demo(version) , but I am getting following output:

```
converting IAM_lines to features/raw/demo.h5
features/raw/demo.h5
0 / 3
RETURNN starting up, version 20190111.133209--git-afe13c4-dirty, date/time 2019-01-12-18-00-51 (UTC+0100), pid 17169, cwd /home/harsh/Downloads/DCA_Project/returnn/demos/mdlstm/IAM, Python /home/harsh/anaconda3/bin/python
RETURNN command line options: ['config_demo']
Hostname: harsh-ThinkPad-L470
Theano: 0.9.0 (<site-package> in /home/harsh/anaconda3/lib/python3.6/site-packages/theano)
pynvml not available, memory information missing
Device cpuX proc starting up, pid 17187
Device cpuX proc: THEANO_FLAGS = 'compiledir_format=compiledir_%(platform)s-%(processor)s-%(python_version)s-%(python_bitwidth)s--dev-cpuZ,device=cpu,force_device=True'
Device train-network: Used data keys: ['classes', 'data', 'sizes']
calculating gradients ... [                       0.00%                        ]exclude: cpuX W_conv0
calculating gradients ... [                       1.09%                        ]exclude: cpuX b_conv0
calculating gradients ... [                       2.17%                        ]exclude: cpuX W_conv1
calculating gradients ... [|                      3.26%                        ]exclude: cpuX b_conv1
calculating gradients ... [|                      4.35%                        ]exclude: cpuX W_conv2
calculating gradients ... [||                     5.43%                        ]exclude: cpuX b_conv2
calculating gradients ... [||                     6.52%                        ]exclude: cpuX W_conv3
calculating gradients ... [|||                    7.61%                        ]exclude: cpuX b_conv3
calculating gradients ... [|||                    8.70%                        ]exclude: cpuX W_conv4
calculating gradients ... [||||                   9.78%                        ]exclude: cpuX b_conv4
calculating gradients ... [||||                   10.87%                       ]exclude: cpuX U1_mdlstm0
calculating gradients ... [|||||                  11.96%                       ]exclude: cpuX U2_mdlstm0
calculating gradients ... [|||||                  13.04%                       ]exclude: cpuX U3_mdlstm0
calculating gradients ... [||||||                 14.13%                       ]exclude: cpuX U4_mdlstm0
calculating gradients ... [||||||                 15.22%                       ]exclude: cpuX V1_mdlstm0
calculating gradients ... [|||||||                16.30%                       ]exclude: cpuX V2_mdlstm0
calculating gradients ... [|||||||                17.39%                       ]exclude: cpuX V3_mdlstm0
calculating gradients ... [||||||||               18.48%                       ]exclude: cpuX V4_mdlstm0
calculating gradients ... [||||||||               19.57%                       ]exclude: cpuX W1_mdlstm0
calculating gradients ... [|||||||||              20.65%                       ]exclude: cpuX W2_mdlstm0
calculating gradients ... [|||||||||              21.74%                       ]exclude: cpuX W3_mdlstm0
calculating gradients ... [||||||||||             22.83%                       ]exclude: cpuX W4_mdlstm0
calculating gradients ... [||||||||||             23.91%                       ]exclude: cpuX b1_mdlstm0
calculating gradients ... [|||||||||||            25.00%                       ]exclude: cpuX b2_mdlstm0
calculating gradients ... [|||||||||||            26.09%                       ]exclude: cpuX b3_mdlstm0
calculating gradients ... [|||||||||||            27.17%                       ]exclude: cpuX b4_mdlstm0
calculating gradients ... [||||||||||||           28.26%                       ]exclude: cpuX U1_mdlstm1
calculating gradients ... [||||||||||||           29.35%                       ]exclude: cpuX U2_mdlstm1
calculating gradients ... [|||||||||||||          30.43%                       ]exclude: cpuX U3_mdlstm1
calculating gradients ... [|||||||||||||          31.52%                       ]exclude: cpuX U4_mdlstm1
calculating gradients ... [||||||||||||||         32.61%                       ]exclude: cpuX V1_mdlstm1
calculating gradients ... [||||||||||||||         33.70%                       ]exclude: cpuX V2_mdlstm1
calculating gradients ... [|||||||||||||||        34.78%                       ]exclude: cpuX V3_mdlstm1
calculating gradients ... [|||||||||||||||        35.87%                       ]exclude: cpuX V4_mdlstm1
calculating gradients ... [||||||||||||||||       36.96%                       ]exclude: cpuX W1_mdlstm1
calculating gradients ... [||||||||||||||||       38.04%                       ]exclude: cpuX W2_mdlstm1
calculating gradients ... [|||||||||||||||||      39.13%                       ]exclude: cpuX W3_mdlstm1
calculating gradients ... [|||||||||||||||||      40.22%                       ]exclude: cpuX W4_mdlstm1
calculating gradients ... [||||||||||||||||||     41.30%                       ]exclude: cpuX b1_mdlstm1
calculating gradients ... [||||||||||||||||||     42.39%                       ]exclude: cpuX b2_mdlstm1
calculating gradients ... [|||||||||||||||||||    43.48%                       ]exclude: cpuX b3_mdlstm1
calculating gradients ... [|||||||||||||||||||    44.57%                       ]exclude: cpuX b4_mdlstm1
calculating gradients ... [||||||||||||||||||||   45.65%                       ]exclude: cpuX U1_mdlstm2
calculating gradients ... [||||||||||||||||||||   46.74%                       ]exclude: cpuX U2_mdlstm2
calculating gradients ... [|||||||||||||||||||||  47.83%                       ]exclude: cpuX U3_mdlstm2
calculating gradients ... [|||||||||||||||||||||  48.91%                       ]exclude: cpuX U4_mdlstm2
calculating gradients ... [|||||||||||||||||||||| 50.00%                       ]exclude: cpuX V1_mdlstm2
calculating gradients ... [|||||||||||||||||||||| 51.09%                       ]exclude: cpuX V2_mdlstm2
calculating gradients ... [|||||||||||||||||||||| 52.17%                       ]exclude: cpuX V3_mdlstm2
calculating gradients ... [|||||||||||||||||||||| 53.26% |                     ]exclude: cpuX V4_mdlstm2
calculating gradients ... [|||||||||||||||||||||| 54.35% |                     ]exclude: cpuX W1_mdlstm2
calculating gradients ... [|||||||||||||||||||||| 55.43% ||                    ]exclude: cpuX W2_mdlstm2
calculating gradients ... [|||||||||||||||||||||| 56.52% ||                    ]exclude: cpuX W3_mdlstm2
calculating gradients ... [|||||||||||||||||||||| 57.61% |||                   ]exclude: cpuX W4_mdlstm2
calculating gradients ... [|||||||||||||||||||||| 58.70% |||                   ]exclude: cpuX b1_mdlstm2
calculating gradients ... [|||||||||||||||||||||| 59.78% ||||                  ]exclude: cpuX b2_mdlstm2
calculating gradients ... [|||||||||||||||||||||| 60.87% ||||                  ]exclude: cpuX b3_mdlstm2
calculating gradients ... [|||||||||||||||||||||| 61.96% |||||                 ]exclude: cpuX b4_mdlstm2
calculating gradients ... [|||||||||||||||||||||| 63.04% |||||                 ]exclude: cpuX U1_mdlstm3
calculating gradients ... [|||||||||||||||||||||| 64.13% ||||||                ]exclude: cpuX U2_mdlstm3
calculating gradients ... [|||||||||||||||||||||| 65.22% ||||||                ]exclude: cpuX U3_mdlstm3
calculating gradients ... [|||||||||||||||||||||| 66.30% |||||||               ]exclude: cpuX U4_mdlstm3
calculating gradients ... [|||||||||||||||||||||| 67.39% |||||||               ]exclude: cpuX V1_mdlstm3
calculating gradients ... [|||||||||||||||||||||| 68.48% ||||||||              ]exclude: cpuX V2_mdlstm3
calculating gradients ... [|||||||||||||||||||||| 69.57% ||||||||              ]exclude: cpuX V3_mdlstm3
calculating gradients ... [|||||||||||||||||||||| 70.65% |||||||||             ]exclude: cpuX V4_mdlstm3
calculating gradients ... [|||||||||||||||||||||| 71.74% |||||||||             ]exclude: cpuX W1_mdlstm3
calculating gradients ... [|||||||||||||||||||||| 72.83% ||||||||||            ]exclude: cpuX W2_mdlstm3
calculating gradients ... [|||||||||||||||||||||| 73.91% ||||||||||            ]exclude: cpuX W3_mdlstm3
calculating gradients ... [|||||||||||||||||||||| 75.00% |||||||||||           ]exclude: cpuX W4_mdlstm3
calculating gradients ... [|||||||||||||||||||||| 76.09% |||||||||||           ]exclude: cpuX b1_mdlstm3
calculating gradients ... [|||||||||||||||||||||| 77.17% |||||||||||           ]exclude: cpuX b2_mdlstm3
calculating gradients ... [|||||||||||||||||||||| 78.26% ||||||||||||          ]exclude: cpuX b3_mdlstm3
calculating gradients ... [|||||||||||||||||||||| 79.35% ||||||||||||          ]exclude: cpuX b4_mdlstm3
calculating gradients ... [|||||||||||||||||||||| 80.43% |||||||||||||         ]exclude: cpuX U1_mdlstm4
calculating gradients ... [|||||||||||||||||||||| 81.52% |||||||||||||         ]exclude: cpuX U2_mdlstm4
calculating gradients ... [|||||||||||||||||||||| 82.61% ||||||||||||||        ]exclude: cpuX U3_mdlstm4
calculating gradients ... [|||||||||||||||||||||| 83.70% ||||||||||||||        ]exclude: cpuX U4_mdlstm4
calculating gradients ... [|||||||||||||||||||||| 84.78% |||||||||||||||       ]exclude: cpuX V1_mdlstm4
calculating gradients ... [|||||||||||||||||||||| 85.87% |||||||||||||||       ]exclude: cpuX V2_mdlstm4
calculating gradients ... [|||||||||||||||||||||| 86.96% ||||||||||||||||      ]exclude: cpuX V3_mdlstm4
calculating gradients ... [|||||||||||||||||||||| 88.04% ||||||||||||||||      ]exclude: cpuX V4_mdlstm4
calculating gradients ... [|||||||||||||||||||||| 89.13% |||||||||||||||||     ]exclude: cpuX W1_mdlstm4
calculating gradients ... [|||||||||||||||||||||| 90.22% |||||||||||||||||     ]exclude: cpuX W2_mdlstm4
calculating gradients ... [|||||||||||||||||||||| 91.30% ||||||||||||||||||    ]exclude: cpuX W3_mdlstm4
calculating gradients ... [|||||||||||||||||||||| 92.39% ||||||||||||||||||    ]exclude: cpuX W4_mdlstm4
calculating gradients ... [|||||||||||||||||||||| 93.48% |||||||||||||||||||   ]exclude: cpuX b1_mdlstm4
calculating gradients ... [|||||||||||||||||||||| 94.57% |||||||||||||||||||   ]exclude: cpuX b2_mdlstm4
calculating gradients ... [|||||||||||||||||||||| 95.65% ||||||||||||||||||||  ]exclude: cpuX b3_mdlstm4
calculating gradients ... [|||||||||||||||||||||| 96.74% ||||||||||||||||||||  ]exclude: cpuX b4_mdlstm4
using adam with nag and momentum schedule                                       
Device cpuX proc, pid 17187 is ready for commands.
Devices: Used in multiprocessing mode.
parsing file features/raw/demo.h5
Preloading cache from 0 to 3
loading file 1/1 features/raw/demo.h5
cached 3 seqs 0.008542824536561966 GB (fully loaded, 3.333333333954215 GB left over)
Train data:
  input: 1 x 1
  output: {'classes': (79, 1), 'sizes': (2, 1), 'data': [1, 2]}
  HDF dataset, sequences: 3, frames: 764399
Devices:
  cpu0: cpu0 (units: 1 clock: 2.37Ghz memory: 2.0GB) working on 1 batch (update on device)
Learning-rate-control: no file specified, not saving history (no proper restart possible)
using adam with nag and momentum schedule
Network layer topology:
  input #: 1
  hidden 1Dto2D '1Dto2D' #: 1
  hidden source 'classes_source' #: 2
  hidden conv2 'conv0' #: 15
  hidden conv2 'conv1' #: 45
  hidden conv2 'conv2' #: 75
  hidden conv2 'conv3' #: 105
  hidden conv2 'conv4' #: 105
  hidden mdlstm 'mdlstm0' #: 30
  hidden mdlstm 'mdlstm1' #: 60
  hidden mdlstm 'mdlstm2' #: 90
  hidden mdlstm 'mdlstm3' #: 120
  hidden mdlstm 'mdlstm4' #: 120
  output softmax 'output' #: 80
net params #: 2627660
net trainable params: [W_conv0, b_conv0, W_conv1, b_conv1, W_conv2, b_conv2, W_conv3, b_conv3, W_conv4, b_conv4, U1_mdlstm0, U2_mdlstm0, U3_mdlstm0, U4_mdlstm0, V1_mdlstm0, V2_mdlstm0, V3_mdlstm0, V4_mdlstm0, W1_mdlstm0, W2_mdlstm0, W3_mdlstm0, W4_mdlstm0, b1_mdlstm0, b2_mdlstm0, b3_mdlstm0, b4_mdlstm0, U1_mdlstm1, U2_mdlstm1, U3_mdlstm1, U4_mdlstm1, V1_mdlstm1, V2_mdlstm1, V3_mdlstm1, V4_mdlstm1, W1_mdlstm1, W2_mdlstm1, W3_mdlstm1, W4_mdlstm1, b1_mdlstm1, b2_mdlstm1, b3_mdlstm1, b4_mdlstm1, U1_mdlstm2, U2_mdlstm2, U3_mdlstm2, U4_mdlstm2, V1_mdlstm2, V2_mdlstm2, V3_mdlstm2, V4_mdlstm2, W1_mdlstm2, W2_mdlstm2, W3_mdlstm2, W4_mdlstm2, b1_mdlstm2, b2_mdlstm2, b3_mdlstm2, b4_mdlstm2, U1_mdlstm3, U2_mdlstm3, U3_mdlstm3, U4_mdlstm3, V1_mdlstm3, V2_mdlstm3, V3_mdlstm3, V4_mdlstm3, W1_mdlstm3, W2_mdlstm3, W3_mdlstm3, W4_mdlstm3, b1_mdlstm3, b2_mdlstm3, b3_mdlstm3, b4_mdlstm3, U1_mdlstm4, U2_mdlstm4, U3_mdlstm4, U4_mdlstm4, V1_mdlstm4, V2_mdlstm4, V3_mdlstm4, V4_mdlstm4, W1_mdlstm4, W2_mdlstm4, W3_mdlstm4, W4_mdlstm4, b1_mdlstm4, b2_mdlstm4, b3_mdlstm4, b4_mdlstm4, W_in_mdlstm4_output, b_output]
start training at epoch 1 and batch 0
using batch size: 600000, max seqs: 10
learning rate control: ConstantLearningRate(defaultLearningRate=0.0005, minLearningRate=0.0, defaultLearningRates={1: 0.0005, 25: 0.0003, 35: 0.0001}, errorMeasureKey=None, relativeErrorAlsoRelativeToLearningRate=False, minNumEpochsPerNewLearningRate=0, filename=None), epoch data: 1: EpochData(learningRate=0.0005, error={}), 25: EpochData(learningRate=0.0003, error={}), 35: EpochData(learningRate=0.0001, error={}), error key: None
pretrain: None
start epoch 1 with learning rate 0.0005 ...
starting task train
running 2 sequence slices (569522 nts) of batch 0 on device cpu0
Device cpuX proc exception: Input dimension mis-match. (input[1].shape[2] = 120, input[2].shape[2] = 105)
Apply node that caused the error: Elemwise{Mul}[(0, 2)](TensorConstant{(1, 1, 1) .. 1.3333334}, Elemwise{Composite{Cast{float32}(Cast{int64}(LT(i0, i1)))}}[(0, 0)].0, Alloc.0)
Toposort index: 346
Inputs types: [TensorType(float32, (True, True, True)), TensorType(float32, (True, True, False)), TensorType(float32, 3D)]
Inputs shapes: [(1, 1, 1), (1, 1, 120), (1747, 2, 105)]
Inputs strides: [(4, 4, 4), (480, 480, 4), (840, 420, 4)]
Inputs values: [array([[[1.3333334]]], dtype=float32), 'not shown', 'not shown']
Outputs clients: [[Reshape{2}(Elemwise{Mul}[(0, 2)].0, MakeVector{dtype='int64'}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
Unhandled exception <class 'ValueError'> in thread <_MainThread(MainThread, started 139886695794432)>, proc 17187.

Thread current, main, <_MainThread(MainThread, started 139886695794432)>:
(Excluded thread.)

That were all threads.
EXCEPTION
Traceback (most recent call last):
  File "/home/harsh/Downloads/DCA_Project/returnn/Device.py", line 1040, in process
    line: self.process_inner(device, config, self.update_specs, asyncTask)
    locals:
      self = <local> <Device.Device object at 0x7f39d64a6d68>
      self.process_inner = <local> <bound method Device.process_inner of <Device.Device object at 0x7f39d64a6d68>>
      device = <local> 'cpuX'
      config = <local> <Config.Config object at 0x7f39cee2c518>
      self.update_specs = <local> {'update_rule': 'global', 'update_params': {}, 'layers': [], 'block_size': 0}
      asyncTask = <local> <TaskSystem.AsyncTask object at 0x7f39d6925320>
  File "/home/harsh/Downloads/DCA_Project/returnn/Device.py", line 1191, in process_inner
    line: output, outputs_format = self.compute_run(task)
    locals:
      output = <not found>
      outputs_format = <not found>
      self = <local> <Device.Device object at 0x7f39d64a6d68>
      self.compute_run = <local> <bound method Device.compute_run of <Device.Device object at 0x7f39d64a6d68>>
      task = <local> 'train'
  File "/home/harsh/Downloads/DCA_Project/returnn/Device.py", line 881, in compute_run
    line: block_output = func(batch_start, batch_end)
    locals:
      block_output = <not found>
      func = <local> <theano.compile.function_module.Function object at 0x7f39c4314828>
      batch_start = <local> 0
      batch_end = <local> 2
  File "/home/harsh/anaconda3/lib/python3.6/site-packages/theano/compile/function_module.py", line 898, in __call__
    line: gof.link.raise_with_op(
              node=self.fn.nodes[self.fn.position_of_error],
              thunk=thunk,
              storage_map=getattr(self.fn, 'storage_map', None))
    locals:
      gof = <global> <module 'theano.gof' from '/home/harsh/anaconda3/lib/python3.6/site-packages/theano/gof/__init__.py'>
      gof.link = <global> <module 'theano.gof.link' from '/home/harsh/anaconda3/lib/python3.6/site-packages/theano/gof/link.py'>
      gof.link.raise_with_op = <global> <function raise_with_op at 0x7f39d62bd950>
      node = <not found>
      self = <local> <theano.compile.function_module.Function object at 0x7f39c4314828>
      self.fn = <local> <theano.gof.vm.CVM object at 0x7f39bd7502a8>
      self.fn.nodes = <local> [ScalarFromTensor(<TensorType(int64, scalar)>), Shape_i{1}(y_sizes), Shape_i{0}(y_sizes), ScalarFromTensor(<TensorType(int64, scalar)>), Shape_i{0}(b_output), InplaceDimShuffle{x,x,0}(b_output), Shape_i{0}(<TensorType(int32, matrix)>), Shape_i{1}(<TensorType(int32, matrix)>), InplaceDimShuffle{x,..., len = 374
      self.fn.position_of_error = <local> 346
      thunk = <local> <function Op.make_c_thunk.<locals>.rval at 0x7f39bd1ecd08>
      storage_map = <not found>
      getattr = <builtin> <built-in function getattr>
  File "/home/harsh/anaconda3/lib/python3.6/site-packages/theano/gof/link.py", line 325, in raise_with_op
    line: reraise(exc_type, exc_value, exc_trace)
    locals:
      reraise = <global> <function reraise at 0x7f39d6423510>
      exc_type = <local> <class 'ValueError'>
      exc_value = <local> ValueError("Input dimension mis-match. (input[1].shape[2] = 120, input[2].shape[2] = 105)\nApply node that caused the error: Elemwise{Mul}[(0, 2)](TensorConstant{(1, 1, 1) .. 1.3333334}, Elemwise{Composite{Cast{float32}(Cast{int64}(LT(i0, i1)))}}[(0, 0)].0, Alloc.0)\nToposort index: 346\nInputs t...
      exc_trace = <local> <traceback object at 0x7f39b81a9a88>
  File "/home/harsh/anaconda3/lib/python3.6/site-packages/six.py", line 692, in reraise
    line: raise value.with_traceback(tb)
    locals:
      value = <local> None
      value.with_traceback = <local> !AttributeError: 'NoneType' object has no attribute 'with_traceback'
      tb = <local> None
  File "/home/harsh/anaconda3/lib/python3.6/site-packages/theano/compile/function_module.py", line 884, in __call__
    line: self.fn() if output_subset is None else\
    locals:
      self = <local> <theano.compile.function_module.Function object at 0x7f39c4314828>
      self.fn = <local> <theano.gof.vm.CVM object at 0x7f39bd7502a8>
      output_subset = <local> None
      else\ = <not found>
**ValueError: Input dimension mis-match. (input[1].shape[2] = 120, input[2].shape[2] = 105)**
Apply node that caused the error: Elemwise{Mul}[(0, 2)](TensorConstant{(1, 1, 1) .. 1.3333334}, Elemwise{Composite{Cast{float32}(Cast{int64}(LT(i0, i1)))}}[(0, 0)].0, Alloc.0)
Toposort index: 346
Inputs types: [TensorType(float32, (True, True, True)), TensorType(float32, (True, True, False)), TensorType(float32, 3D)]
Inputs shapes: [(1, 1, 1), (1, 1, 120), (1747, 2, 105)]
Inputs strides: [(4, 4, 4), (480, 480, 4), (840, 420, 4)]
Inputs values: [array([[[1.3333334]]], dtype=float32), 'not shown', 'not shown']
Outputs clients: [[Reshape{2}(Elemwise{Mul}[(0, 2)].0, MakeVector{dtype='int64'}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
Dev cpu0 proc died: recv_bytes EOFError: 
device crashed on batch 0
Save model from epoch 0 under models/mdlstm_demo.001.crash_0
```

**Comment by albertz** [comment]
I wonder, how can you run this at all without a GPU? As far as I know, the MDLSTM only works with GPU.

**Comment by albertz** [comment]
I'm closing as there is no response.
