### ISSUE TITLE
compile_tf_graph.py does not support configs written with `get_network`

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#1103]
The compile script currently assumes a given `network`, see exception below. If there are no objections, I would add an `epoch` parameter, and adapt the code so that the script can be used to compile an arbitrary network defined via `get_network`.

```python
EXCEPTION
Traceback (most recent call last):
  File "/u/rossenbach/experiments/tts_asr_2021/work/i6_core/tools/git/CloneGitRepositoryJob.bsiPD5PZPug1/output/repository/tools/compile_tf_graph.py", line 1605, in <module>
    line: main(sys.argv)
    locals:
      main = <local> <function main at 0x7f0e59d853a0>
      sys = <local> <module 'sys' (built-in)>
      sys.argv = <local> ['/u/rossenbach/experiments/tts_asr_2021/work/i6_core/tools/git/CloneGitRepositoryJob.bsiPD5PZPug1/output/repository/tools/compile_tf_graph.py', '/u/rossenbach/experiments/tts_asr_2021/work/i6_core/returnn/compile/CompileTFGraphJob.THAA8Bg4KlbI/output/returnn.config', '--train=0', '--eval=0', '--..., len = 9, _[0]: {len = 140}
  File "/u/rossenbach/experiments/tts_asr_2021/work/i6_core/tools/git/CloneGitRepositoryJob.bsiPD5PZPug1/output/repository/tools/compile_tf_graph.py", line 1511, in main
    line: assert 'network' in config.typed_dict
    locals:
      config = <global> <returnn.config.Config object at 0x7f0e59db8f10>
      config.typed_dict = <global> {'use_tensorflow': True, 'log': None, 'log_verbosity': 4, 'task': '/u/rossenbach/experiments/tts_asr_2021/work/i6_core/tools/git/CloneGitRepositoryJob.bsiPD5PZPug1/output/repository/tools/compile_tf_graph.py', 'device': 'cpu', 'config': {}, '__file__': '/u/rossenbach/experiments/tts_asr_2021/work..., len = 40
AssertionError
```

**Comment by albertz** [comment]
The behavior should be backward compatible. I.e. `epoch=None` by default or so, and that would always use `network` when available, and otherwise throw an error (just as it is right now). Only with `epoch is not None`, it would also check `get_network`, and then maybe also the pretrain logic.

**Comment by albertz** [comment]
Btw, an alternative would be that you just prepare the config specifically for this script, by adding `network = get_network(epoch)` or so.

**Comment by albertz** [comment]
No response? But I assume duplicate of #1088, so closing this.

**Comment by JackTemaki** [comment]
Sorry missed this one, yes is a duplicate
