### ISSUE TITLE
TensorFlow error: Check failed: cudnnSetTensorNdDescriptor ...

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#1191]
```
...
[Thread 0x7fff04df2700 (LWP 18878) exited]
Data{'data', [B,T|'time'[B],F|F'input'(3)]} <tf.Tensor 'extern_data/placeholders/data/data:0' shape=(?, ?, 3) dtype=float32>: shape [3, 7, 3]
2022-10-27 11:57:59.411909: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2022-10-27 11:58:02.723376: F tensorflow/stream_executor/cuda/cuda_dnn.cc:533] Check failed: cudnnSetTensorNdDescriptor(handle_.get(), elem_type, nd, dims.data(), strides.data()) == CUDNN_STATUS_SUCCESS (3 vs. 0)batch_descriptor: {count: 3 feature_map_count: 3 spatial: 1 0  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}

Thread 32 "python3" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff055f3700 (LWP 18877)]
0x00007ffff7282438 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7282438 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff728403a in __GI_abort () at abort.c:89
#2  0x00007fffd9d57fe7 in tensorflow::internal::LogMessageFatal::~LogMessageFatal() ()
   from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#3  0x00007fffcbf26fe4 in stream_executor::gpu::(anonymous namespace)::CudnnTensorDescriptor::CudnnTensorDescriptor(stream_executor::dnn::BatchDescriptor const&, cudnnDataType_t) ()
   from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.so.2
#4  0x00007fffcbf2ef37 in stream_executor::gpu::CudnnSupport::DoPoolForward(stream_executor::Stream*, stream_executor::dnn::PoolingDescriptor const&, stream_executor::dnn::BatchDescriptor const&, stream_executor::DeviceMemory<float> const&, stream_executor::dnn::BatchDescriptor const&, stream_executor::DeviceMemory<float>*, stream_executor::ScratchAllocator*) ()
   from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.so.2
#5  0x00007fffd9867c16 in stream_executor::Stream::ThenPoolForward(stream_executor::dnn::PoolingDescriptor const&, stream_executor::dnn::BatchDescriptor const&, stream_executor::DeviceMemory<float> const&, stream_executor::dnn::BatchDescriptor const&, stream_executor::DeviceMemory<float>*, stream_executor::ScratchAllocator*) ()
   from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#6  0x00007fffd5bf751e in tensorflow::DnnPoolingOp<float>::Compute(tensorflow::OpKernelContext*, stream_executor::dnn::PoolingMode, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, tensorflow::Padding, tensorflow::TensorFormat, tensorflow::Tensor const&, tensorflow::TensorShape const&, bool) () from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#7  0x00007fffd5bb9373 in tensorflow::MaxPoolingNoMaskOp<Eigen::GpuDevice, float>::Compute(tensorflow::OpKernelContext*) () from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#8  0x00007fffcb8e765c in tensorflow::BaseGPUDevice::Compute(tensorflow::OpKernel*, tensorflow::OpKernelContext*) () from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.so.2
#9  0x00007fffcb9ab2d4 in tensorflow::(anonymous namespace)::ExecutorState<tensorflow::PropagatorState>::Process(tensorflow::PropagatorState::TaggedNode, long long) ()
   from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.so.2
#10 0x00007fffcb9abd7f in std::_Function_handler<void (), tensorflow::(anonymous namespace)::ExecutorState<tensorflow::PropagatorState>::ScheduleReady(absl::lts_2020_02_25::InlinedVector<tensorflow::PropagatorState::TaggedNode, 8ul, std::allocator<tensorflow::PropagatorState::TaggedNode> >*, tensorflow::PropagatorState::TaggedNodeReadyQueue*)::{lambda()#2}>::_M_invoke(std::_Any_data const&) ()
   from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.so.2
#11 0x00007fffcba57b92 in Eigen::ThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int) ()
   from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.so.2
#12 0x00007fffcba54008 in std::_Function_handler<void (), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
   from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.so.2
#13 0x00007fffcba45539 in tensorflow::(anonymous namespace)::PThread::ThreadFn(void*) ()
   from /u/zeyer/.local/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.so.2
#14 0x00007ffff761e6ba in start_thread (arg=0x7fff055f3700) at pthread_create.c:333
#15 0x00007ffff735451d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

Via:
```python
def test_RandomLayer_zero_shape():
  # https://github.com/rwth-i6/returnn/issues/1190
  from returnn.tf.util.data import batch_dim, SpatialDim, FeatureDim
  time_dim = SpatialDim('time')
  time_pool_dim = SpatialDim("time-pool")
  input_dim = FeatureDim('input', 3)
  config = Config({"extern_data": {"data": {"dim_tags": (batch_dim, time_dim, input_dim)}}})
  net_dict = {
    'pool': {"class": "pool", "pool_size": [100], "mode": "max", "from": "data", "out_spatial_dims": [time_pool_dim]},
    'random': {
      'class': 'random',
      'shape': [batch_dim, time_pool_dim, input_dim],
      "shape_deps": ["pool"],
      'distribution': 'normal',
      'mean': 0.0,
      'stddev': 1.0,
    },
    'output': {
      'class': 'combine', "kind": "add",
      'from': ['random', 'pool'],  # the order is relevant to test shape_deps
      'out_shape': {batch_dim, time_pool_dim, input_dim}
    }
  }
  with make_scope() as session:
    net = TFNetwork(config=config)
    net.construct_from_dict(net_dict)
    net.initialize_params(session)
    out = net.get_default_output_layer().output.copy_as_time_major()
    out_np, out_seq_lens = session.run(
      (out.placeholder, out.get_sequence_lengths()), feed_dict=make_feed_dict(net.extern_data))
    print(out_np)
    print(out_seq_lens)
    assert (out_seq_lens == 0).all()
```

This test was actually intended for #1190 but it crashes already in the max-pooling, as you see.

**Comment by albertz** [comment]
Related:
https://stackoverflow.com/questions/54122858/check-failed-cudnnsettensornddescriptor-when-transfer-learning-with-pretraine
https://stackoverflow.com/questions/54290753/f-tensorflow-stream-executor-cuda-cuda-dnn-cc522-check-failed
https://github.com/keras-team/keras/issues/14934
https://github.com/tensorflow/tensorflow/issues/57502

**Comment by albertz** [comment]
The error for `RandomLayer` (#1190) is very related. I added a workaround for `RandomLayer` with `tf.cond` to dynamically check whether the output has zero elements, and in that case use `tf.zeros` instead.

For `PoolLayer`, I really want to avoid such a workaround, as this might have some impact on the speed. This really should be fixed on TF side.

Or we just ignore it anyway. It's probably rare and I think it has never occurred yet in any real setup. This only occurred in this very special crafted test case.

**Comment by albertz** [comment]
I will close this for now, as this should be fixed on TF side, and we really don't want to have any overhead on RETURNN side for this.
