### ISSUE TITLE
Attention-ASR setup not working anymore

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#1253]
Our current ASR setup does not work beginning from commit 7eee625cef492601cc2f639674860ce320cd5356.

The full log (including network and stacktrace) can be found here: https://gist.github.com/JackTemaki/a338415827154833662615cbd9a8d8c3

Unfortunately I do not have time to debug this.

**Comment by albertz** [comment]
Which setup exactly?

It would be nice to have a test case covering this.

**Comment by albertz** [comment]
For reference, that was the PR #1246.

**Comment by JackTemaki** [comment]
> Which setup exactly?
> 
> It would be nice to have a test case covering this.

My latest conformer-encoder + transformer decoder bpe-attention librispeech model:
https://github.com/rwth-i6/i6_experiments/tree/main/users/rossenbach/experiments/librispeech/librispeech_960_attention/conformer_baseline_2023

**Comment by albertz** [comment]
For reference, some maybe relevant parts of the log:
```
RETURNN starting up, version 1.20201127.150026+git.d7e3101b, date/time 2023-02-01-11-38-40 (UTC+0000), pid 304888, cwd /work/asr4/rossenbach/sisyphus_work_folders/tts_asr_2021_work/i6_core/returnn/search/ReturnnSearchJobV2.86l8tez6CF3w/work, Python /work/asr4/rossenbach/neon_test/python_310_tf29_pip/bin/python
RETURNN command line options: ['/u/rossenbach/experiments/tts_asr_2021/work/i6_core/returnn/search/ReturnnSearchJobV2.86l8tez6CF3w/output/returnn.config']
Hostname: cn-233
TensorFlow: 2.9.1 (v2.9.0-18-gd8ce9f9c301) (<site-package> in /work/asr4/rossenbach/neon_test/python_310_tf29_pip/lib/python3.10/site-packages/tensorflow)
...
layer /'data:audio_features': [B,T|'time:var:extern_data:audio_features'[B],F|F'feature:audio_features'(1)] float32
layer /'stft': [B,T|'stft:conv:s0'[B],F|F'stft:channel'(257)] complex64
layer /'abs': [B,T|'stft:conv:s0'[B],F|F'stft:channel'(257)] float32
...
layer /'transformer_decoder_01_att_key': [B,T|'lstm1_pool:conv:s0'[B],F'transformer_decoder_01_att_key_split_dims0'(8),F|F'transformer_decoder_01_att_key_split_dims1'(64)] float32
DEPRECATION WARNING: DotLayer: Axes must be referenced by tag or special specified, not by int.
This will be disallowed with behavior_version 3.
Failed to initialize layers:
  <_TemplateLayer 'output/transformer_decoder_01_self_att_ln_rel_pos_enc' uninitialized, construction stack 'transformer_decoder_01_self_att_att'>
  <_TemplateLayer 'output/transformer_decoder_02_self_att_ln_rel_pos_enc' uninitialized, construction stack 'transformer_decoder_02_self_att_att'>
  <_TemplateLayer 'output/transformer_decoder_03_self_att_ln_rel_pos_enc' uninitialized, construction stack 'transformer_decoder_03_self_att_att'>
  <_TemplateLayer 'output/transformer_decoder_04_self_att_ln_rel_pos_enc' uninitialized, construction stack 'transformer_decoder_04_self_att_att'>
  <_TemplateLayer 'output/transformer_decoder_05_self_att_ln_rel_pos_enc' uninitialized, construction stack 'transformer_decoder_05_self_att_att'>
  <_TemplateLayer 'output/transformer_decoder_06_self_att_ln_rel_pos_enc' uninitialized, construction stack 'transformer_decoder_06_self_att_att'>
Check the further debug output for the partial construction and other exceptions.
<_SubnetworkRecCell '/output(rec-subnet)'>: exception constructing template network (for deps and data shapes)
Most recent construction stack:
<_TemplateLayer(CompareLayer)(:template:compare) output/'end' out_type=Data{[B&Beam{'output/output'}(12)], dtype='bool', ctx=loop('dyn-time:output'[?])} (construction stack None)>, kwargs:
{'_name': 'end',
 '_network': <TFNetwork '/output(rec-subnet)' parent_net=<TFNetwork '' train=False search> train=False search>,
 'kind': 'equal',
 'name': 'end',
 'network': <TFNetwork '/output(rec-subnet)' parent_net=<TFNetwork '' train=False search> train=False search>,
 'output': Data{'output_output', [B&Beam{'output/output'}(12)], dtype='bool', ctx=loop('dyn-time:output'[?])},
 'sources': [<_TemplateLayer(ChoiceLayer)(:template:choice) output/'output' out_type=Data{[B&Beam{'output/output'}(12)], dtype='int32', sparse_dim=Dim{F'bpe_labels:sparse-dim'(10025)}, ctx=loop('dyn-time:output'[?])} (construction stack None)>],
 'value': 0}
...

EXCEPTION
Traceback (most recent call last):
  File "/u/rossenbach/src/returnn/returnn/tf/layers/rec.py", line 1537, in _SubnetworkRecCell._construct_template.<locals>.RecSubnetGetTemplateLayer.__call__
    line: res_layer = self.net.construct_layer(
            net_dict=self.net_dict, name=name,
            get_layer=default_get_layer, add_layer=default_get_layer.add_templated_layer)
    locals:
      res_layer = <local> None
      self = <local> <_SubnetworkRecCell '/output(rec-subnet)'>
      self.net = <local> <TFNetwork '/output(rec-subnet)' parent_net=<TFNetwork '' train=False search> train=False search>
      self.net.construct_layer = <local> <bound method TFNetwork.construct_layer of <TFNetwork '/output(rec-subnet)' parent_net=<TFNetwork '' train=False search> train=False search>>
      net_dict = <not found>
      self.net_dict = <local> {'output_prob': {'class': 'softmax', 'from': 'decoder', 'target': 'bpe_labels', 'loss': 'ce', 'loss_opts': {'label_smoothing': 0.1}, 'forward_weights_init': "variance_scaling_initializer(mode='fan_avg', distribution='uniform', scale=1.0)"}, 'output': {'class': 'choice', 'target': 'bpe_labels', 'b..., len = 145
      name = <local> 'transformer_decoder_01_self_att_ln_rel_pos_enc', len = 46
      get_layer = <not found>
      default_get_layer = <local> <RecLayer construct template GetLayer>(allow_uninitialized_template False, parents 'output <- output_prob <- decoder <- transformer_decoder_06 <- transformer_decoder_06_ff_out <- transformer_decoder_06_ff_drop <- transformer_decoder_06_ff_conv2 <- transformer_decoder_06_ff_conv1 <- transformer_de...
      add_layer = <not found>
      default_get_layer.add_templated_layer = <local> <bound method _SubnetworkRecCell._construct_template.<locals>.RecSubnetGetTemplateLayer.add_templated_layer of <RecLayer construct template GetLayer>(allow_uninitialized_template False, parents 'output <- output_prob <- decoder <- transformer_decoder_06 <- transformer_decoder_06_ff_out <- transfo...
  File "/u/rossenbach/src/returnn/returnn/tf/network.py", line 1116, in TFNetwork.construct_layer
    line: return add_layer(name=name_with_prefix, layer_class=layer_class, **layer_desc)
    locals:
      add_layer = <local> <bound method _SubnetworkRecCell._construct_template.<locals>.RecSubnetGetTemplateLayer.add_templated_layer of <RecLayer construct template GetLayer>(allow_uninitialized_template False, parents 'output <- output_prob <- decoder <- transformer_decoder_06 <- transformer_decoder_06_ff_out <- transfo...
      name = <local> 'transformer_decoder_01_self_att_ln_rel_pos_enc', len = 46
      name_with_prefix = <local> 'transformer_decoder_01_self_att_ln_rel_pos_enc', len = 46
      layer_class = <local> <class 'returnn.tf.layers.rec.RelativePositionalEncodingLayer'>
      layer_desc = <local> {'n_out': 64, 'forward_weights_init': "variance_scaling_initializer(mode='fan_avg', distribution='uniform', scale=1.0)", 'clipping': 16, '_network': <TFNetwork '/output(rec-subnet)' parent_net=<TFNetwork '' train=False search> train=False search>, '_name': 'transformer_decoder_01_self_att_ln_rel_..., len = 6
  File "/u/rossenbach/src/returnn/returnn/tf/layers/rec.py", line 1441, in _SubnetworkRecCell._construct_template.<locals>.RecSubnetGetTemplateLayer.add_templated_layer
    line: layer_.kwargs["output"].sanity_check(ignore_placeholder=True)  # placeholder might be overwritten later
    locals:
      layer_ = <local> <_TemplateLayer 'output/transformer_decoder_01_self_att_ln_rel_pos_enc' uninitialized, construction stack 'transformer_decoder_01_self_att_att'>
      layer_.kwargs = <local> {'n_out': 64, 'forward_weights_init': "variance_scaling_initializer(mode='fan_avg', distribution='uniform', scale=1.0)", 'clipping': 16, '_network': <TFNetwork '/output(rec-subnet)' parent_net=<TFNetwork '' train=False search> train=False search>, '_name': 'transformer_decoder_01_self_att_ln_rel_..., len = 9
      sanity_check = <not found>
      ignore_placeholder = <not found>
  File "/u/rossenbach/src/returnn/returnn/tf/util/data.py", line 3056, in Data.sanity_check
    line: assert tag.dyn_size_ext
    locals:
      tag = <local> Dim{'transformer_decoder_01_self_att_ln_rel_pos_enc_rel_pos_enc_time'[?]{ctx=loop('dyn-time:output'[?])}}
      tag.dyn_size_ext = <local> None
AssertionError

EXCEPTION
...
  File "/u/rossenbach/src/returnn/returnn/tf/layers/rec.py", line 7089, in SelfAttentionLayer.get_out_data_from_opts
    line: out = out.copy_as_batch_major().copy_with_feature_last()
    locals:
      out = <local> Data{'transformer_decoder_01_self_att_att_output', [F|F'target_embed_raw:feature-dense'(512)], ctx=loop('dyn-time:output'[?])}
      out.copy_as_batch_major = <local> <bound method Data.copy_as_batch_major of Data{'transformer_decoder_01_self_att_att_output', [F|F'target_embed_raw:feature-dense'(512)], ctx=loop('dyn-time:output'[?])}>
      copy_with_feature_last = <not found>
  File "/u/rossenbach/src/returnn/returnn/tf/util/data.py", line 3347, in Data.copy_as_batch_major
    line: return self.copy_with_batch_dim_axis(0)
    locals:
      self = <local> Data{'transformer_decoder_01_self_att_att_output', [F|F'target_embed_raw:feature-dense'(512)], ctx=loop('dyn-time:output'[?])}
      self.copy_with_batch_dim_axis = <local> <bound method Data.copy_with_batch_dim_axis of Data{'transformer_decoder_01_self_att_att_output', [F|F'target_embed_raw:feature-dense'(512)], ctx=loop('dyn-time:output'[?])}>
  File "/u/rossenbach/src/returnn/returnn/tf/util/data.py", line 3363, in Data.copy_with_batch_dim_axis
    line: assert self.batch_dim_axis is not None
    locals:
      self = <local> Data{'transformer_decoder_01_self_att_att_output', [F|F'target_embed_raw:feature-dense'(512)], ctx=loop('dyn-time:output'[?])}
      self.batch_dim_axis = <local> None
AssertionError

EXCEPTION
...
  File "/u/rossenbach/src/returnn/returnn/tf/layers/basic.py", line 7434, in DotLayer.get_out_data_from_opts
    line: assert len(a_rem_axes) == len(b_rem_axes), "%s: sources %r, red1 %r, red2 %r, var1 %r, var2 %r" % (
            name, sources, red1, red2, var1, var2)
    locals:
      len = <builtin> <built-in function len>
      a_rem_axes = <local> [0, 2]
      b_rem_axes = <local> [0]
      name = <local> 'transformer_decoder_01_att_energy', len = 33
      sources = <local> [<SplitDimsLayer 'transformer_decoder_01_att_key' out_type=Data{[B,T|'lstm1_pool:conv:s0'[B],F'transformer_decoder_01_att_key_split_dims0'(8),F|F'transformer_decoder_01_att_key_split_dims1'(64)]}>, <_TemplateLayer(SplitDimsLayer)(:template:split_dims) output/'transformer_decoder_01_att_query' out...
      red1 = <local> -1
      red2 = <local> -1
      var1 = <local> 'T'
      var2 = <local> 'T?'
AssertionError: transformer_decoder_01_att_energy: sources [<SplitDimsLayer 'transformer_decoder_01_att_key' out_type=Data{[B,T|'lstm1_pool:conv:s0'[B],F'transformer_decoder_01_att_key_split_dims0'(8),F|F'transformer_decoder_01_att_key_split_dims1'(64)]}>, <_TemplateLayer(SplitDimsLayer)(:template:split_dims) output/'transformer_decoder_01_att_query' out_type=Data{[F'transformer_decoder_01_att_query_split_dims0'(8),F|F'transformer_decoder_01_att_query_split_dims1'(64)], ctx=loop('dyn-time:output'[?])} (construction stack 'transformer_decoder_01_att_energy')>], red1 -1, red2 -1, var1 'T', var2 'T?'

EXCEPTION
...
  File "/u/rossenbach/src/returnn/returnn/tf/layers/basic.py", line 2181, in SoftmaxOverSpatialLayer._get_axis_to_reduce
    line: assert input_data.have_time_axis(), "%s: requires that the input has a time dim" % exception_prefix
    locals:
      input_data = <local> Data{'transformer_decoder_01_att_weights_output', [], ctx=loop('dyn-time:output'[?])}
      input_data.have_time_axis = <local> <bound method Data.have_time_axis of Data{'transformer_decoder_01_att_weights_output', [], ctx=loop('dyn-time:output'[?])}>
      exception_prefix = <local> "SoftmaxOverSpatialLayer 'transformer_decoder_01_att_weights'", len = 60
AssertionError: SoftmaxOverSpatialLayer 'transformer_decoder_01_att_weights': requires that the input has a time dim

Unhandled exception <class 'AssertionError'> in thread <_MainThread(MainThread, started 139904049754560)>, proc 304888.

Thread current, main, <_MainThread(MainThread, started 139904049754560)>:
(Excluded thread.)

That were all threads.
EXCEPTION
...
  File "/u/rossenbach/src/returnn/returnn/tf/layers/rec.py", line 1441, in _SubnetworkRecCell._construct_template.<locals>.RecSubnetGetTemplateLayer.add_templated_layer
    line: layer_.kwargs["output"].sanity_check(ignore_placeholder=True)  # placeholder might be overwritten later
    locals:
      layer_ = <local> <_TemplateLayer 'output/transformer_decoder_06_self_att_ln_rel_pos_enc' uninitialized, construction stack 'transformer_decoder_06_self_att_att'>
      layer_.kwargs = <local> {'n_out': 64, 'forward_weights_init': "variance_scaling_initializer(mode='fan_avg', distribution='uniform', scale=1.0)", 'clipping': 16, '_network': <TFNetwork '/output(rec-subnet)' parent_net=<TFNetwork '' train=False search> train=False search>, '_name': 'transformer_decoder_06_self_att_ln_rel_..., len = 9
      sanity_check = <not found>
      ignore_placeholder = <not found>
  File "/u/rossenbach/src/returnn/returnn/tf/util/data.py", line 3056, in Data.sanity_check
    line: assert tag.dyn_size_ext
    locals:
      tag = <local> Dim{'transformer_decoder_06_self_att_ln_rel_pos_enc_rel_pos_enc_time'[?]{ctx=loop('dyn-time:output'[?])}}
      tag.dyn_size_ext = <local> None
AssertionError
```
That last sanity check is due to the PR. But all the exceptions look somehow like they should be fixed. That's all the template construction (not really so relevant anymore with returnn_common).

**Comment by albertz** [comment]
Can you post some dump of the config, esp the net dict?

**Comment by JackTemaki** [comment]
> Can you post some dump of the config, esp the net dict?

https://gist.github.com/JackTemaki/b96603d673cdf7391d86ffb7d05894b4

**Comment by albertz** [comment]
Maybe relevant parts of the config:
```python
...

extern_data = {
    "audio_features": {"available_for_inference": True, "shape": (None, 1), "dim": 1},
    "bpe_labels": {
        "available_for_inference": False,
        "shape": (None,),
        "dim": 10025,
        "sparse": True,
    },
}

...

need_data = False

network = {
    ...
    "output": {
        "class": "rec",
        "from": [],
        "unit": {
            "output_prob": {
                "class": "softmax",
                "from": "decoder",
                "target": "bpe_labels",
                "loss": "ce",
                "loss_opts": {"label_smoothing": 0.1},
                "forward_weights_init": "variance_scaling_initializer(mode='fan_avg', distribution='uniform', scale=1.0)",
            },
            "output": {
                "class": "choice",
                "target": "bpe_labels",
                "beam_size": 12,
                "from": "output_prob",
                "initial_output": 0,
            },
            "end": {"class": "compare", "kind": "equal", "from": "output", "value": 0},
            ...

            "transformer_decoder_01_att_energy": {
                "class": "dot",
                "from": [
                    "base:transformer_decoder_01_att_key",
                    "transformer_decoder_01_att_query",
                ],
                "red1": -1,
                "red2": -1,
                "var1": "T",
                "var2": "T?",
            },
            "transformer_decoder_01_att_weights": {
                "class": "softmax_over_spatial",
                "from": "transformer_decoder_01_att_energy",
                "energy_factor": 0.125,
            },
            ...

            "transformer_decoder_01_self_att_ln_rel_pos_enc": {
                "class": "relative_positional_encoding",
                "from": "transformer_decoder_01_self_att_ln",
                "n_out": 64,
                "forward_weights_init": "variance_scaling_initializer(mode='fan_avg', "
                "distribution='uniform', scale=1.0)",
                "clipping": 16,
            },
            "transformer_decoder_01_self_att_att": {
                "class": "self_attention",
                "from": "transformer_decoder_01_self_att_ln",
                "n_out": 512,
                "num_heads": 8,
                "total_key_dim": 512,
                "attention_dropout": 0.1,
                "key_shift": "transformer_decoder_01_self_att_ln_rel_pos_enc",
                "forward_weights_init": "variance_scaling_initializer(mode='fan_avg', "
                "distribution='uniform', scale=0.5)",
                "attention_left_only": True,
            },
            ...

            "transformer_decoder_06_self_att_ln_rel_pos_enc": {
                "class": "relative_positional_encoding",
                "from": "transformer_decoder_06_self_att_ln",
                "n_out": 64,
                "forward_weights_init": "variance_scaling_initializer(mode='fan_avg', "
                "distribution='uniform', scale=1.0)",
                "clipping": 16,
            },
            "transformer_decoder_06_self_att_att": {
                "class": "self_attention",
                "from": "transformer_decoder_06_self_att_ln",
                "n_out": 512,
                "num_heads": 8,
                "total_key_dim": 512,
                "attention_dropout": 0.1,
                "key_shift": "transformer_decoder_06_self_att_ln_rel_pos_enc",
                "forward_weights_init": "variance_scaling_initializer(mode='fan_avg', "
                "distribution='uniform', scale=0.5)",
                "attention_left_only": True,
            },
            ...

            "decoder": {"class": "layer_norm", "from": "transformer_decoder_06"},
        },
        "target": "bpe_labels",
        "max_seq_len": "max_len_from('base:encoder')",
    },
    ...
}

search_output_layer = "decision"
task = "search"

search_data = {
    "class": "MetaDataset",
    "data_map": {
        "audio_features": ("zip_dataset", "data"),
        "bpe_labels": ("zip_dataset", "classes"),
    },
    ...
}
...
```

**Comment by albertz** [comment]
It's maybe the `RelativePositionalEncodingLayer`. In `get_out_data_from_opts`:
```python
      # length will be ``network.get_rec_step_index() + 1``.
      dummy_dim_tag = Dim(
        kind=Dim.Types.Spatial, description="%s_rel_pos_enc_dummy" % name, dimension=1, auto_generated=True)
      time_dim_tag = Dim(
        kind=Dim.Types.Spatial, description="%s_rel_pos_enc_time" % name, dimension=None, auto_generated=True)
      data = data.copy_template_new_dim_tags((dummy_dim_tag, time_dim_tag, feature_dim_tag))
```
The exception occurs because of that `time_dim_tag`. It is not properly initialized. That's what #1246 does not allow anymore.

**Comment by albertz** [comment]
I will make a small test case, and try to fix it.

**Comment by albertz** [comment]
PR (work in progress) #1254.

**Comment by albertz** [comment]
Ok, it should be fixed now. Can you try?

**Comment by JackTemaki** [comment]
Seems to work!
