### ISSUE TITLE
ReturnConfig loads definitions from `__main__.py`

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#1280]
I have no idea at all how I triggered this, but running RETURNN with PyTorch and Python 3.10 causes the following error:

```python
Traceback (most recent call last):
  File "/u/rossenbach/src/returnn/rnn.py", line 11, in <module>
    line: main()
    locals:
      main = <local> <function main at 0x7fade5587f40>
  File "/u/rossenbach/src/returnn/returnn/__main__.py", line 604, in main
    line: init(command_line_options=argv[1:])
    locals:
      init = <global> <function init at 0x7fade5587c70>
      command_line_options = <not found>
      argv = <local> ['/u/rossenbach/src/returnn/rnn.py', '/u/rossenbach/src/returnn/rnn.py', '/u/rossenbach/experiments/tts_asr_2023/work/i6_core/returnn/rasr_training/ReturnnRasrTrainingJob.vciVX4EuCnpj/output/returnn.config'], _[0]: {len = 32}
  File "/u/rossenbach/src/returnn/returnn/__main__.py", line 379, in init
    line: if need_data():
    locals:
      need_data = <global> <function need_data at 0x7fade5587d90>
  File "/u/rossenbach/src/returnn/returnn/__main__.py", line 409, in need_data
    line: if config.has("need_data") and not config.bool("need_data", True):
    locals:
      config = <global> <returnn.config.Config object at 0x7fade5743df0>
      config.has = <global> <bound method Config.has of <returnn.config.Config object at 0x7fade5743df0>>
      config.bool = <global> <bound method Config.bool of <returnn.config.Config object at 0x7fade5743df0>>
  File "/u/rossenbach/src/returnn/returnn/config.py", line 441, in Config.bool
    line: assert isinstance(value, bool)
    locals:
      isinstance = <builtin> <built-in function isinstance>
      value = <local> <function need_data at 0x7fade5587d90>
      bool = <builtin> <class 'bool'>
AssertionError
```

Somehow the `need_data` function definition in the `__main__.py` file was loaded into the config, and now accessing it as boolean causes this error. I do not understand at all how this can happen.

**Comment by albertz** [comment]
You called `rnn.py rnn.py ...`.

**Comment by JackTemaki** [comment]
Oh wow... well then...
