### ISSUE TITLE
RF demo: padding="valid" crashes

### ISSUE THREAD

**Issue by Icemole** [rwth-i6/returnn#1325]
Hi all! I tried running the `demo-rf.config` with the `Conv1d` layers having `padding="valid"` instead of `padding="same"`, but I got the following error:
```
Starting training at epoch 1.
start epoch 1 with learning rate 0.01 ...
Unhandled exception <class 'ValueError'> in thread <_MainThread(MainThread, started 139760954429440)>, proc 14411.

Thread current, main, <_MainThread(MainThread, started 139760954429440)>:
(Excluded thread.)

That were all threads.
EXCEPTION
Traceback (most recent call last):
  File "/home/icemole/Documentos/work/repos/returnn_pytorch/rnn.py", line 11, in <module>
    line: main()
    locals:
      main = <local> <function main at 0x7f1c94db67a0>
  File "/home/icemole/Documentos/work/repos/returnn_pytorch/returnn/__main__.py", line 595, in main
    line: execute_main_task()
    locals:
      execute_main_task = <global> <function execute_main_task at 0x7f1c94db6680>
  File "/home/icemole/Documentos/work/repos/returnn_pytorch/returnn/__main__.py", line 419, in execute_main_task
    line: engine.train()
    locals:
      engine = <global> <returnn.torch.engine.Engine object at 0x7f1c94de20e0>
      engine.train = <global> <bound method Engine.train of <returnn.torch.engine.Engine object at 0x7f1c94de20e0>>
  File "/home/icemole/Documentos/work/repos/returnn_pytorch/returnn/torch/engine.py", line 119, in Engine.train
    line: self.train_epoch()
    locals:
      self = <local> <returnn.torch.engine.Engine object at 0x7f1c94de20e0>
      self.train_epoch = <local> <bound method Engine.train_epoch of <returnn.torch.engine.Engine object at 0x7f1c94de20e0>>
  File "/home/icemole/Documentos/work/repos/returnn_pytorch/returnn/torch/engine.py", line 147, in Engine.train_epoch
    line: self._run_step(data, train_flag=True)
    locals:
      self = <local> <returnn.torch.engine.Engine object at 0x7f1c94de20e0>
      self._run_step = <local> <bound method Engine._run_step of <returnn.torch.engine.Engine object at 0x7f1c94de20e0>>
      data = <local> {'data': tensor([[[1., 0., 0.,  ..., 0., 0., 0.],
                              [0., 0., 0.,  ..., 0., 0., 0.],
                              [0., 0., 0.,  ..., 1., 0., 0.],
                              ...,
                              [0., 0., 0.,  ..., 0., 0., 0.],
                              [0., 0., 0.,  ..., 0., 0., 0.],
                              [0., 0., 0.,  ..., 0., 0., 0.]],
                     
                             [[1., 0., 0.,  ......
      train_flag = <not found>
  File "/home/icemole/Documentos/work/repos/returnn_pytorch/returnn/torch/engine.py", line 324, in Engine._run_step
    line: self._train_step_func(model=self._orig_model, extern_data=extern_data, **sentinel_kw)
    locals:
      self = <local> <returnn.torch.engine.Engine object at 0x7f1c94de20e0>
      self._train_step_func = <local> <function train_step at 0x7f1c94cd1ab0>
      model = <not found>
      self._orig_model = <local> <Model>
      extern_data = <local> TensorDict({'data': Tensor{'data', [B?,'time'[B?],'in'(9)]}, 'classes': Tensor{'classes', [B?,'time'[B?]], dtype='int32', sparse_dim=Dim{'out'(2)}}})
      sentinel_kw = <local> {'__fwd_compatible_random_arg_67': None}
  File "/home/icemole/Documentos/work/repos/returnn_pytorch/demos/demo-rf.config", line 76, in train_step
    line: logits = model(data, spatial_dim=time_dim)
    locals:
      logits = <not found>
      model = <local> <Model>
      data = <local> Tensor{'data', [B?,'time'[B?],'in'(9)]}
      spatial_dim = <not found>
      time_dim = <global> Dim{'time'[B?]}
  File "/home/icemole/Documentos/work/repos/returnn_pytorch/demos/demo-rf.config", line 50, in Model.__call__
    line: x, _ = layer(x, in_spatial_dim=spatial_dim)
    locals:
      x = <local> Tensor{'relu', [B?,F|'hidden'(50),'-2+time+-2'[B?]]}
      _ = <local> Dim{'-2+time+-2'[B?]}
      layer = <local> <Conv1d>
      in_spatial_dim = <not found>
      spatial_dim = <local> Dim{'time'[B?]}
  File "/home/icemole/Documentos/work/repos/returnn_pytorch/returnn/frontend/conv.py", line 101, in _ConvOrTransposedConv._call_nd1
    line: out, (out_spatial_dim,) = self.__class__.__base__.__call__(
              self,
              source,
              in_spatial_dims=[in_spatial_dim],
              out_spatial_dims=[out_spatial_dim] if out_spatial_dim else None,
          )
    locals:
      out = <not found>
      out_spatial_dim = <local> None
      self = <local> <Conv1d>
      self.__class__ = <local> <class 'returnn.frontend.conv.Conv1d'>
      self.__class__.__base__ = <local> <class 'returnn.frontend.conv._Conv'>
      self.__class__.__base__.__call__ = <local> <function _Conv.__call__ at 0x7f1c94c86d40>
      source = <local> Tensor{'relu', [B?,F|'hidden'(50),'-2+time+-2'[B?]]}
      in_spatial_dims = <not found>
      in_spatial_dim = <local> Dim{'time'[B?]}
      out_spatial_dims = <not found>
  File "/home/icemole/Documentos/work/repos/returnn_pytorch/returnn/frontend/conv.py", line 158, in _Conv.__call__
    line: return conv(
              source,
              in_dim=self.in_dim,
              out_dim=self.out_dim,
              in_spatial_dims=in_spatial_dims,
              out_spatial_dims=out_spatial_dims,
              filter=self.filter,
              filter_size=self.filter_size,
              padding=self.padding,
              strides=self.strides,
              dilation_rate=self.dilation_rate,
              groups=self.groups,
              bias=self.bias if self.with_bias else None,
          )
    locals:
      conv = <global> <function conv at 0x7f1c94c86b00>
      source = <local> Tensor{'relu', [B?,F|'hidden'(50),'-2+time+-2'[B?]]}
      in_dim = <not found>
      self = <local> <Conv1d>
      self.in_dim = <local> Dim{'hidden'(50)}
      out_dim = <not found>
      self.out_dim = <local> Dim{'hidden2'(100)}
      in_spatial_dims = <local> [Dim{'time'[B?]}]
      out_spatial_dims = <local> None
      filter = <builtin> <class 'filter'>
      self.filter = <local> Tensor{'parameter', ['hidden2'(100),'hidden'(50),'filter-dim0'(5)]}
      filter_size = <not found>
      self.filter_size = <local> [Dim{'filter-dim0'(5)}]
      padding = <not found>
      self.padding = <local> 'valid'
      strides = <not found>
      self.strides = <local> None
      dilation_rate = <not found>
      self.dilation_rate = <local> None
      groups = <not found>
      self.groups = <local> None
      bias = <not found>
      self.bias = <local> Tensor{'parameter', ['hidden2'(100)]}
      self.with_bias = <local> True
  File "/home/icemole/Documentos/work/repos/returnn_pytorch/returnn/frontend/conv.py", line 193, in conv
    line: raise ValueError(f"conv: source {source} does not have spatial dim {in_spatial_dim}")
    locals:
      ValueError = <builtin> <class 'ValueError'>
ValueError: conv: source Tensor{'relu', [B?,F|'hidden'(50),'-2+time+-2'[B?]]} does not have spatial dim Dim{'time'[B?]}

Process finished with exit code 1
```
To me it seems as if the time dimension got renamed to `'-2+time+-2` for some reason, but I can't figure out where it was renamed. Print debugging says that https://github.com/rwth-i6/returnn/blob/master/returnn/torch/frontend/_backend.py#L1070 is the culprit as `out_spatial_dims` already has the "weird" name, but my PyCharm debugger is stuck at "Evaluating..." and I can't debug further.

How to reproduce: change `padding="same"` to `padding="valid"` in the `rf-demo.config`, and run the demo.

**Comment by albertz** [comment]
But that is not really a bug? It's correct that this crashes. The error is also correct.

**Comment by albertz** [comment]
The dim does not get renamed. It is a new different dim. You get this different spatial dim because there was convolution or pooling before, with valid padding, I assume kernel size 5.

**Comment by Icemole** [comment]
Yes, the kernel size is set to 5.

I see. So because the output map size is shrunk, the dimension is different. Does this mean that several `padding="valid"` convolutional layers can't be stacked? I thought it was theoretically possible.

**Comment by albertz** [comment]
> Does this mean that several `padding="valid"` convolutional layers can't be stacked? I thought it was theoretically possible.

Of course this is possible. But you have to refer to the correct spatial dim then.
```python
x, spatial_dim = conv1(x, spatial_dim=spatial_dim)
x, spatial_dim = conv2(x, spatial_dim=spatial_dim)
```

**Comment by Icemole** [comment]
Ah right, I see. So in this case the spatial dimension is the time dimension, and I was using the original dimension. Anyway, I didn't think of further consequences of `padding="valid"`, for instance that this would have an influence on the cross entropy calculation, as the relationship of logits to classes also changes (6 labels should be dropped from either side of the class labels). Thank you for the explanation, I'll close this issue.
