### ISSUE TITLE
watch_memory crashes with keyerror 

### ISSUE THREAD

**Issue by Max-Ryujin** [rwth-i6/returnn#1449]
## Description
When starting a training the watch_memory thread crashes with error:

### Error message
```
Exception in thread watch_memory:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/work/asr3/vieting/hiwis/kannen/sisyphus_work_dirs/swb/i6_core/tools/git/CloneGitRepositoryJob.FigHMwYJhhef/output/repository/returnn/util/watch_memory.py", line 38, in _watch_memory_thread_main
    print(prefix, f"proc {_format_proc(p)} exited, old:", _format_mem_info(mem_per_pid[p.pid]))
KeyError: 2958633
```
## possible fix
The easiest fix is just to remove the print statement in line 38 which tries to use `mem_per_pid[p.pid]` 
The other way would be to work with a try catch block as it was done a few lines later in line 44-50

## Relavant code:
returnn/util/watch_memory.py
```
    while True:
        change = False
        procs_ = [cur_proc] + cur_proc.children(recursive=True)
        for p in procs:
            if p not in procs_:
     -38---->   print(prefix, f"proc {_format_proc(p)} exited, old:", _format_mem_info(mem_per_pid[p.pid]))
                mem_per_pid.pop(p.pid, None)
                change = True
        procs = procs_

        for p in procs:
            old_mem_info = mem_per_pid.get(p.pid, None)
            try:
                mem_info = get_mem_info(p)
            except psutil.NoSuchProcess:  # race condition, can happen
                if old_mem_info:
                    print(prefix, f"proc {_format_proc(p)} exited, old:", _format_mem_info(old_mem_info))
                    mem_per_pid.pop(p.pid, None)
                    change = True
                continue
```

**Comment by albertz** [comment]
Are you using the latest version?

The question is, how can it happen that `p` is in `procs` and `p.pid` is not in `mem_per_pid`. That was fixed recently by adding `procs.remove(p)` below.

**Comment by Max-Ryujin** [comment]
This is fixed, I used a commit that is a few days old.
