### ISSUE TITLE
error on sampling_loss with adagrad, momentum

### ISSUE THREAD

**Issue by Gerstenberger** [rwth-i6/returnn#145]
I get the following error message when running sampling_loss with adagrad (and momentum)

```
InvalidArgumentError: AttrValue must not have reference type value of float_ref
```

This works fine when using SGD and Adam.

I can provide you an example config file if you need.

Here is the full error message:
```
RETURNN starting up, version 20190221.160124--git-c137aab, date/time 2019-02-28-23-01-28 (UTC+0100), pid 18016, cwd /rwthfs/rz/cluster/work/ag707076/setups/obw/data-train/obw.b-32.b-640.lr-0.001.dr-0.2.adagrad, Python /rwthfs/rz/cluster/home/ag707076/.venv/crnn/bin/python3.6
RETURNN command line options: ['config-train/obw.b-32.b-640.lr-0.001.dr-0.2.adagrad.config']
Hostname: lng01.hpc.itc.rwth-aachen.de
TensorFlow: 1.12.0 (v1.12.0-0-ga6d8ffae09) (<site-package> in /rwthfs/rz/cluster/home/ag707076/.venv/crnn/lib/python3.6/site-packages/tensorflow)

...

session opts {'allow_soft_placement': True, 'log_device_placement': False, 'device_count': {'GPU': 0}, 'intra_op_parallelism_threads': 2, 'inter_op_parallelism_threads': 2}.

...

Network layer topology:
  extern data: data: Data(shape=(None,), dtype='int32', sparse=True, dim=793471), classes: Data(shape=(None,), dtype='int32', sparse=True, dim=793471)
  used data keys: ['classes', 'data']
  layer source 'data' #: 793471
  layer linear 'input' #: 128
  layer rec 'lstm0' #: 2048
  layer rec 'lstm1' #: 2048
  layer softmax 'output' #: 793471
net params #: 1778782975
net trainable params: [<tf.Variable 'input/W:0' shape=(793471, 128) dtype=float32_ref>, <tf.Variable 'lstm0/rec/W:0' shape=(128, 8192) dtype=float32_ref>, <tf.Variable 'lstm0/rec/W_re:0' shape=(2048, 8192) dtype=float32_ref>, <tf.Variable 'lstm0/rec/b:0' shape=(8192,) dtype=float32_ref>, <tf.Variable 'lstm1/rec/W:0' shape=(2048, 8192) dtype=float32_ref>, <tf.Variable 'lstm1/rec/W_re:0' shape=(2048, 8192) dtype=float32_ref>, <tf.Variable 'lstm1/rec/b:0' shape=(8192,) dtype=float32_ref>, <tf.Variable 'output/W:0' shape=(793471, 2048) dtype=float32_ref>, <tf.Variable 'output/b:0' shape=(793471,) dtype=float32_ref>]
start training at epoch 1 and step 0
using batch size: 640, max seqs: 32
learning rate control: NewbobAbs(errorThreshold=-0.01, learningRateDecayFactor=0.95), epoch data: , error key: dev_score_output:exp
pretrain: None
start epoch 1 with learning rate 0.001 ...
TF: log_dir: net-model/train-2019-02-28-22-01-26
Create Adagrad optimizer.
Initialize optimizer (default) with slots ['accumulator'].
2019-02-28 23:03:17.780562: E tensorflow/core/framework/op_segment.cc:54] Create kernel failed: Invalid argument: AttrValue must not have reference type value of float_ref
         for attr 'tensor_type'
        ; NodeDef: {{node output/W/_13}} = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_9_output/W", tensor_type=DT_FLOAT_REF, _device="/job:localhost/replica:0/task:0/device:CPU:0"](); Op<name=_Recv; signature= -> tensor:tensor_type; attr=tensor_type:type; attr=tensor_name:string; attr=send_device:string; attr=send_device_incarnation:int; attr=recv_device:string; attr=client_terminated:bool,default=false; is_stateful=true>
2019-02-28 23:03:17.781086: E tensorflow/core/common_runtime/executor.cc:623] Executor failed to create kernel. Invalid argument: AttrValue must not have reference type value of float_ref
         for attr 'tensor_type'
        ; NodeDef: {{node output/W/_13}} = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_9_output/W", tensor_type=DT_FLOAT_REF, _device="/job:localhost/replica:0/task:0/device:CPU:0"](); Op<name=_Recv; signature= -> tensor:tensor_type; attr=tensor_type:type; attr=tensor_name:string; attr=send_device:string; attr=send_device_incarnation:int; attr=recv_device:string; attr=client_terminated:bool,default=false; is_stateful=true>
         [[{{node output/W/_13}} = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_9_output/W", tensor_type=DT_FLOAT_REF, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Exception InvalidArgumentError() in step 0.
Step meta information:
None
Feed dict:
None
/rwthfs/rz/cluster/home/ag707076/.venv/crnn/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
EXCEPTION
Traceback (most recent call last):
  File "/rwthfs/rz/cluster/home/ag707076/returnn/TFEngine.py", line 542, in run
    line: self.engine.check_uninitialized_vars()
    locals:
      self = <local> <TFEngine.Runner object at 0x7f5fd5932358>
      self.engine = <local> <TFEngine.Engine object at 0x7f60332d2be0>
      self.engine.check_uninitialized_vars = <local> <bound method Engine.check_uninitialized_vars of <TFEngine.Engine object at 0x7f60332d2be0>>
  File "/rwthfs/rz/cluster/home/ag707076/returnn/TFEngine.py", line 1643, in check_uninitialized_vars
    line: var_mask = tf.logical_not(tf.stack(
            [tf.is_variable_initialized(v) for v in var_list])).eval(session=self.tf_session)
    locals:
      var_mask = <not found>
      tf = <global> <module 'tensorflow' from '/rwthfs/rz/cluster/home/ag707076/.venv/crnn/lib/python3.6/site-packages/tensorflow/__init__.py'>
      tf.logical_not = <global> <function logical_not at 0x7f60382d61e0>
      tf.stack = <global> <function stack at 0x7f60382a1ae8>
      tf.is_variable_initialized = <global> <function should_use_result.<locals>.wrapped at 0x7f6037d57620>
      v = <not found>
      var_list = <local> [<tf.Variable 'input/W:0' shape=(793471, 128) dtype=float32_ref>, <tf.Variable 'lstm0/rec/W:0' shape=(128, 8192) dtype=float32_ref>, <tf.Variable 'lstm0/rec/b:0' shape=(8192,) dtype=float32_ref>, <tf.Variable 'lstm0/rec/W_re:0' shape=(2048, 8192) dtype=float32_ref>, <tf.Variable 'lstm1/rec/W:0' s..., len = 19
      eval = <builtin> <built-in function eval>
      session = <not found>
      self = <local> <TFEngine.Engine object at 0x7f60332d2be0>
      self.tf_session = <local> <tensorflow.python.client.session.Session object at 0x7f6034a32390>
  File "/rwthfs/rz/cluster/home/ag707076/.venv/crnn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 713, in eval
    line: return _eval_using_default_session(self, feed_dict, self.graph, session)
    locals:
      _eval_using_default_session = <global> <function _eval_using_default_session at 0x7f603864e488>
      self = <local> <tf.Tensor 'check_uninitialized_vars/LogicalNot:0' shape=(19,) dtype=bool>
      feed_dict = <local> None
      self.graph = <local> <tensorflow.python.framework.ops.Graph object at 0x7f608aafe470>
      session = <local> <tensorflow.python.client.session.Session object at 0x7f6034a32390>
  File "/rwthfs/rz/cluster/home/ag707076/.venv/crnn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5157, in _eval_using_default_session
    line: return session.run(tensors, feed_dict)
    locals:
      session = <local> <tensorflow.python.client.session.Session object at 0x7f6034a32390>
      session.run = <local> <bound method BaseSession.run of <tensorflow.python.client.session.Session object at 0x7f6034a32390>>
      tensors = <local> <tf.Tensor 'check_uninitialized_vars/LogicalNot:0' shape=(19,) dtype=bool>
      feed_dict = <local> None
  File "/rwthfs/rz/cluster/home/ag707076/.venv/crnn/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    line: result = self._run(None, fetches, feed_dict, options_ptr,
                             run_metadata_ptr)
    locals:
      result = <not found>
      self = <local> <tensorflow.python.client.session.Session object at 0x7f6034a32390>
      self._run = <local> <bound method BaseSession._run of <tensorflow.python.client.session.Session object at 0x7f6034a32390>>
      fetches = <local> <tf.Tensor 'check_uninitialized_vars/LogicalNot:0' shape=(19,) dtype=bool>
      feed_dict = <local> None
      options_ptr = <local> None
      run_metadata_ptr = <local> None
  File "/rwthfs/rz/cluster/home/ag707076/.venv/crnn/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    line: results = self._do_run(handle, final_targets, final_fetches,
                                 feed_dict_tensor, options, run_metadata)
    locals:
      results = <not found>
      self = <local> <tensorflow.python.client.session.Session object at 0x7f6034a32390>
      self._do_run = <local> <bound method BaseSession._do_run of <tensorflow.python.client.session.Session object at 0x7f6034a32390>>
      handle = <local> None
      final_targets = <local> []
      final_fetches = <local> [<tf.Tensor 'check_uninitialized_vars/LogicalNot:0' shape=(19,) dtype=bool>]
      feed_dict_tensor = <local> {}
      options = <local> None
      run_metadata = <local> None
  File "/rwthfs/rz/cluster/home/ag707076/.venv/crnn/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    line: return self._do_call(_run_fn, feeds, fetches, targets, options,
                               run_metadata)
    locals:
      self = <local> <tensorflow.python.client.session.Session object at 0x7f6034a32390>
      self._do_call = <local> <bound method BaseSession._do_call of <tensorflow.python.client.session.Session object at 0x7f6034a32390>>
      _run_fn = <local> <function BaseSession._do_run.<locals>._run_fn at 0x7f5fc00f5e18>
      feeds = <local> {}
      fetches = <local> [<tensorflow.python.pywrap_tensorflow_internal.TF_Output; proxy of <Swig Object of type 'TF_Output *' at 0x7f5fc0c56120> >]
      targets = <local> []
      options = <local> None
      run_metadata = <local> None
  File "/rwthfs/rz/cluster/home/ag707076/.venv/crnn/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    line: raise type(e)(node_def, op, message)
    locals:
      type = <builtin> <class 'type'>
      e = <not found>
      node_def = <local> None
      op = <local> None
      message = <local> 'AttrValue must not have reference type value of float_ref\n\t for attr \'tensor_type\'\n\t; NodeDef: {{node output/W/_13}} = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_..., len = 1007
InvalidArgumentError: AttrValue must not have reference type value of float_ref
         for attr 'tensor_type'
        ; NodeDef: {{node output/W/_13}} = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_9_output/W", tensor_type=DT_FLOAT_REF, _device="/job:localhost/replica:0/task:0/device:CPU:0"](); Op<name=_Recv; signature= -> tensor:tensor_type; attr=tensor_type:type; attr=tensor_name:string; attr=send_device:string; attr=send_device_incarnation:int; attr=recv_device:string; attr=client_terminated:bool,default=false; is_stateful=true>
         [[{{node output/W/_13}} = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_9_output/W", tensor_type=DT_FLOAT_REF, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

```

**Comment by Gerstenberger** [comment]
I forgot to add that it works fine when setting `use_full_softmax: True`. I use sampled_softmax (default) as sampling method.

**Comment by kazuki-irie** [comment]
Yes, we are aware of this problem.
Currently, adagrad + sampled softmax works only if you place both the input and output (softmax) embedding weights on CPU (`"param_device": "CPU"`).

**Comment by kazuki-irie** [comment]
If that is too slow, an alternative solution would be to use another optimizer for the output layer...

**Comment by albertz** [comment]
Note that this is because the TF AdaGrad implementation partly is not implemented for GPU. (@kazuki-irie Do you have a corresponding TF GitHub issue link?)

**Comment by kazuki-irie** [comment]
I found one here: https://github.com/tensorlayer/tensorlayer/issues/135

**Comment by albertz** [comment]
I mean a TF GitHub issue link.

**Comment by albertz** [comment]
Found some:
https://github.com/tensorflow/tensorflow/issues/86
https://github.com/tensorflow/tensorflow/issues/13880
https://github.com/tensorflow/tensorflow/issues/1570

**Comment by albertz** [comment]
I guess we cannot do much about it (except using some workaround, like `param_device` option, as Kazuki explained), and otherwise wait for TF upstream to implement this. So I'm closing this now. But feel free to continue the discussion about how to use the workaround if it's not clear.
