### ISSUE TITLE
multi-gpu training: cleanup_old_models called per training process

### ISSUE THREAD

**Issue by kuacakuaca** [rwth-i6/returnn#1452]
https://github.com/rwth-i6/returnn/blob/52abd3ae5bcb3396ec7da40a95b8f68d7db4e832/returnn/torch/engine.py#L358

**Comment by albertz** [comment]
But in `cleanup_old_models`, we have this in the beginning:
```python
        if not self._do_save():
            return
```
So this should not be a problem?

**Comment by albertz** [comment]
Do you have the log? Can you post it?

The code you refer to was always like that. But anyway, try with latest version.

**Comment by kuacakuaca** [comment]
the code you pointed to was not in my returnn version. Now with the newest returnn, the old model cleanup error is gone, but I constantly got following error. It seems to be some synchronisation problem.
```
EXCEPTION
Traceback (most recent call last):
  File "/nas/models/asr/pzheng/returnn_pytorch_backend/work/i6_core/tools/git/CloneGitRepositoryJob.LClNkVyrEDKK/output/repository/rnn.py", line 11, in <module>
    line: main()
    locals:
      main = <local> <function main at 0x14e5df55bf40>
  File "/nas/models/asr/pzheng/returnn_pytorch_backend/work/i6_core/tools/git/CloneGitRepositoryJob.LClNkVyrEDKK/output/repository/returnn/__main__.py", line 634, in main
    line: execute_main_task()
    locals:
      execute_main_task = <global> <function execute_main_task at 0x14e5df55be20>
  File "/nas/models/asr/pzheng/returnn_pytorch_backend/work/i6_core/tools/git/CloneGitRepositoryJob.LClNkVyrEDKK/output/repository/returnn/__main__.py", line 440, in execute_main_task
    line: engine.train()
    locals:
      engine = <global> <returnn.torch.engine.Engine object at 0x14e4f5ba9b70>
      engine.train = <global> <bound method Engine.train of <returnn.torch.engine.Engine object at 0x14e4f5ba9b70>>
  File "/nas/models/asr/pzheng/returnn_pytorch_backend/work/i6_core/tools/git/CloneGitRepositoryJob.LClNkVyrEDKK/output/repository/returnn/torch/engine.py", line 225, in Engine.train
    line: self.train_epoch()
    locals:
      self = <local> <returnn.torch.engine.Engine object at 0x14e4f5ba9b70>
      self.train_epoch = <local> <bound method Engine.train_epoch of <returnn.torch.engine.Engine object at 0x14e4f5ba9b70>>
  File "/nas/models/asr/pzheng/returnn_pytorch_backend/work/i6_core/tools/git/CloneGitRepositoryJob.LClNkVyrEDKK/output/repository/returnn/torch/engine.py", line 278, in Engine.train_epoch
    line: torch.distributed.all_reduce(_has_data, op=torch.distributed.ReduceOp.MIN)
    locals:
      torch = <global> <module 'torch' from '/usr/local/lib/python3.10/dist-packages/torch/__init__.py'>
      torch.distributed = <global> <module 'torch.distributed' from '/usr/local/lib/python3.10/dist-packages/torch/distributed/__init__.py'>
      torch.distributed.all_reduce = <global> <function all_reduce at 0x14e5bd5cc820>
      _has_data = <local> tensor([1], dtype=torch.int8)
      op = <not found>
      torch.distributed.ReduceOp = <global> <class 'torch.distributed.distributed_c10d.ReduceOp'>
      torch.distributed.ReduceOp.MIN = <global> <RedOpType.MIN: 3>
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1451, in broadcast_multigpu
    line: return func(*args, **kwargs)
    locals:
      func = <local> <function all_reduce at 0x14e5bd5cc790>
      args = <local> (tensor([1], dtype=torch.int8),)
      kwargs = <local> {'op': <RedOpType.MIN: 3>}
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1707, in all_reduce
    line: work.wait()
    locals:
      work = <local> <torch.distributed.distributed_c10d.Work object at 0x14e5defc5a70>
      work.wait = <local> <bound method PyCapsule.wait of <torch.distributed.distributed_c10d.Work object at 0x14e5defc5a70>>
RuntimeError: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 1800000ms for recv operation to complete
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 11641 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 11642) of binary: /usr/bin/python3
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/nas/models/asr/pzheng/returnn_pytorch_backend/work/i6_core/tools/git/CloneGitRepositoryJob.LClNkVyrEDKK/output/repository/rnn.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-11-05_06:21:10
  host      : gpu-12.apptek.local
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 11643)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-11-05_06:21:10
  host      : gpu-12.apptek.local
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 11644)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-05_06:21:10
  host      : gpu-12.apptek.local
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 11642)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

**Comment by albertz** [comment]
Please open a new separate issue if this is not related to `cleanup_old_models`.
