### ISSUE TITLE
ncclSystemError: Cannot assign requested address

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#1466]
In PyTorch distributed training, I get:
```
  File "/rwthfs/rz/cluster/home/az668407/setups/combined/2021-05-31/tools/returnn/returnn/torch/engine.py", line 198, in Engine.init_train_from_config
    line: self._ddp_pt_model = self._torch_distributed_class(
              self._pt_model, device_ids=get_device_ids(), **self._torch_distributed_options
          )
  File "/rwthfs/rz/cluster/work/az668407/py-envs/py3.10-torch2.1/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 795, in DistributedDataParallel.__init__
    line: _verify_param_shape_across_processes(self.process_group, parameters)
  File "/rwthfs/rz/cluster/work/az668407/py-envs/py3.10-torch2.1/lib/python3.10/site-packages/torch/distributed/utils.py", line 265, in _verify_param_shape_across_processes 
    line: return dist._verify_params_across_processes(process_group, tensors, logger)
...
DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1333, unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.1 
ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error. 
Last error:
socketStartConnect: Connect to fe80::ba59:9f03:fc:765c%ib0<57829> failed : Cannot assign requested address
```

Maybe related to that:
* https://github.com/rwth-i6/i6_core/issues/459
* https://discuss.pytorch.org/t/multi-gpu-memory-address-assignment-issue-and-semaphore-resource-tracking-issue/162785
* https://github.com/NVIDIA/nccl/issues/975
* https://github.com/NVIDIA/nccl/issues/1016
* https://github.com/google-research/t5x/issues/832
* https://github.com/pytorch/examples/issues/1199
* https://github.com/huggingface/text-generation-inference/issues/1106
* https://github.com/horovod/horovod/issues/2852

_Originally posted by @albertz in https://github.com/rwth-i6/i6_core/issues/459#issuecomment-1826804121_

**Comment by albertz** [comment]
Note that there was a small change w.r.t. the DDP module wrapping, see commit https://github.com/rwth-i6/returnn/commit/90c7548370d75196b9cbe851cb8345abcf8825bc, #1451. I'm not sure if this affected the reported error here, as this error was much earlier, in `Engine.init_train_from_config` / `DistributedDataParallel.__init__`.

**Comment by albertz** [comment]
Now after a restart (also the ITC restarted the nodes), I'm not sure if I see the same error. I had another error in my setup to use Torch AMP with bfloat16, but the V100 GPU does not support that. After fixing that, I had another bug with CUDA device mixup, now also fixed (https://github.com/rwth-i6/returnn/commit/200b7a439f910e67aac63c2db4fb29d13a5dad7d). Now I get a GPU OOM error:
`OutOfMemoryError: CUDA out of memory. Tried to allocate 52.00 MiB. GPU 0 has a total capacty of 31.74 GiB of which 39.62 MiB is free. Process 101553 has 1.19 GiB memory in use. Process 101552 has 1.19 GiB memory in use. Process 101563 has 1.19 GiB memory in use. Process 101549 has 1.19 GiB memory in use. Process 101555 has 1.19 GiB memory in use. Process 101558 has 1.19 GiB memory in use. Process 101557 has 1.19 GiB memory in use. Process 101562 has 1.19 GiB memory in use. Process 101556 has 1.19 GiB memory in use. Process 101560 has 1.19 GiB memory in use. Process 101554 has 1.19 GiB memory in use. Process 101550 has 1.19 GiB memory in use. Process 101561 has 1.19 GiB memory in use. Process 101559 has 1.19 GiB memory in use. Process 101551 has 1.19 GiB memory in use. Including non-PyTorch memory, this process has 13.82 GiB memory in use. Of the allocated memory 11.54 GiB is allocated by PyTorch, and 677.26 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

The procs correspond to all the other procs, as you see here:
```
nd20-01:101560:130074 [12] NCCL INFO comm 0x66a0bb80 rank 12 nranks 16 cudaDev 12 busId e0000 commId 0x66b9ae567fdb3d69 - Init COMPLETE
nd20-01:101552:130510 [4] NCCL INFO comm 0x66a0da90 rank 4 nranks 16 cudaDev 4 busId 57000 commId 0x66b9ae567fdb3d69 - Init COMPLETE
nd20-01:101556:132204 [8] NCCL INFO comm 0x66a112d0 rank 8 nranks 16 cudaDev 8 busId b7000 commId 0x66b9ae567fdb3d69 - Init COMPLETE
nd20-01:101562:130451 [14] NCCL INFO comm 0x66a125d0 rank 14 nranks 16 cudaDev 14 busId e5000 commId 0x66b9ae567fdb3d69 - Init COMPLETE
nd20-01:101548:128664 [0] NCCL INFO comm 0x1553b500 rank 0 nranks 16 cudaDev 0 busId 34000 commId 0x66b9ae567fdb3d69 - Init COMPLETE
nd20-01:101558:130725 [10] NCCL INFO comm 0x66a2d8f0 rank 10 nranks 16 cudaDev 10 busId bc000 commId 0x66b9ae567fdb3d69 - Init COMPLETE
nd20-01:101554:132196 [6] NCCL INFO comm 0x66a0dfa0 rank 6 nranks 16 cudaDev 6 busId 5c000 commId 0x66b9ae567fdb3d69 - Init COMPLETE
nd20-01:101550:130068 [2] NCCL INFO comm 0x66a0f950 rank 2 nranks 16 cudaDev 2 busId 39000 commId 0x66b9ae567fdb3d69 - Init COMPLETE
nd20-01:101551:130072 [3] NCCL INFO comm 0x66a13ce0 rank 3 nranks 16 cudaDev 3 busId 3b000 commId 0x66b9ae567fdb3d69 - Init COMPLETE
nd20-01:101559:130070 [11] NCCL INFO comm 0x66a0aad0 rank 11 nranks 16 cudaDev 11 busId be000 commId 0x66b9ae567fdb3d69 - Init COMPLETE
nd20-01:101563:130080 [15] NCCL INFO comm 0x66a16140 rank 15 nranks 16 cudaDev 15 busId e7000 commId 0x66b9ae567fdb3d69 - Init COMPLETE
nd20-01:101555:130073 [7] NCCL INFO comm 0x66a12270 rank 7 nranks 16 cudaDev 7 busId 5e000 commId 0x66b9ae567fdb3d69 - Init COMPLETE
nd20-01:101553:132201 [5] NCCL INFO comm 0x66a08610 rank 5 nranks 16 cudaDev 5 busId 59000 commId 0x66b9ae567fdb3d69 - Init COMPLETE
nd20-01:101561:132172 [13] NCCL INFO comm 0x66a09420 rank 13 nranks 16 cudaDev 13 busId e2000 commId 0x66b9ae567fdb3d69 - Init COMPLETE
nd20-01:101549:130082 [1] NCCL INFO comm 0x66a0e910 rank 1 nranks 16 cudaDev 1 busId 36000 commId 0x66b9ae567fdb3d69 - Init COMPLETE
nd20-01:101557:130069 [9] NCCL INFO comm 0x66a14580 rank 9 nranks 16 cudaDev 9 busId b9000 commId 0x66b9ae567fdb3d69 - Init COMPLETE
```

I wonder a bit about this. It means every process reserved some memory on every other GPU. This seems suboptimal? But this is probably unrelated to the original issue here.

And additionally:
```
...
  File "/home/az668407/work/py-envs/py3.10-torch2.1/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    line: Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
              tensors,
              grad_tensors_,
              retain_graph,
              create_graph,
              inputs,
              allow_unreachable=True,
              accumulate_grad=True,
          )  # Calls into the C++ engine to run the backward pass
    locals:
      Variable = <global> <class 'torch.autograd.variable.Variable'>
      Variable._execution_engine = <global> <torch._C._EngineBase object at 0x14be0f944050>
      Variable._execution_engine.run_backward = <global> <built-in method run_backward of torch._C._EngineBase object at 0x14be0f944050>
RuntimeError: GET was unable to find an engine to execute this computation
```
This might just be a followup error of the OOM, but I'm not sure.

**Comment by albertz** [comment]
Via #1470, similar (`Cannot assign requested address`) but also a bit different:
```nd20-01:275975:275975 [0] NCCL INFO Bootstrap : Using ib0:fe80::ba59:9f03:fc:765c%ib0<0>                                                       
nd20-01:275975:275975 [0] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory                                                                                                                           
nd20-01:275975:275975 [0] NCCL INFO NET/Plugin : No plugin found, using internal implementation                                                
nd20-01:275975:275975 [0] misc/socket.cc:379 NCCL WARN Call to bind failed : Cannot assign requested address                                   
nd20-01:275975:275975 [0] NCCL INFO bootstrap.cc:176 -> 2                                                                                      
nd20-01:275975:275975 [0] NCCL INFO bootstrap.cc:201 -> 2
Traceback (most recent call last):
  File "/home/az668407/setups/combined/2021-05-31/tools/playground/torch-distributed-demo.py", line 53, in <module>                            
    ddp_model = DistributedDataParallel(model, device_ids=[local_rank])
  File "/home/az668407/work/py-envs/py3.10-torch2.1/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 795, in __init__      
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/az668407/work/py-envs/py3.10-torch2.1/lib/python3.10/site-packages/torch/distributed/utils.py", line 265, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)                                                                
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1251, unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.1
ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error.                                            
Last error:
Call to bind failed : Cannot assign requested address
Traceback (most recent call last):
  File "/home/az668407/setups/combined/2021-05-31/tools/playground/torch-distributed-demo.py", line 53, in <module>                            
    ddp_model = DistributedDataParallel(model, device_ids=[local_rank])
  File "/home/az668407/work/py-envs/py3.10-torch2.1/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 795, in __init__      
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/az668407/work/py-envs/py3.10-torch2.1/lib/python3.10/site-packages/torch/distributed/utils.py", line 265, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
RuntimeError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0')
got error: Connection reset by peer. This may indicate a possible application crash on rank 0 or a network set up issue.
[2023-11-29 18:07:07,192] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 275975) of binary: /home/az668407/work/py-envs/py3.10-torch2.1/bin/python3.10
```
This is actually with the demo from [here](https://github.com/rwth-i6/returnn/issues/1469#issuecomment-1832278817) (also [here](https://github.com/albertz/playground/blob/master/torch-distributed-demo.py)), but the same error happens also with RETURNN.

This also seems non-deterministic. After a restart of the job, even running `torchrun` just again seem to fix it sometimes.

**Comment by albertz** [comment]
So, I think now, in case this problem happens on the IB, this is maybe a (non-deterministic) hardware issue.

**Comment by albertz** [comment]
Again on DGX, I'm debugging probably the same or a similar issue.

```
Torch distributed initialized. Hostname nd20-01.hpc.itc.rwth-aachen.de, pid 191191, rank 0 / size 16, local rank 0 / local size 16.
RETURNN starting up, version 1.20231130.103604+git.5878e5f9, date/time 2023-12-01-10-30-00 (UTC+0100), pid 191191, cwd /rwthfs/rz/cluster/hpcw
ork/az668407/setups-data/combined/2021-05-31/work/i6_core/returnn/training/ReturnnTrainingJob.KHDgdQNqanKz/work, Python /home/az668407/work/py
-envs/py3.10-torch2.1/bin/python3.10
Torch: Hostname nd20-01.hpc.itc.rwth-aachen.de, pid 191191, using GPU 0.
MEMORY: main proc python3.10(191191) initial: rss=1.1GB pss=808.0MB uss=787.3MB shared=324.9MB
MEMORY: main proc python3.10(191191) increased RSS: rss=1.2GB pss=467.7MB uss=39.2MB shared=1.1GB
MEMORY: main proc python3.10(191191) increased RSS: rss=1.3GB pss=597.5MB uss=194.9MB shared=1.1GB
MEMORY: main proc python3.10(191191) increased RSS: rss=1.4GB pss=694.6MB uss=292.3MB shared=1.1GB
MEMORY: main proc python3.10(191191) increased RSS: rss=1.5GB pss=805.8MB uss=403.4MB shared=1.1GB
MEMORY: main proc python3.10(191191) increased RSS: rss=1.6GB pss=0.9GB uss=507.7MB shared=1.1GB
MEMORY: main proc python3.10(191191) increased RSS: rss=2.0GB pss=1.3GB uss=0.9GB shared=1.1GB
nd20-01:191191:191191 [0] NCCL INFO Bootstrap : Using ib0:fe80::ba59:9f03:fc:765c%ib0<0>
nd20-01:191191:191191 [0] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No 
such file or directory
nd20-01:191191:191191 [0] NCCL INFO NET/Plugin : No plugin found, using internal implementation
MEMORY: main proc python3.10(191191) increased RSS: rss=2.6GB pss=2.0GB uss=1.6GB shared=1.1GB
nd20-01:191191:191191 [0] NCCL INFO cudaDriverVersion 12000
nd20-01:191191:219889 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB [1]mlx5_bond_0:1/RoCE [RO]; OOB ib0:fe80::ba59:9f03:fc:765c%ib0<0>
nd20-01:191191:219889 [0] NCCL INFO Using network IB
MEMORY: main proc python3.10(191191) increased RSS: rss=2.7GB pss=2.0GB uss=1.6GB shared=1.1GB
nd20-01:191191:219889 [0] NCCL INFO misc/socket.cc:564 -> 2
nd20-01:191191:219889 [0] NCCL INFO misc/socket.cc:615 -> 2
nd20-01:191191:219889 [0] NCCL INFO bootstrap.cc:270 -> 2
nd20-01:191191:219889 [0] NCCL INFO init.cc:1303 -> 2
nd20-01:191191:219889 [0] NCCL INFO group.cc:64 -> 2 [Async thread]
nd20-01:191191:191191 [0] NCCL INFO group.cc:422 -> 2
nd20-01:191191:191191 [0] NCCL INFO group.cc:106 -> 2 
```
Looking at the NCCL code is interesting, for example [misc/socket.cc](https://github.com/NVIDIA/nccl/blob/v2.18.1-1/src/misc/socket.cc). You see, the first error is [this line](https://github.com/NVIDIA/nccl/blob/d97a32fac84f69cbd022ffdc57d5687c760742c7/src/misc/socket.cc#L564). It uses `NCCLCHECK` there which produces the `NCCL INFO` debug output, showing the line number and that it got a non-success error code, specifically code 2. Code 2 (see [here](https://github.com/NVIDIA/nccl/blob/b6d7438d3145a619f924dbbca6c96db21fab716e/src/nccl.h.in#L39)) is `ncclSystemError`. So `socketPollConnect` fails here ([code](https://github.com/NVIDIA/nccl/blob/d97a32fac84f69cbd022ffdc57d5687c760742c7/src/misc/socket.cc#L485)). I wonder that I don't see any related warning, because in `socketPollConnect`, in most cases when it fails it should have printed some warning. Ok, actually not for the case of `ncclSystemError` in the end (`else if (ret != EINPROGRESS)`). But also the `SYSCHECK` macro could return with `ncclSystemError` (see [here](https://github.com/NVIDIA/nccl/blob/b6d7438d3145a619f924dbbca6c96db21fab716e/src/include/checks.h#L41C9-L41C17)). Or also the `EQCHECK`. But in those cases, there should have been a warning again, which I don't see. So this would mean, it really gets into the `else if (ret != EINPROGRESS)`, the only case (as far as I see) which would not print any warning but return with `ncclSystemError`.
