### ISSUE TITLE
ReturnnDumpHDFJob bug

### ISSUE THREAD

**Issue by NurAd-Din** [rwth-i6/returnn#1472]
Running the ReturnnDumpHDFJob on the current returnn commit eeea993c results in the job crashing due to an assertion error as seen below, however running the job with the same inputs on an older returnn commit 327f43cf had allowed it to work as normal (I don't know if this information is helpful but the a less old commit f1a678fe also does not work and gives the same error):

```
Unhandled exception <class 'AssertionError'> in thread <_MainThread(MainThread, started 139962800121664)>, proc 1044667.

Thread current, main, <_MainThread(MainThread, started 139962800121664)>:
(Excluded thread.)

That were all threads.
EXCEPTION
Traceback (most recent call last):
  File "/u/noureldin.bayoumi/dev/returnn/tools/hdf_dump.py", line 126, in <module>
    line: main(sys.argv)
    locals:
      main = <local> <function main at 0x7f4b989430d0>
      sys = <local> <module 'sys' (built-in)>
      sys.argv = <local> ['/u/noureldin.bayoumi/dev/returnn/tools/hdf_dump.py', 'dataset.config', '/var/tmp/8sn5tzx1.hdf'], _[0]: {len = 50}
      use_progress_bar = <not found>
  File "/u/noureldin.bayoumi/dev/returnn/returnn/datasets/hdf.py", line 1410, in HDFDatasetWriter.dump_from_dataset
              end_seq=parser_args.end_seq,
              use_progress_bar=True,
          )
    locals:
      hdf_dataset = <local> <returnn.datasets.hdf.HDFDatasetWriter object at 0x7f4b9895dfa0>
      hdf_dataset.dump_from_dataset = <local> <bound method HDFDatasetWriter.dump_from_dataset of <returnn.datasets.hdf.HDFDatasetWriter object at 0x7f4b9895dfa0>>
      dataset = <local> <SprintCacheDataset 'train' epoch=1>
      epoch = <not found>
      parser_args = <local> Namespace(config_file_or_dataset='dataset.config', end_seq=inf, epoch=1, hdf_filename='/var/tmp/8sn5tzx1.hdf', start_seq=0)
      parser_args.epoch = <local> 1
      start_seq = <not found>
      parser_args.start_seq = <local> 0
      end_seq = <not found>
      parser_args.end_seq = <local> inf
      use_progress_bar = <not found>
  File "/u/noureldin.bayoumi/dev/returnn/returnn/datasets/hdf.py", line 1410, in HDFDatasetWriter.dump_from_dataset
    line: dataset.init_seq_order(epoch)
    locals:
      dataset = <local> <SprintCacheDataset 'train' epoch=1>
      dataset.init_seq_order = <local> <bound method SprintCacheDataset.init_seq_order of <SprintCacheDataset 'train' epoch=1>>
      epoch = <local> 1
  File "/u/noureldin.bayoumi/dev/returnn/returnn/datasets/sprint.py", line 1215, in SprintCacheDataset.init_seq_order
    line: seq_index = self.get_seq_order_for_epoch(epoch, self.num_seqs, get_seq_len=get_seq_size)
  File "/u/noureldin.bayoumi/dev/returnn/returnn/datasets/sprint.py", line 1215, in SprintCacheDataset.init_seq_order
    line: seq_index = self.get_seq_order_for_epoch(epoch, self.num_seqs, get_seq_len=get_seq_size)
  File "/u/noureldin.bayoumi/dev/returnn/returnn/datasets/sprint.py", line 1215, in SprintCacheDataset.init_seq_order
    line: seq_index = self.get_seq_order_for_epoch(epoch, self.num_seqs, get_seq_len=get_seq_size)
  File "/u/noureldin.bayoumi/dev/returnn/returnn/datasets/sprint.py", line 1215, in SprintCacheDataset.init_seq_order
    line: seq_index = self.get_seq_order_for_epoch(epoch, self.num_seqs, get_seq_len=get_seq_size)
    locals:
      seq_index = <not found>
      self = <local> <SprintCacheDataset 'train' epoch=1>
      self.get_seq_order_for_epoch = <local> <bound method Dataset.get_seq_order_for_epoch of <SprintCacheDataset 'train' epoch=1>>
      epoch = <local> 1
      self.num_seqs = <local> 0
      get_seq_len = <not found>
      self.num_seqs = <local> 0
      get_seq_len = <not found>
      get_seq_size = <local> <function SprintCacheDataset.init_seq_order.<locals>.get_seq_size at 0x7f4b98d473a0>
  File "/u/noureldin.bayoumi/dev/returnn/returnn/datasets/basic.py", line 466, in Dataset.get_seq_order_for_epoch
    line: assert num_seqs > 0
    locals:
      num_seqs = <local> 0
AssertionError

```

**Comment by albertz** [comment]
I pushed a small change. Can you test whether this fixes it?

**Comment by NurAd-Din** [comment]
No it did not :

```
Unhandled exception <class 'ValueError'> in thread <_MainThread(MainThread, started 140236586342208)>, proc 1613914.

Thread current, main, <_MainThread(MainThread, started 140236586342208)>:
(Excluded thread.)

That were all threads.
EXCEPTION
Traceback (most recent call last):
  File "/u/noureldin.bayoumi/dev/returnn/tools/hdf_dump.py", line 126, in <module>
    line: main(sys.argv)
    locals:
      main = <local> <function main at 0x7f8b53af50d0>
      sys = <local> <module 'sys' (built-in)>
      sys.argv = <local> ['/u/noureldin.bayoumi/dev/returnn/tools/hdf_dump.py', 'dataset.config', '/var/tmp/c3nhd4ee.hdf'], _[0]: {len = 50}
  File "/u/noureldin.bayoumi/dev/returnn/tools/hdf_dump.py", line 119, in main
    line: hdf_dump_from_dataset(dataset, hdf_dataset, args)
    locals:
      hdf_dump_from_dataset = <global> <function hdf_dump_from_dataset at 0x7f8b5f88a0d0>
      dataset = <local> <SprintCacheDataset 'train' epoch=1>
      hdf_dataset = <local> <returnn.datasets.hdf.HDFDatasetWriter object at 0x7f8b53b02280>
      args = <local> Namespace(config_file_or_dataset='dataset.config', end_seq=inf, epoch=1, hdf_filename='/var/tmp/c3nhd4ee.hdf', start_seq=0)
  File "/u/noureldin.bayoumi/dev/returnn/tools/hdf_dump.py", line 35, in hdf_dump_from_dataset
    line: hdf_dataset.dump_from_dataset(
              dataset=dataset,
              epoch=parser_args.epoch,
              start_seq=parser_args.start_seq,
              end_seq=parser_args.end_seq,
              use_progress_bar=True,
          )
    locals:
      hdf_dataset = <local> <returnn.datasets.hdf.HDFDatasetWriter object at 0x7f8b53b02280>
      hdf_dataset.dump_from_dataset = <local> <bound method HDFDatasetWriter.dump_from_dataset of <returnn.datasets.hdf.HDFDatasetWriter object at 0x7f8b53b02280>>
      dataset = <local> <SprintCacheDataset 'train' epoch=1>
      epoch = <not found>
      parser_args = <local> Namespace(config_file_or_dataset='dataset.config', end_seq=inf, epoch=1, hdf_filename='/var/tmp/c3nhd4ee.hdf', start_seq=0)
      parser_args.epoch = <local> 1
      start_seq = <not found>
      parser_args.start_seq = <local> 0
      end_seq = <not found>
      parser_args.end_seq = <local> inf
      use_progress_bar = <not found>
  File "/u/noureldin.bayoumi/dev/returnn/returnn/datasets/hdf.py", line 1463, in HDFDatasetWriter.dump_from_dataset
    line: dataset.load_seqs(seq_idx, seq_idx + 1)
    locals:
      dataset = <local> <SprintCacheDataset 'train' epoch=1>
      dataset.load_seqs = <local> <bound method Dataset.load_seqs of <SprintCacheDataset 'train' epoch=1>>
      seq_idx = <local> 0
  File "/u/noureldin.bayoumi/dev/returnn/returnn/datasets/basic.py", line 397, in Dataset.load_seqs
    line: self._load_seqs(start, end)
    locals:
      self = <local> <SprintCacheDataset 'train' epoch=1>
      self._load_seqs = <local> <bound method CachedDataset2._load_seqs of <SprintCacheDataset 'train' epoch=1>>
      start = <local> 0
      end = <local> 1
  File "/u/noureldin.bayoumi/dev/returnn/returnn/datasets/cached2.py", line 121, in CachedDataset2._load_seqs
    line: seqs = [self._collect_single_seq(seq_idx=seq_idx) for seq_idx in range(start, end)]
    locals:
      seqs = <not found>
self = <local> <SprintCacheDataset 'train' epoch=1>
      self._collect_single_seq = <local> <bound method SprintCacheDataset._collect_single_seq of <SprintCacheDataset 'train' epoch=1>>
      seq_idx = <not found>
      range = <builtin> <class 'range'>
      start = <local> 0
      end = <local> 1
  File "/u/noureldin.bayoumi/dev/returnn/returnn/datasets/cached2.py", line 121, in <listcomp>
    line: seqs = [self._collect_single_seq(seq_idx=seq_idx) for seq_idx in range(start, end)]
    locals:
      seqs = <not found>
      self = <local> <SprintCacheDataset 'train' epoch=1>
      self._collect_single_seq = <local> <bound method SprintCacheDataset._collect_single_seq of <SprintCacheDataset 'train' epoch=1>>
      seq_idx = <local> 0
      range = <builtin> <class 'range'>
      start = <not found>
      end = <not found>
  File "/u/noureldin.bayoumi/dev/returnn/returnn/datasets/sprint.py", line 1242, in SprintCacheDataset._collect_single_seq
    line: return self.get_dataset_seq_for_name(seq_idx=seq_idx, name=seq_tag)
    locals:
      self = <local> <SprintCacheDataset 'train' epoch=1>
      self.get_dataset_seq_for_name = <local> <bound method SprintCacheDataset.get_dataset_seq_for_name of <SprintCacheDataset 'train' epoch=1>>
      seq_idx = <local> 0
      name = <not found>
      seq_tag = <local> 'dev-other/116-288045-0000/116-288045-0000', len = 41
  File "/u/noureldin.bayoumi/dev/returnn/returnn/datasets/sprint.py", line 1230, in SprintCacheDataset.get_dataset_seq_for_name
    line: data = {key: d.read(name) for (key, d) in self.data.items()}  # type: typing.Dict[str,numpy.ndarray]
    locals:
      data = <not found>
      key = <not found>
      d = <not found>
      d.read = <not found>
      name = <local> 'dev-other/116-288045-0000/116-288045-0000', len = 41
      self = <local> <SprintCacheDataset 'train' epoch=1>
      self.data = <local> {'data': <returnn.datasets.sprint.SprintCacheDataset.SprintCacheReader object at 0x7f8b5397ad00>}
      self.data.items = <local> <built-in method items of dict object at 0x7f8b53a66a00>
  File "/u/noureldin.bayoumi/dev/returnn/returnn/datasets/sprint.py", line 1230, in <dictcomp>
    line: data = {key: d.read(name) for (key, d) in self.data.items()}  # type: typing.Dict[str,numpy.ndarray]
    locals:
      data = <not found>
      key = <local> 'data'
      d = <local> <returnn.datasets.sprint.SprintCacheDataset.SprintCacheReader object at 0x7f8b5397ad00>
      d.read = <local> <bound method SprintCacheDataset.SprintCacheReader.read of <returnn.datasets.sprint.SprintCacheDataset.SprintCacheReader object at 0x7f8b5397ad00>>
      name = <local> 'dev-other/116-288045-0000/116-288045-0000', len = 41
      self = <not found>
      self.data = <not found>
      self.data.items = <not found>
  File "/u/noureldin.bayoumi/dev/returnn/returnn/datasets/sprint.py", line 1150, in SprintCacheDataset.SprintCacheReader.read
    line: [self.allophone_labeling.state_tying_by_allo_state_idx[a] for (t, a, s) in res], dtype=self.dtype
    locals:
      self = <local> <returnn.datasets.sprint.SprintCacheDataset.SprintCacheReader object at 0x7f8b5397ad00>
      self.allophone_labeling = <local> <returnn.sprint.cache.AllophoneLabeling object at 0x7f8b539855e0>
      self.allophone_labeling.state_tying_by_allo_state_idx = <local> {0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 35, 35: 36, 36: 37, 37: 38, 38: 39, 39:..., len = 316
      a = <not found>
      t = <not found>
      s = <not found>
      res = <local> [(0, 315, None, 1), (1, 315, None, 1), (2, 315, None, 1), (3, 315, None, 1), (4, 315, None, 1), (5, 315, None, 1), (6, 315, None, 1), (7, 315, None, 1), (8, 315, None, 1), (9, 315, None, 1), (10, 315, None, 1), (11, 315, None, 1), (12, 79, None, 1), (13, 315, None, 1), (14, 315, None, 1), (15, 23..., len = 265
dtype = <not found>
      self.dtype = <local> 'int8'
  File "/u/noureldin.bayoumi/dev/returnn/returnn/datasets/sprint.py", line 1150, in <listcomp>
    line: [self.allophone_labeling.state_tying_by_allo_state_idx[a] for (t, a, s) in res], dtype=self.dtype
    locals:
      self = <local> <returnn.datasets.sprint.SprintCacheDataset.SprintCacheReader object at 0x7f8b5397ad00>
      self.allophone_labeling = <local> <returnn.sprint.cache.AllophoneLabeling object at 0x7f8b539855e0>
      self.allophone_labeling.state_tying_by_allo_state_idx = <local> {0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 35, 35: 36, 36: 37, 37: 38, 38: 39, 39:..., len = 316
      a = <not found>
      t = <not found>
      s = <not found>
      res = <not found>
      dtype = <not found>
      self.dtype = <local> 'int8'
ValueError: too many values to unpack (expected 3)
```
