### ISSUE TITLE
hdf_dump not working with SprintCacheDataset + seq_list_filter_file

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/returnn#1474]
When running `hdf_dump.py` (via ReturnnDumpHDFJob) I get the following exception below. Not sure if #1472 is really related, only realized that there is a recent issue regarding that. I think the issue stems from the fact that `self.num_seqs` is 0, since both `all_seq_tags` and `get_total_num_seqs` rely on that. From what I see the dataset in the main of `hdf_dump.py` (line 117) already has `_num_seqs` as 0, so maybe initialization before that went wrong. I am further looking into this, but maybe you already know what might cause this. 

```
EXCEPTION
Traceback (most recent call last):
  File "/u/hilmes/experiments/max_setup/work/i6_core/tools/git/CloneGitRepositoryJob.ex2FiDv9fD9H/output/repository/tools/hdf_dump.py", line 126, in <module>
    line: main(sys.argv)
    locals:
      main = <local> <function main at 0x7f7850de9ca0>
      sys = <local> <module 'sys' (built-in)>
      sys.argv = <local> ['/u/hilmes/experiments/max_setup/work/i6_core/tools/git/CloneGitRepositoryJob.ex2FiDv9fD9H/output/repository/tools/hdf_dump.py', 'dataset.config', '/var/tmp/sis_0tt09nsw.hdf'], _[0]: {len = 125}
  File "/u/hilmes/experiments/max_setup/work/i6_core/tools/git/CloneGitRepositoryJob.ex2FiDv9fD9H/output/repository/tools/hdf_dump.py", line 119, in main
    line: hdf_dump_from_dataset(dataset, hdf_dataset, args)
    locals:
      hdf_dump_from_dataset = <global> <function hdf_dump_from_dataset at 0x7f7850f4d790>
      dataset = <local> <SprintCacheDataset 'train' epoch=1>
      hdf_dataset = <local> <returnn.datasets.hdf.HDFDatasetWriter object at 0x7f7850df1280>
      args = <local> Namespace(config_file_or_dataset='dataset.config', end_seq=inf, epoch=1, hdf_filename='/var/tmp/sis_0tt09nsw.hdf', start_seq=0)
  File "/u/hilmes/experiments/max_setup/work/i6_core/tools/git/CloneGitRepositoryJob.ex2FiDv9fD9H/output/repository/tools/hdf_dump.py", line 35, in hdf_dump_from_dataset
    line: hdf_dataset.dump_from_dataset(
              dataset=dataset,
              epoch=parser_args.epoch,
              start_seq=parser_args.start_seq,
              end_seq=parser_args.end_seq,
              use_progress_bar=True,
          )
    locals:
      hdf_dataset = <local> <returnn.datasets.hdf.HDFDatasetWriter object at 0x7f7850df1280>
      hdf_dataset.dump_from_dataset = <local> <bound method HDFDatasetWriter.dump_from_dataset of <returnn.datasets.hdf.HDFDatasetWriter object at 0x7f7850df1280>>
      dataset = <local> <SprintCacheDataset 'train' epoch=1>
      epoch = <not found>
      parser_args = <local> Namespace(config_file_or_dataset='dataset.config', end_seq=inf, epoch=1, hdf_filename='/var/tmp/sis_0tt09nsw.hdf', start_seq=0)
      parser_args.epoch = <local> 1
      start_seq = <not found>
      parser_args.start_seq = <local> 0
      end_seq = <not found>
      parser_args.end_seq = <local> inf
      use_progress_bar = <not found>
  File "/work/asr4/hilmes/sis_work_folder/tmp/i6_core/tools/git/CloneGitRepositoryJob.ex2FiDv9fD9H/output/repository/returnn/datasets/hdf.py", line 1410, in HDFDatasetWriter.dump_from_dataset
    line: dataset.init_seq_order(epoch)
    locals:
      dataset = <local> <SprintCacheDataset 'train' epoch=1>
      dataset.init_seq_order = <local> <bound method SprintCacheDataset.init_seq_order of <SprintCacheDataset 'train' epoch=1>>
      epoch = <local> 1
  File "/work/asr4/hilmes/sis_work_folder/tmp/i6_core/tools/git/CloneGitRepositoryJob.ex2FiDv9fD9H/output/repository/returnn/datasets/sprint.py", line 1219, in SprintCacheDataset.init_seq_order
    line: seq_index = self.get_seq_order_for_epoch(epoch, num_seqs=len(self.seq_list_original), get_seq_len=get_seq_size)
    locals:
      seq_index = <not found>
      self = <local> <SprintCacheDataset 'train' epoch=1>
      self.get_seq_order_for_epoch = <local> <bound method Dataset.get_seq_order_for_epoch of <SprintCacheDataset 'train' epoch=1>>
      epoch = <local> 1
      num_seqs = <not found>
      len = <builtin> <built-in function len>
      self.seq_list_original = <local> ['TED-LIUM-realease2/AdamDavidson_2012S/9', 'TED-LIUM-realease2/AdamSadowsky_2010X/27', 'TED-LIUM-realease2/AdamSpencer_2013/31', 'TED-LIUM-realease2/AimeeMullins_2009U/18', 'TED-LIUM-realease2/AlGore_2008/59', 'TED-LIUM-realease2/AlSeckel_2004/37', 'TED-LIUM-realease2/AlVernacchio_2012/32', 'TED..., len = 500, _[0]: {len = 39}
      get_seq_len = <not found>
      get_seq_size = <local> <function SprintCacheDataset.init_seq_order.<locals>.get_seq_size at 0x7f7850d680d0>
  File "/work/asr4/hilmes/sis_work_folder/tmp/i6_core/tools/git/CloneGitRepositoryJob.ex2FiDv9fD9H/output/repository/returnn/datasets/basic.py", line 572, in Dataset.get_seq_order_for_epoch
    line: assert len(all_seq_tags) == num_seqs == self.get_total_num_seqs(), "%r vs %r vs %r" % (
              len(all_seq_tags),
              num_seqs,
              self.get_total_num_seqs(),
          )
    locals:
      len = <builtin> <built-in function len>
      all_seq_tags = <local> []
      num_seqs = <local> 500
      self = <local> <SprintCacheDataset 'train' epoch=1>
      self.get_total_num_seqs = <local> <bound method Dataset.get_total_num_seqs of <SprintCacheDataset 'train' epoch=1>>
AssertionError: 0 vs 500 vs 0
```

**Comment by albertz** [comment]
I pushed sth. Can you try?

**Comment by Atticus1806** [comment]
Sure :) 
So what I noticed, was that I think this was caused by returning an empty list in `get_seq_order_for_epoch` for `epoch=None` which is used for `self.seq_list_ordered` in `init_seq_order`. My proposal would have been: https://github.com/rwth-i6/returnn/blob/3e9f4bb892b5bd1aa13b59f80db497e0f5ec3f17/returnn/datasets/basic.py#L463

I am raising this just to make sure that setting `self.seq_list_ordered` to an empty list does not cause other unexpected harm. Can you have a look please?

**Comment by Atticus1806** [comment]
The fix worked though, thank you!

**Comment by albertz** [comment]
> this was caused by returning an empty list in `get_seq_order_for_epoch` for `epoch=None`

This is exactly intended. We don't want that any sequences are loaded when `epoch` is None.

The old behavior was that `epoch = None` was behaving just like `epoch = 1`, which caused loading and preparing the first epoch for many datasets. This is often not wanted:
- When the dataset is not used at all.
- When you are starting from an intermediate epoch.
- For things like PyTorch DataLoader with multi processing, or PyTorch DataLoader V2 which does deep copies of datasets, or MultiProcDataset, whenever it starts a new subprocess, usually done after every epoch, it would always first load some seqs from epoch 1, which is a huge overhead.

**Comment by Atticus1806** [comment]
That makes a lot of sense, thank you!
