### ISSUE TITLE
RF CausalAttention get_sequence_mask_broadcast bug

### ISSUE THREAD

**Issue by LucaG1** [rwth-i6/returnn#1477]
I think there is a small bug in the CausalSelfAttention class of returnn frontend:
In https://github.com/rwth-i6/returnn/blob/a043a50fed992c3eee2c999fa469f3b79b281d9a/returnn/frontend/attention.py#L224
it uses `hist_dim = Dim(None, name="kv-history")` as `kv_axis`. This leads to it getting called in https://github.com/rwth-i6/returnn/blob/a043a50fed992c3eee2c999fa469f3b79b281d9a/returnn/frontend/attention.py#L73 as the axis for softmax. This then fails to get a sequence mask for the axis.

This is the error log I get:
```
Traceback (most recent call last):
  File "/u/luca.gaudino/setups/2023-08-10--rf-librispeech/recipe/i6_experiments/users/gaudino/experiments/rf_conformer_att_2023/tedlium2/_moh_att_2023_12_12_import.py", line 281, in <module>
    test_import_search()
  File "/u/luca.gaudino/setups/2023-08-10--rf-librispeech/recipe/i6_experiments/users/gaudino/experiments/rf_conformer_att_2023/tedlium2/_moh_att_2023_12_12_import.py", line 239, in test_import_search
    seq_targets, seq_log_prob, out_spatial_dim, beam_dim = model_recog(
  File "/u/luca.gaudino/setups/2023-08-10--rf-librispeech/recipe/i6_experiments/users/gaudino/experiments/rf_conformer_att_2023/librispeech_960/model_recogs/model_recog.py", line 161, in model_recog
    trafo_lm_out = model.trafo_lm.loop_step(target, batch_dims_)
  File "/u/luca.gaudino/setups/2023-08-10--rf-librispeech/recipe/i6_experiments/users/gaudino/experiments/rf_conformer_att_2023/tedlium2/lm_import_2023_11_09.py", line 179, in loop_step
    x = self.layers(
  File "/u/luca.gaudino/setups/2023-08-10--rf-librispeech/returnn/returnn/frontend/container.py", line 120, in __call__
    inp = module(inp, **kwargs)
  File "/u/luca.gaudino/setups/2023-08-10--rf-librispeech/recipe/i6_experiments/users/gaudino/experiments/rf_conformer_att_2023/tedlium2/lm_import_2023_11_09.py", line 89, in __call__
    x_mhsa, new_state = self.self_att(x_mhsa_ln, axis=single_step_dim, state=self.self_att_state)
  File "/u/luca.gaudino/setups/2023-08-10--rf-librispeech/returnn/returnn/frontend/attention.py", line 225, in __call__
    output = self.attention(q, k, v, kv_axis=hist_dim)
  File "/u/luca.gaudino/setups/2023-08-10--rf-librispeech/returnn/returnn/frontend/attention.py", line 173, in attention
    att = dot_attention(
  File "/u/luca.gaudino/setups/2023-08-10--rf-librispeech/returnn/returnn/frontend/attention.py", line 73, in dot_attention
    att_weights = rf.softmax(energy, axis=axis)
  File "/u/luca.gaudino/setups/2023-08-10--rf-librispeech/returnn/returnn/frontend/math_.py", line 512, in softmax
    return a._raw_backend.softmax(a, axis=axis, use_mask=use_mask)
  File "/u/luca.gaudino/setups/2023-08-10--rf-librispeech/returnn/returnn/torch/frontend/_backend.py", line 505, in softmax
    mask = tensor.get_sequence_mask_broadcast(axis=axis)
  File "/u/luca.gaudino/setups/2023-08-10--rf-librispeech/returnn/returnn/tensor/_tensor_extra.py", line 2858, in get_sequence_mask_broadcast
    assert tag.dyn_size_ext and tag.dyn_size_ext.raw_tensor is not None
AssertionError
```

Replacing https://github.com/rwth-i6/returnn/blob/a043a50fed992c3eee2c999fa469f3b79b281d9a/returnn/frontend/attention.py#L73 with `att_weights = rf.softmax(energy, axis=axis, use_mask=False)` worked for me, but I'm not sure if this is correct in any case.

The entry point of the code I used to get this is pushed to i6_experiments under: users/gaudino/experiments/rf_conformer_att_2023/tedlium2/_moh_att_2023_12_12_import.py
My model implementation where I use CausalSelfAttention is this:
users/gaudino/experiments/rf_conformer_att_2023/tedlium2/lm_import_2023_11_09.py

**Comment by albertz** [comment]
I pushed a fix. Can you test?

Note that this code is still a bit experimental, was never used so far, only works with PyTorch currently, only works in step-by-step (`single_step_dim`) mode currently.

**Comment by LucaG1** [comment]
I works now, thank you. 

> Note that this code is still a bit experimental, was never used so far, only works with PyTorch currently, only works in step-by-step (`single_step_dim`) mode currently.
Ok I will keep this in mind.
