### ISSUE TITLE
PyTorch distributed training, hang in `all_reduce(_has_data ...`, after exception, Timed out waiting 1800000ms for send operation to complete

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#1484]
The log ends with this:
```
...
ep 272 train, step 339, ce 0.469, ctc_4 1.077, ctc_8 0.513, fer 0.077, mem_usage:cuda:0 7.5GB
ep 272 train, step 339, ce 0.454, ctc_4 0.817, ctc_8 0.549, fer 0.075, mem_usage:cuda:3 7.6GB
ep 272 train, step 339, ce 0.395, ctc_4 1.315, ctc_8 0.482, fer 0.069, mem_usage:cuda:2 7.5GB
ep 272 train, step 339, ce 0.407, ctc_4 0.954, ctc_8 0.571, fer 0.068, mem_usage:cuda:1 7.5GB
ep 272 train, step 340, ce 0.578, ctc_4 1.937, ctc_8 0.831, fer 0.099, mem_usage:cuda:0 7.5GB
ep 272 train, step 340, ce 0.478, ctc_4 0.958, ctc_8 0.542, fer 0.091, mem_usage:cuda:1 7.5GB
ep 272 train, step 340, ce 0.582, ctc_4 0.929, ctc_8 0.768, fer 0.124, mem_usage:cuda:2 7.5GB
ep 272 train, step 340, ce 0.254, ctc_4 0.614, ctc_8 0.294, fer 0.043, mem_usage:cuda:3 7.6GB
ep 272 train, step 341, ce 0.372, ctc_4 0.876, ctc_8 0.507, fer 0.073, mem_usage:cuda:0 7.5GB
ep 272 train, step 341, ce 0.418, ctc_4 0.800, ctc_8 0.485, fer 0.068, mem_usage:cuda:3 7.6GB
ep 272 train, step 341, ce 0.367, ctc_4 0.581, ctc_8 0.551, fer 0.064, mem_usage:cuda:2 7.5GB
Unhandled exception <class 'RuntimeError'> in thread <_MainThread(MainThread, started 139628628058112)>, proc 2834.

Thread <Thread(QueueFeederThread, started daemon 139622650693184)>:
Unhandled exception <class 'RuntimeError'> in thread <_MainThread(MainThread, started 139655026450432)>, proc 2837.

Thread <Thread(QueueFeederThread, started daemon 139649061164608)>:
Unhandled exception <class 'RuntimeError'> in thread <_MainThread(MainThread, started 140024853565440)>, proc 2836.

Thread <Thread(QueueFeederThread, started daemon 140018567861824)>:
  File "/work/tools/users/zeyer/linuxbrew/opt/python@3.11/lib/python3.11/threading.py", line 320, in Condition.wait
    line: waiter.acquire()
    locals:
      waiter = <local> <locked _thread.lock object at 0x7efc8c17e3c0>
      waiter.acquire = <local> <built-in method acquire of _thread.lock object at 0x7efc8c17e3c0>
  File "/work/tools/users/zeyer/linuxbrew/opt/python@3.11/lib/python3.11/multiprocessing/queues.py", line 231, in Queue._feed
    line: nwait()
...
      _has_data = <local> tensor[1] i8 [1]
      work = <local> <torch.distributed.distributed_c10d.Work object at 0x7f58c6614470>
      op = <not found>
      work.wait = <local> <bound method PyCapsule.wait of <torch.distributed.distributed_c10d.Work object at 0x7f58c6614470>>
      torch.distributed.ReduceOp = <global> <class 'torch.distributed.distributed_c10d.ReduceOp'>
RuntimeError: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:133] Timed out waiting 1800000ms for send operation to complete
      torch.distributed.ReduceOp.MIN = <global> <RedOpType.MIN: 3>
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 47, in send
    line: return func(*args, **kwargs)
    locals:
      func = <local> <function all_reduce at 0x7efd26f1eca0>
      args = <local> (tensor[1] i8 [1],)
      kwargs = <local> {'op': <RedOpType.MIN: 3>}
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 2055, in all_reduce
    line: work.wait()
    locals:
      work = <local> <torch.distributed.distributed_c10d.Work object at 0x7efc8c1aeb30>
      work.wait = <local> <bound method PyCapsule.wait of <torch.distributed.distributed_c10d.Work object at 0x7efc8c1aeb30>>
RuntimeError: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 1800000ms for recv operation to complete
EXCEPTION
Traceback (most recent call last):
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/rnn.py", line 11, in <module>
...
RuntimeError: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 1800000ms for recv operation to complete
...
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 2055, in all_reduce
    line: work.wait()
    locals:
      work = <local> <torch.distributed.distributed_c10d.Work object at 0x7fba6621f2f0>
      work.wait = <local> <bound method PyCapsule.wait of <torch.distributed.distributed_c10d.Work object at 0x7fba6621f2f0>>
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [10.6.9.61]:6309
[2024-01-01 10:55:31,817] INFO: Run time: 0:37:40 CPU: 0.40% RSS: 4.71GB VMS: 44.96GB
```
The stack traces are a bit scrambled because they all occurred at the same time. I count 4 times `RuntimeError`, and this uses 4 worker procs. So this indicates that all the workers have crashed? But then, why does it not stop, and hang?

**Comment by albertz** [comment]
On the host:
```
$ nvidia-smi
Unable to determine the device handle for GPU0000:03:00.0: Unknown Error
```
So maybe this is a hardware issue?

The running procs:
```
$ ps a --forest -u $(whoami) -o pid,comm 
    PID COMMAND
   6294 sshd
   6295  \_ zsh
   6365      \_ gdb
   6395      \_ ps
   2780 slurm_script
   2791  \_ python3.11
   2816      \_ python3.11
   2834          \_ python3.11 <defunct>
   2835          \_ python3.11
   2970          |   \_ python3.11
   2836          \_ python3.11 <defunct>
   2971          |   \_ python3.11 <defunct>
   2837          \_ python3.11 <defunct>
   2964              \_ python3.11 <defunct>
   6283 systemd
   6284  \_ (sd-pam)
   1521 agetty
```
The root proc idles like this:
```
Process 2816: /work/tools/users/zeyer/py-envs/py3.11-torch2.1/bin/python3.11 -mtorch.distributed.run --standalone --nnodes=1 --nproc-per-node=4 /u/zeyer/
setups/combined/2021-05-31/tools/returnn/rnn.py /u/zeyer/setups/combined/2021-05-31/work/i6_core/returnn/training/ReturnnTrainingJob.ekBKZvE5HeTb/output/
returnn.config               
Python v3.11.2 (/work/tools/users/zeyer/linuxbrew/Cellar/python@3.11/3.11.2_1/bin/python3.11)
                                      
Thread 2816 (idle): "MainThread"                                                                                                                         
    _invoke_run (torch/distributed/elastic/agent/server/api.py:877)
    run (torch/distributed/elastic/agent/server/api.py:736)
    wrapper (torch/distributed/elastic/metrics/api.py:124)
    launch_agent (torch/distributed/launcher/api.py:255)
    __call__ (torch/distributed/launcher/api.py:134)
    run (torch/distributed/run.py:800)
    main (torch/distributed/run.py:806)
    wrapper (torch/distributed/elastic/multiprocessing/errors/__init__.py:346)
    <module> (torch/distributed/run.py:810)
    _run_code (<frozen runpy>:88)
    _run_module_as_main (<frozen runpy>:198)
Thread 2833 (idle): "RendezvousKeepAliveTimer_0"
    wait (threading.py:324)                                                 
    wait (threading.py:622)                                                 
    _run (torch/distributed/elastic/rendezvous/utils.py:272)
    run (threading.py:975)
    _bootstrap_inner (threading.py:1038)
    _bootstrap (threading.py:995)
```
And I cannot attach to 2835:
```
$ py-spy dump -p 2835
Error: Failed to find a python interpreter in the .data section
```
And GDB hangs at `Attaching to process 2835`.

**Comment by albertz** [comment]
> And GDB hangs at `Attaching to process 2835`.

I assume the only explanation that this hangs is if the proc itself hangs in some syscall, probably related to the GPU, which is in a faulty state here?

**Comment by albertz** [comment]
I'm not really sure if there is anything we can do about this. Maybe another external watch proc could help, but maybe not. I'm closing this for now.

(Or @dthulke , maybe some idea?)

**Comment by albertz** [comment]
Hm, same again.
```
RETURNN starting up, version 1.20231230.164342+git.f353135e, date/time 2024-01-01-12-01-50 (UTC+0000), pid 6472, cwd /work/asr4/zeyer/setups-data/combine
d/2021-05-31/work/i6_core/returnn/training/ReturnnTrainingJob.ekBKZvE5HeTb/work, Python /work/tools/users/zeyer/py-envs/py3.11-torch2.1/bin/python3.11
RETURNN command line options: ['/u/zeyer/setups/combined/2021-05-31/work/i6_core/returnn/training/ReturnnTrainingJob.ekBKZvE5HeTb/output/returnn.config']
Hostname: cn-251
...
ep 272 train, step 176, ce 0.424, ctc_4 0.958, ctc_8 0.577, fer 0.088, mem_usage:cuda:2 7.3GB
ep 272 train, step 177, ce 0.506, ctc_4 1.136, ctc_8 1.017, fer 0.106, mem_usage:cuda:2 7.3GB
ep 272 train, step 177, ce 0.451, ctc_4 0.860, ctc_8 0.509, fer 0.081, mem_usage:cuda:3 7.4GB
ep 272 train, step 177, ce 0.590, ctc_4 1.281, ctc_8 0.823, fer 0.118, mem_usage:cuda:1 7.4GB
ep 272 train, step 177, ce 0.358, ctc_4 0.839, ctc_8 0.442, fer 0.062, mem_usage:cuda:0 7.4GB
ep 272 train, step 178, ce 0.350, ctc_4 0.551, ctc_8 0.398, fer 0.055, mem_usage:cuda:0 7.4GB
ep 272 train, step 178, ce 0.544, ctc_4 0.915, ctc_8 0.654, fer 0.094, mem_usage:cuda:2 7.3GB
ep 272 train, step 178, ce 0.271, ctc_4 0.564, ctc_8 0.245, fer 0.039, mem_usage:cuda:3 7.4GB
Unhandled exception <class 'RuntimeError'> in thread <_MainThread(MainThread, started 140332624121856)>, proc 6474.Unhandled exception <class 'RuntimeError'> in thread <_MainThread(MainThread, started 139889804689408)>, proc 6472.



Thread <Thread(QueueFeederThread, started daemon 139883829999168)>:
Thread <Thread(QueueFeederThread, started daemon 140326728570432)>:
Unhandled exception <class 'RuntimeError'> in thread <_MainThread(MainThread, started 139718006165504)>, proc 6475.
...
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/torch/engine.py", line 239, in Engine.train
    line: self.train_epoch()
    locals:
      self = <local> <returnn.torch.engine.Engine object at 0x7f11ccba8810>
      self.train_epoch = <local> <bound method Engine.train_epoch of <returnn.torch.engine.Engine object at 0x7f11ccba8810>>
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/torch/engine.py", line 349, in Engine.train_epoch
    line: torch.distributed.all_reduce(_has_data, op=torch.distributed.ReduceOp.MIN)
    locals:
      torch = <global> <module 'torch' from '/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/__init__.py'>
      torch.distributed = <global> <module 'torch.distributed' from '/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/d
istributed/__init__.py'> 
      torch.distributed.all_reduce = <global> <function all_reduce at 0x7f11f651ed40>
      _has_data = <local> tensor[1] i8 [1]
      op = <not found>
      torch.distributed.ReduceOp = <global> <class 'torch.distributed.distributed_c10d.ReduceOp'>
      torch.distributed.ReduceOp.MIN = <global> <RedOpType.MIN: 3>
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 47, in send
    line: return func(*args, **kwargs)
    locals:
      func = <local> <function all_reduce at 0x7f11f651eca0>
      args = <local> (tensor[1] i8 [1],)
      kwargs = <local> {'op': <RedOpType.MIN: 3>}
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 2055, in all_reduce
    line: work.wait()
    locals:
      work = <local> <torch.distributed.distributed_c10d.Work object at 0x7f11404c1230>
      work.wait = <local> <bound method PyCapsule.wait of <torch.distributed.distributed_c10d.Work object at 0x7f11404c1230>>
RuntimeError: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 1800000ms for recv operation to complete
EXCEPTION
...
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/torch/engine.py", line 349, in Engine.train_epoch
    line: torch.distributed.all_reduce(_has_data, op=torch.distributed.ReduceOp.MIN)
    locals:
      torch = <global> <module 'torch' from '/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/__init__.py'>
      torch.distributed = <global> <module 'torch.distributed' from '/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/__init__.py'>
      torch.distributed.all_reduce = <global> <function all_reduce at 0x7fa110716d40>
      _has_data = <local> tensor[1] i8 [1]
      op = <not found>
      torch.distributed.ReduceOp = <global> <class 'torch.distributed.distributed_c10d.ReduceOp'>
      torch.distributed.ReduceOp.MIN = <global> <RedOpType.MIN: 3>
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 47, in send
    line: return func(*args, **kwargs)
    locals:
      func = <local> <function all_reduce at 0x7fa110716ca0>
      args = <local> (tensor[1] i8 [1],)
      kwargs = <local> {'op': <RedOpType.MIN: 3>}
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 2055, in all_reduce
    line: work.wait()
    locals:
      work = <local> <torch.distributed.distributed_c10d.Work object at 0x7fa07a11ec30>
      work.wait = <local> <bound method PyCapsule.wait of <torch.distributed.distributed_c10d.Work object at 0x7fa07a11ec30>>
RuntimeError: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:133] Timed out waiting 1800000ms for send operation to complete
...
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/torch/engine.py", line 349, in Engine.train_epoch
    line: torch.distributed.all_reduce(_has_data, op=torch.distributed.ReduceOp.MIN)
    locals:
      torch = <global> <module 'torch' from '/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/__init__.py'>
      torch.distributed = <global> <module 'torch.distributed' from '/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/d
istributed/__init__.py'>
      torch.distributed.all_reduce = <global> <function all_reduce at 0x7f39f651ad40>
      _has_data = <local> tensor[1] i8 [1]
      op = <not found>
      torch.distributed.ReduceOp = <global> <class 'torch.distributed.distributed_c10d.ReduceOp'>
      torch.distributed.ReduceOp.MIN = <global> <RedOpType.MIN: 3>
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 47, in send
    line: return func(*args, **kwargs)
    locals:
      func = <local> <function all_reduce at 0x7f39f651aca0>
      args = <local> (tensor[1] i8 [1],)
      kwargs = <local> {'op': <RedOpType.MIN: 3>}
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 2055, in all_reduce
    line: work.wait()
    locals:
      work = <local> <torch.distributed.distributed_c10d.Work object at 0x7f395414ea70>
      work.wait = <local> <bound method PyCapsule.wait of <torch.distributed.distributed_c10d.Work object at 0x7f395414ea70>>
RuntimeError: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 1800000ms for recv operation to complete
```
In this case, I only see 3 exceptions, from the 4 workers.
```
   6420 slurm_script
   6429  \_ python3.11
   6454      \_ python3.11
   6472          \_ python3.11 <defunct>
   6601          |   \_ python3.11 <defunct>
   6473          \_ python3.11
   6637          |   \_ python3.11
   6639          |   \_ watch memory
   6727          |   \_ MPD seq order
   6730          |   \_ MPD worker
   6733          |   \_ MPD worker
   6735          |   \_ MPD worker
   6738          |   \_ MPD worker
   7383          |   \_ python3.11
   7634          |   \_ MPD seq order
   7635          |   \_ MPD worker
   7636          |   \_ MPD worker
   7637          |   \_ MPD worker
   7638          |   \_ MPD worker
   8181          |   \_ MPD seq order
   8182          |   \_ MPD worker
   8183          |   \_ MPD worker
   8184          |   \_ MPD worker
   8185          |   \_ MPD worker
   8754          |   \_ TDL worker 0
   6474          \_ python3.11 <defunct>
   6475          \_ python3.11 <defunct>
```
And that single running proc:
```
% py-spy dump -p 6473
Process 6473: /work/tools/users/zeyer/py-envs/py3.11-torch2.1/bin/python3.11 -u /u/zeyer/setups/combined/2021-05-31/tools/returnn/rnn.py /u/zeyer/setups/combined/2021-05-31/work/i6_core/returnn/training/ReturnnTrainingJob.ekBKZvE5HeTb/output/returnn.config
Python v3.11.2 (/work/tools/users/zeyer/linuxbrew/Cellar/python@3.11/3.11.2_1/bin/python3.11)

Thread 6473 (active): "MainThread"
    range_over_dim (returnn/returnn/torch/frontend/_backend.py:1204)
    range_over_dim (returnn/returnn/frontend/dims.py:35)
    _make_indices (returnn/returnn/frontend/attention.py:765)
    __call__ (returnn/returnn/frontend/attention.py:712)
    __call__ (returnn/returnn/frontend/attention.py:355)
    __call__ (returnn/returnn/frontend/encoder/conformer.py:263)
    <lambda> (i6_experiments/users/zeyer/returnn/models/rf_layerdrop.py:27)
    cond (returnn/returnn/frontend/cond.py:35)
    _layer_drop_call (i6_experiments/users/zeyer/returnn/models/rf_layerdrop.py:25)
    cond (returnn/returnn/frontend/cond.py:27)
    __call__ (i6_experiments/users/zeyer/returnn/models/rf_layerdrop.py:37)
    __call__ (returnn/returnn/frontend/encoder/conformer.py:372)
    encode (i6_experiments/users/zeyer/experiments/exp2023_04_25_rf/aed.py:439)
    from_scratch_training (i6_experiments/users/zeyer/experiments/exp2023_04_25_rf/aed.py:507)
    _returnn_v2_train_step (i6_experiments/users/zeyer/experiments/exp2023_04_25_rf/train.py:188)
    _run_step (returnn/returnn/torch/engine.py:611)
    train_epoch (returnn/returnn/torch/engine.py:360)
    train (returnn/returnn/torch/engine.py:239)
    execute_main_task (returnn/returnn/__main__.py:465)
    main (returnn/returnn/__main__.py:659)
    <module> (returnn/rnn.py:11)
Thread 8856 (idle): "QueueFeederThread"
    wait (threading.py:320)
    _feed (multiprocessing/queues.py:231)
    run (threading.py:975)
    _bootstrap_inner (threading.py:1038)
    _bootstrap (threading.py:995)
Thread 9214 (idle)
Thread 9215 (idle)
Thread 9216 (idle)
Thread 9217 (idle)
```
So in this case, I can attach to it. GDB shows this stacktrace:
```
(gdb) bt                                                                                                                                                 
#0  0x00007f87c16233c7 in sched_yield () at ../sysdeps/unix/syscall-template.S:120                                                     
#1  0x00007f875927b68b in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#2  0x00007f875953dc5e in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#3  0x00007f875953df2c in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#4  0x00007f875936c6c7 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#5  0x00007f875923c6f3 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#6  0x00007f875923ce1d in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#7  0x00007f875923f71a in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#8  0x00007f875942236e in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#9  0x00007f875b61498c in ?? ()
   from /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/../../nvidia/cuda_runtime/lib/libcudart.so.12
#10 0x00007f875b66bf5e in cudaLaunchKernel ()
   from /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/../../nvidia/cuda_runtime/lib/libcudart.so.12
#11 0x00007f871781dda8 in void (anonymous namespace)::gpu_kernel_with_index<__nv_hdl_wrapper_t<false, false, false, __nv_dl_tag<at::Tensor& (*)(c10::Scal
ar const&, c10::Scalar const&, c10::Scalar const&, at::Tensor&), &at::native::arange_cuda_out, 3u>, int (long), long, long> >(at::Tensor&, __nv_hdl_wrapp
er_t<false, false, false, __nv_dl_tag<at::Tensor& (*)(c10::Scalar const&, c10::Scalar const&, c10::Scalar const&, at::Tensor&), &at::native::arange_cuda_
out, 3u>, int (long), long, long>) () from /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so
#12 0x00007f871780da30 in at::native::arange_cuda_out(c10::Scalar const&, c10::Scalar const&, c10::Scalar const&, at::Tensor&)::{lambda()#1}::operator()(
) const::{lambda()#3}::operator()() const ()
   from /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so
#13 0x00007f871780fd7e in at::native::arange_cuda_out(c10::Scalar const&, c10::Scalar const&, c10::Scalar const&, at::Tensor&)::{lambda()#1}::operator()(
) const () from /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so
#14 0x00007f87178125e6 in at::native::arange_cuda_out(c10::Scalar const&, c10::Scalar const&, c10::Scalar const&, at::Tensor&) ()
   from /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so
#15 0x00007f87184b7f4f in at::(anonymous namespace)::(anonymous namespace)::wrapper_CUDA_start_out_arange_out(c10::Scalar const&, c10::Scalar const&, c10
::Scalar const&, at::Tensor&) () from /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so
#16 0x00007f87437a5dae in at::_ops::arange_start_out::call(c10::Scalar const&, c10::Scalar const&, c10::Scalar const&, at::Tensor&) ()
   from /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so
#17 0x00007f8742ddf452 in at::native::arange(c10::Scalar const&, c10::Scalar const&, c10::Scalar const&, c10::optional<c10::ScalarType>, c10::optional<c1
0::Layout>, c10::optional<c10::Device>, c10::optional<bool>) ()
   from /work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so
...
```
The host also again shows an error for `nvidia-smi`:
```
$ nvidia-smi
Unable to determine the device handle for GPU0000:03:00.0: Unknown Error
```
And `dmesg` also shows errors:
```
[Jan 1 10:54] nfs: Deprecated parameter 'intr'
[Jan 1 11:11] nfs: Deprecated parameter 'intr'
[Jan 1 11:32] nfs: Deprecated parameter 'intr'
[Jan 1 11:51] nfs: Deprecated parameter 'intr'
[Jan 1 12:05] pcieport 0000:00:03.0: AER: Uncorrected (Fatal) error received: 0000:00:03.0
[  +0.000011] pcieport 0000:00:03.0: PCIe Bus Error: severity=Uncorrected (Fatal), type=Transaction Layer, (Receiver ID)
[  +0.000051] pcieport 0000:00:03.0:   device [8086:6f08] error status/mask=00000020/00000000
[  +0.000032] pcieport 0000:00:03.0:    [ 5] SDES                   (First)
[  +0.000033] nvidia 0000:03:00.0: AER: can't recover (no error_detected callback)
[  +0.000003] snd_hda_intel 0000:03:00.1: AER: can't recover (no error_detected callback)
[  +0.818932] NVRM: GPU at PCI:0000:03:00: GPU-a2b1cd66-a68a-16cb-3c95-e14580663cae
[  +0.000012] NVRM: Xid (PCI:0000:03:00): 79, pid='<unknown>', name=<unknown>, GPU has fallen off the bus.
[  +0.000004] NVRM: GPU 0000:03:00.0: GPU has fallen off the bus.
[  +0.000007] NVRM: A GPU crash dump has been created. If possible, please run
              NVRM: nvidia-bug-report.sh as root to collect this data before
              NVRM: the NVIDIA kernel module is unloaded.
[  +0.223940] pcieport 0000:00:03.0: AER: Root Port link has been reset (0)
[  +0.000026] pcieport 0000:00:03.0: AER: device recovery failed
[Jan 1 12:15] perf: interrupt took too long (2515 > 2500), lowering kernel.perf_event_max_sample_rate to 79500
[Jan 1 12:22] perf: interrupt took too long (3152 > 3143), lowering kernel.perf_event_max_sample_rate to 63250
[Jan 1 12:33] perf: interrupt took too long (3941 > 3940), lowering kernel.perf_event_max_sample_rate to 50750
```
So I guess again a problem with the GPU, and not much we can do about it.
