### ISSUE TITLE
MultiProcDataset inside PyTorch DataLoader with num_workers>0, multiple issues

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#1495]
When you also set `multiprocessing_context="spawn"` in the `DataLoader` (which we do now by default, via d12211292a150f4fe7b1fe718692ed82f9d698a4, to fix #1494), then this triggers multiple issues:

In a real setup, I now get this:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/work/tools/users/zeyer/linuxbrew/opt/python@3.11/lib/python3.11/multiprocessing/spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/tools/users/zeyer/linuxbrew/opt/python@3.11/lib/python3.11/multiprocessing/spawn.py", line 130, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/utils/data/datapipes/datapipe.py", line 359, in __setstate__
    self._datapipe = pickle.loads(value)
                     ^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '__returnn_config__'
```

I guess this error is clear. The RETURNN config is not properly serialized. (I thought we had some logic for that? Maybe it's not correctly used here.)

But even trying simpler variants, e.g. our test case `test_MultiProcDataset_HDFDataset`, fail (when adding `num_workers=1, multiprocessing_context="spawn",` to the `DataLoader` args). Then you get:
```
AssertionError: daemonic processes are not allowed to have children
```

The problem is that PyTorch sets all worker processes as daemonic. This is the relevant PyTorch code (in `_MultiProcessingDataLoaderIter`):
```python
            w = multiprocessing_context.Process(
                target=_utils.worker._worker_loop,
                args=(self._dataset_kind, self._dataset, index_queue,
                      self._worker_result_queue, self._workers_done_event,
                      self._auto_collation, self._collate_fn, self._drop_last,
                      self._base_seed, self._worker_init_fn, i, self._num_workers,
                      self._persistent_workers, self._shared_seed))
            w.daemon = True
            ...
            w.start()
```

This somehow was unnoticed before when I did not set `multiprocessing_context="spawn"`. In that case, it would use the default, which is the fork method. This is strange: Why does this problem not occur when I use the fork method? It's still a proper subprocess, so shouldn't I get the same error ("daemonic processes are not allowed to have children")?

Maybe because the `MultiProcDataset` instance is already created and initialized, and thus it already has created subprocesses, and in a fork, it will not actually copy (serialize + deserialize) `MultiProcDataset` but rather just use the same instance?

**Comment by albertz** [comment]
> This is strange: Why does this problem not occur when I use the fork method? It's still a proper subprocess, so shouldn't I get the same error ("daemonic processes are not allowed to have children")?
> 
> Maybe because the `MultiProcDataset` instance is already created and initialized, and thus it already has created subprocesses, and in a fork, it will not actually copy (serialize + deserialize) `MultiProcDataset` but rather just use the same instance?

I just verified this: Yes, this is exactly what happens. And then, `MultiProcDataset._collect_single_seq` here:
```python
    def _collect_single_seq(self, seq_idx: int) -> Optional[DatasetSeq]:
        if seq_idx >= self._num_seqs:
            return None
        worker_idx = seq_idx % self.num_workers
        worker = self._worker_parent_conns[worker_idx]
        worker.send(("get_data_seq", {"seq_idx": seq_idx // self.num_workers}))
        msg, data = worker.recv()
        assert msg == "data_seq"
        if data is None:
            return None
        assert isinstance(data, DatasetSeq)
        data.seq_idx = seq_idx
        return data
```
will use existing `Connection` objects, which seems to work fine even after the fork.

But this code here is potentially very dangerous, as it will break when there are multiple workers, all spamming into the same connection. Also, this whole code here only works because `MultiProcDataset` was already initialized and the sub procs were started, which is not necessarily true.

So we just had some luck that it was working fine so far.

In any case, using fork is not a good idea, because of #1494, and all the other potential problems which come with fork. So 32328cd3d6cb7e47c628ca9188f909fca5257943 should be undone, i.e. we should use sth different than the default (fork). But the question is, how to fix the described issue here ("daemonic processes are not allowed to have children")?

**Comment by albertz** [comment]
So, this daemonic sub processes problem should be fixed now via the introduced `NonDaemonicSpawnContext`, which we use by default now.

However, the other issue with the config is not yet fixed.

**Comment by albertz** [comment]
> However, the other issue with the config is not yet fixed.

We had mostly the same problem also with `MultiProcDataset`, see #1384.
