### ISSUE TITLE
Hang at exit in TDL worker in multiprocessing `_run_finalizers`, deadlock in `_wait_for_tstate_lock`?

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#1499]
```
ep 62 train, step 93, ctc_4 3.291, ctc_8 2.878, ce 3.709, fer 0.607, num_seqs 24, max_size:time 263208, max_size:out-spatial 55, mem_usage:cuda 18.8GB, 0.826 sec/step
ep 62 train, step 94, ctc_4 3.585, ctc_8 3.239, ce 4.010, fer 0.648, num_seqs 24, max_size:time 266024, max_size:out-spatial 58, mem_usage:cuda 18.8GB, 0.708 sec/step
ep 62 train, step 95, ctc_4 3.945, ctc_8 3.631, ce 4.139, fer 0.669, num_seqs 23, max_size:time 268312, max_size:out-spatial 65, mem_usage:cuda 18.8GB, 0.868 sec/step
ep 62 train, step 96, ctc_4 3.598, ctc_8 3.304, ce 3.921, fer 0.619, num_seqs 23, max_size:time 270160, max_size:out-spatial 62, mem_usage:cuda 18.8GB, 0.734 sec/step
OutOfMemoryError: CUDA out of memory. Tried to allocate 264.00 MiB. GPU 0 has a total capacty of 22.03 GiB of which 246.88 MiB is free. Including non-PyTorch memory, this process has 21.79 GiB memory in use. Of the allocated memory 19.18 GiB is allocated by PyTorch, and 1.26 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Unhandled exception <class 'torch.cuda.OutOfMemoryError'> in thread <_MainThread(MainThread, started 140665210197824)>, proc 2882484.

...
EXCEPTION
Traceback (most recent call last):
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/rnn.py", line 11, in <module> 
    line: main()
    locals:
      main = <local> <function main at 0x7feec0d7f740>
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/__main__.py", line 682, in main
    line: execute_main_task()
    locals:
      execute_main_task = <global> <function execute_main_task at 0x7feec0d7f600>
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/__main__.py", line 488, in execute_main_task
    line: engine.train()
    locals:
      engine = <global> <returnn.torch.engine.Engine object at 0x7fed9e1e0c90>
      engine.train = <global> <bound method Engine.train of <returnn.torch.engine.Engine object at 0x7fed9e1e0c90>>
...
  File "/u/zeyer/setups/combined/2021-05-31/recipe/i6_experiments/users/zeyer/experiments/exp2023_04_25_rf/train.py", line 190, in _returnn_v2_train_step
    line: train_def(
              model=model,
              data=data,
              data_spatial_dim=data_spatial_dim,
              targets=targets,
              targets_spatial_dim=targets_spatial_dim,
          )
    locals:
      train_def = <local> <function from_scratch_training at 0x7feec09f8ea0>
      model = <local> <Model>
      data = <local> Tensor{'data', [B?,T|'time'[B?],F|F'audio'(1)]}
      data_spatial_dim = <local> Dim{'time'[B?]}
      targets = <local> Tensor{'classes', [B?,T|'out-spatial'[B?]], dtype='int32', sparse_dim=Dim{'vocab'(10025)}}
      targets_spatial_dim = <local> Dim{'out-spatial'[B?]}
  File "/u/zeyer/setups/combined/2021-05-31/recipe/i6_experiments/users/zeyer/experiments/exp2023_04_25_rf/conformer_import_moh_att_2023_06_30.py", line 1014, i
n from_scratch_training
    line: logits_packed, pack_dim = rf.pack_padded(logits, dims=batch_dims + [targets_spatial_dim], enforce_sorted=False)
...

OutOfMemoryError: CUDA out of memory. Tried to allocate 264.00 MiB. GPU 0 has a total capacty of 22.03 GiB of which 246.88 MiB is free. Including non-PyTorch memory, this process has 21.79 GiB memory in use. Of the allocated memory 19.18 GiB is allocated by PyTorch, and 1.26 GiB is reserved by PyTorch but unallocated. 
If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Module call stack:
(No module call frames.)
<OggZipDataset 'train' epoch=59>, epoch 59. No filter for this epoch.
<OggZipDataset 'train' epoch=60>, epoch 60. No filter for this epoch.
<OggZipDataset 'train' epoch=61>, epoch 61. No filter for this epoch.
<OggZipDataset 'train' epoch=62>, epoch 62. No filter for this epoch.
MEMORY: proc <unknown-dead>(2882959) exited, old: rss=582.2MB pss=463.2MB uss=414.3MB shared=167.8MB
MEMORY: proc <unknown-dead>(2883092) exited, old: rss=645.3MB pss=514.1MB uss=477.6MB shared=167.7MB
MEMORY: proc <unknown-dead>(2883140) exited, old: rss=735.2MB pss=709.7MB uss=709.0MB shared=26.2MB
MEMORY: proc <unknown-dead>(2883154) exited, old: rss=737.1MB pss=711.7MB uss=711.0MB shared=26.1MB
MEMORY: proc <unknown-dead>(2883169) exited, old: rss=736.5MB pss=710.8MB uss=710.0MB shared=26.5MB
MEMORY: proc <unknown-dead>(2883184) exited, old: rss=735.2MB pss=709.6MB uss=708.8MB shared=26.4MB
MEMORY: proc <unknown-dead>(2883008) exited, old: rss=108.6MB pss=83.0MB uss=82.3MB shared=26.3MB
MEMORY: proc <unknown-dead>(2883022) exited, old: rss=108.7MB pss=83.1MB uss=82.3MB shared=26.4MB
MEMORY: proc <unknown-dead>(2883037) exited, old: rss=108.6MB pss=83.0MB uss=82.3MB shared=26.4MB
MEMORY: proc <unknown-dead>(2883052) exited, old: rss=109.3MB pss=83.7MB uss=82.9MB shared=26.4MB
MEMORY: proc <unknown-dead>(2882782) exited, old: rss=0.9GB pss=0.8GB uss=0.8GB shared=26.5MB
MEMORY: proc <unknown-dead>(2882796) exited, old: rss=0.9GB pss=805.3MB uss=784.6MB shared=101.4MB
MEMORY: proc <unknown-dead>(2882811) exited, old: rss=0.9GB pss=798.1MB uss=777.0MB shared=102.2MB
MEMORY: proc <unknown-dead>(2882826) exited, old: rss=0.9GB pss=808.6MB uss=787.6MB shared=102.0MB
MEMORY: total (main 2882484, 2024-01-19, 17:42:08, 17 procs): pss=8.5GB uss=7.7GB
[2024-01-19 17:42:08,586] INFO: Run time: 6:47:50 CPU: 0.40% RSS: 8.82GB VMS: 83.05GB
```

With py-spy on the main proc:
```
zeyer@cn-504 ~ % py-spy dump -p 2882484                       
Process 2882484: /work/tools/users/zeyer/py-envs/py3.11-torch2.1/bin/python3.11 /u/zeyer/setups/combined/2021-05-31/tools/returnn/rnn.py /u/zeyer/setups/combine
d/2021-05-31/work/i6_core/returnn/training/ReturnnTrainingJob.XBD0ELoPJvFX/output/returnn.config
Python v3.11.2 (/work/tools/users/zeyer/linuxbrew/Cellar/python@3.11/3.11.2_1/bin/python3.11)
                                                                                
Thread 2882484 (idle): "MainThread"
    __call__ (returnn/returnn/util/multi_proc_non_daemonic_spawn.py:166)
Thread 2882749 (idle): "QueueFeederThread"
    wait (threading.py:320)          
    _feed (multiprocessing/queues.py:231)
    run (threading.py:975)                                                                                                                                      
    _bootstrap_inner (threading.py:1038)                                        
    _bootstrap (threading.py:995)                                               
Thread 2882889 (idle)                                                           
Thread 2882975 (idle): "QueueFeederThread"                    
    wait (threading.py:320)                                                     
    _feed (multiprocessing/queues.py:231)                     
    run (threading.py:975)
    _bootstrap_inner (threading.py:1038)
    _bootstrap (threading.py:995)
Thread 2883107 (idle): "QueueFeederThread"
    wait (threading.py:320)
    _feed (multiprocessing/queues.py:231)
    run (threading.py:975)
    _bootstrap_inner (threading.py:1038)
    _bootstrap (threading.py:995)
```
So it waits for some subproc after it got the exception, in the atexit handler. It's not totally clear which subproc though. In the `ps a --forest -u $(whoami) -o pid,comm`, I was seeing that still 3 * 4 MPD workers were alive, and then a single TDL worker. That TDL worker did not had any subprocs.

That TDL worker subproc in py-spy:
```
zeyer@cn-504 ~ % py-spy dump -p 2882734                        
Process 2882734: /work/tools/users/zeyer/py-envs/py3.11-torch2.1/bin/python3.11 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=8, pipe_handle=90) --multiprocessing-fork
Python v3.11.2 (/work/tools/users/zeyer/linuxbrew/Cellar/python@3.11/3.11.2_1/bin/python3.11)

Thread 2882734 (idle): "MainThread"
    _wait_for_tstate_lock (threading.py:1132)
    join (threading.py:1112)
    _finalize_join (multiprocessing/queues.py:199)
    __call__ (multiprocessing/util.py:224)
    _run_finalizers (multiprocessing/util.py:300)
    _exit_function (multiprocessing/util.py:360)
    _bootstrap (multiprocessing/process.py:317)
    _main (multiprocessing/spawn.py:133)
    spawn_main (multiprocessing/spawn.py:120)
    <module> (<string>:1)
Thread 2882887 (idle): "QueueFeederThread"
    _send (multiprocessing/connection.py:367)
    _send_bytes (multiprocessing/connection.py:404)
    send_bytes (multiprocessing/connection.py:199)
    _feed (multiprocessing/queues.py:250)
    run (threading.py:975)
    _bootstrap_inner (threading.py:1038)
    _bootstrap (threading.py:995)
Thread 2882888 (idle): "Thread-1 (_serve)"
    accept (socket.py:294)
    accept (multiprocessing/connection.py:608)
    accept (multiprocessing/connection.py:462)
    _serve (multiprocessing/resource_sharer.py:138)
    run (threading.py:975)
    _bootstrap_inner (threading.py:1038)
    _bootstrap (threading.py:995)
```

So this also hangs. I did not investigate yet where this hangs.

(<s>Also, I wonder a bit about the `--multiprocessing-fork`, which indicates that this is a fork, although it is actually started via spawn method?</s> **Edit** This is just misleading. It does not mean that this is via the fork start method. It just means that it is a sub process started via the multiprocessing logic. Maybe it is even specifically only for the spawn method.)

Some of the recent memory log entries of this TDL worker:
```
...
ep 61 train, step 120, ctc_4 3.700, ctc_8 3.376, ce 3.952, fer 0.639, num_seqs 25, max_size:time 255729, max_size:out-spatial 65, mem_usage:cuda 19.0GB, 0.654 s
ec/step
MEMORY: sub proc TDL worker 0(2882734) increased RSS: rss=604.6MB pss=473.1MB uss=436.5MB shared=168.0MB
MEMORY: total (main 2882484, 2024-01-19, 17:35:12, 31 procs): pss=15.6GB uss=14.6GB
ep 61 train, step 121, ctc_4 3.724, ctc_8 3.365, ce 4.106, fer 0.685, num_seqs 25, max_size:time 253441, max_size:out-spatial 57, mem_usage:cuda 19.0GB, 0.904 s
...
MEMORY: sub proc TDL worker 0(2882734) increased RSS: rss=628.9MB pss=497.5MB uss=460.9MB shared=168.0MB
ep 61 train, step 129, ctc_4 3.541, ctc_8 3.145, ce 3.857, fer 0.618, num_seqs 27, max_size:time 232937, max_size:out-spatial 50, mem_usage:cuda 19.0GB, 0.880 sec/step
MEMORY: total (main 2882484, 2024-01-19, 17:35:18, 31 procs): pss=15.6GB uss=14.6GB
...
```

Also, I wonder why it was not interrupted by the SIGINT. The atexit handler of the main proc does:
```python
        # The proc might have been killed by some other code. That's ok.
        try:
            # Send SIGINT, not SIGTERM or SIGKILL. See NonDaemonicSpawnProcess docstring.
            os.kill(self.proc_pid, signal.SIGINT)
        except ProcessLookupError:
            pass
        else:
            try:
                os.waitpid(self.proc_pid, 0)   # <--- line 166, where it hangs
            except ChildProcessError:
                pass
        self.proc_pid = None
```
So, this code should have send a SIGINT to the proc. Otherwise we would not even got to line 166.

Then I manually send a SIGINT. And now the log continued:
```
Process NonDaemonicSpawnProcess-15:
Traceback (most recent call last):
  File "/work/tools/users/zeyer/linuxbrew/opt/python@3.11/lib/python3.11/multiprocessing/process.py", line 317, in _bootstrap
    util._exit_function()
  File "/work/tools/users/zeyer/linuxbrew/opt/python@3.11/lib/python3.11/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/work/tools/users/zeyer/linuxbrew/opt/python@3.11/lib/python3.11/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/work/tools/users/zeyer/linuxbrew/opt/python@3.11/lib/python3.11/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/tools/users/zeyer/linuxbrew/opt/python@3.11/lib/python3.11/multiprocessing/queues.py", line 199, in _finalize_join
    thread.join()
  File "/work/tools/users/zeyer/linuxbrew/opt/python@3.11/lib/python3.11/threading.py", line 1112, in join
    self._wait_for_tstate_lock()
  File "/work/tools/users/zeyer/linuxbrew/opt/python@3.11/lib/python3.11/threading.py", line 1132, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```
And then the RETURNN train auto-restart logic worked, but this is somewhat irrelevant here:
```
MEMORY: proc <unknown-dead>(2882524) exited, old: rss=68.3MB pss=46.0MB uss=42.9MB shared=25.5MB
MEMORY: proc <unknown-dead>(2882525) exited, old: rss=68.6MB pss=46.1MB uss=42.9MB shared=25.8MB
MEMORY: proc <unknown-dead>(2882597) exited, old: rss=98.4MB pss=74.3MB uss=72.8MB shared=25.6MB
MEMORY: proc <unknown-dead>(2882598) exited, old: rss=68.3MB pss=44.3MB uss=42.8MB shared=25.5MB
MEMORY: proc <unknown-dead>(2882599) exited, old: rss=68.6MB pss=44.4MB uss=42.9MB shared=25.6MB
MEMORY: proc <unknown-dead>(2882600) exited, old: rss=68.5MB pss=44.4MB uss=42.8MB shared=25.6MB
MEMORY: proc <unknown-dead>(2882662) exited, old: rss=576.5MB pss=552.1MB uss=550.6MB shared=25.9MB
MEMORY: proc <unknown-dead>(2882663) exited, old: rss=68.4MB pss=44.3MB uss=42.8MB shared=25.5MB
MEMORY: proc <unknown-dead>(2882664) exited, old: rss=68.5MB pss=44.3MB uss=42.8MB shared=25.7MB
MEMORY: proc <unknown-dead>(2882665) exited, old: rss=68.3MB pss=44.3MB uss=42.8MB shared=25.5MB
MEMORY: proc <unknown-dead>(2882734) exited, old: rss=628.9MB pss=497.5MB uss=460.9MB shared=168.0MB
Run ['/work/tools/users/zeyer/py-envs/py3.11-torch2.1/bin/python3.11', '/u/zeyer/setups/combined/2021-05-31/tools/returnn/rnn.py', '/u/zeyer/setups/combined/2021-05-31/work/i6_core/returnn/training/ReturnnTrainingJob.XBD0ELoPJvFX/output/returnn.config']
RETURNN runtime: 2:44:40
RETURNN return code: 1
Most recent trained model epoch: 61 file: /u/zeyer/setups/combined/2021-05-31/work/i6_core/returnn/training/ReturnnTrainingJob.XBD0ELoPJvFX/output/models/epoch.061
Most recent trained model epoch before RETURNN run: 58
-> trained successfully 3 epoch(s)
Try again, restart RETURNN...
WARNING:root:Settings file 'settings.py' does not exist, ignoring it ([Errno 2] No such file or directory: 'settings.py').
Running in managed mode.
```

**Comment by albertz** [comment]
> Also, I wonder a bit about the `--multiprocessing-fork`, which indicates that this is a fork, although it is actually started via spawn method?

This is just misleading. It does not mean that this is via the fork start method. It just means that it is a sub process started via the multiprocessing logic. Maybe it is even specifically only for the spawn method.

**Comment by albertz** [comment]
Looking at the stacktrace of the TDL worker, we see that it waits in a multiprocessing `Queue` `_finalize_join`.

**Comment by albertz** [comment]
> Then I manually send a SIGINT. And now the log continued:

As this worked, we could also extend our NonDaemonicSpawnProcess atexit handler logic, to not just send a single SIGINT, but instead send one, then wait a bit, check waitpid (with timeout), if not yet finished, send SIGINT again, etc. Maybe after trying this N times, after T seconds, try with SIGTERM, and then SIGKILL, and at some point, just gave up.

But we should still investigate why it hangs in the `Queue` `_finalize_join`.

**Comment by albertz** [comment]
> Looking at the stacktrace of the TDL worker, we see that it waits in a multiprocessing `Queue` `_finalize_join`.

So, it waits for the Queue feed thread to finish. It should already have send the sentinel to it. But we see from the py-spy output, that the Queue feed thread hangs here:
```
Thread 2882887 (idle): "QueueFeederThread"
    _send (multiprocessing/connection.py:367)
    _send_bytes (multiprocessing/connection.py:404)
    send_bytes (multiprocessing/connection.py:199)
    _feed (multiprocessing/queues.py:250)
    run (threading.py:975)
    _bootstrap_inner (threading.py:1038)
    _bootstrap (threading.py:995)
```
Probably it tries to send some data but hangs.

I wonder a bit why this hangs if the relevant subproc already quitted. Shouldn't this lead to a sigpipe? Or is the relevant subproc still alive? But it did not look like that. Also, from the TDL worker py-spy output, we see that the main thread is in `_exit_function` below the point where it terminated and joined all the procs. This implies that there are no alive subprocs anymore.

**Comment by albertz** [comment]
Ok, the proc continued, and then when it got the next OOM, it hanged again at exit:
```
...
ep 159 train, step 349, ctc_4 1.890, ctc_8 1.582, ce 1.492, fer 0.275, num_seqs 22, max_size:time 279752, max_size:out-spatial 65, mem_usage:cuda 19.0GB, 0.809 sec/step
ep 159 train, step 350, ctc_4 1.854, ctc_8 1.529, ce 1.333, fer 0.263, num_seqs 22, max_size:time 281512, max_size:out-spatial 67, mem_usage:cuda 19.0GB, 0.692 sec/step
ep 159 train, step 351, ctc_4 1.789, ctc_8 1.459, ce 1.227, fer 0.258, num_seqs 22, max_size:time 286264, max_size:out-spatial 67, mem_usage:cuda 19.0GB, 0.879 sec/step
ep 159 train, step 352, ctc_4 1.700, ctc_8 1.383, ce 1.160, fer 0.230, num_seqs 22, max_size:time 290576, max_size:out-spatial 64, mem_usage:cuda 19.0GB, 0.680 sec/step
OutOfMemoryError: CUDA out of memory. Tried to allocate 264.00 MiB. GPU 0 has a total capacty of 22.03 GiB of which 238.88 MiB is free. Including non-PyTorch memory, this process has 21.80 GiB memory in use. Of the allocated memory 19.31 GiB is allocated by PyTorch, and 1.12 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Unhandled exception <class 'torch.cuda.OutOfMemoryError'> in thread <_MainThread(MainThread, started 140688618846016)>, proc 2884751. 

...
OutOfMemoryError: CUDA out of memory. Tried to allocate 264.00 MiB. GPU 0 has a total capacty of 22.03 GiB of which 238.88 MiB is free. Including non-PyTorch memory, this process has 21.80 GiB memory in use. Of the allocated memory 19.31 GiB is allocated by PyTorch, and 1.12 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Module call stack:
(No module call frames.)
MEMORY: proc <unknown-dead>(2885470) exited, old: rss=737.9MB pss=712.4MB uss=711.7MB shared=26.2MB
MEMORY: total (main 2884751, 2024-01-20, 07:32:32, 30 procs): pss=16.4GB uss=15.4GB
[2024-01-20 07:32:33,168] INFO: Run time: 20:38:14 CPU: 0.20% RSS: 15.80GB VMS: 121.23GB
<OggZipDataset 'train' epoch=62>, epoch 62. No filter for this epoch.
<OggZipDataset 'train' epoch=63>, epoch 63. No filter for this epoch.
<OggZipDataset 'train' epoch=64>, epoch 64. No filter for this epoch.
<OggZipDataset 'train' epoch=65>, epoch 65. No filter for this epoch.
<OggZipDataset 'train' epoch=66>, epoch 66. No filter for this epoch.
<OggZipDataset 'train' epoch=67>, epoch 67. No filter for this epoch.
<OggZipDataset 'train' epoch=68>, epoch 68. No filter for this epoch.
<OggZipDataset 'train' epoch=69>, epoch 69. No filter for this epoch.
<OggZipDataset 'train' epoch=70>, epoch 70. No filter for this epoch.
<OggZipDataset 'train' epoch=71>, epoch 71. No filter for this epoch.
<OggZipDataset 'train' epoch=72>, epoch 72. No filter for this epoch.
<OggZipDataset 'train' epoch=73>, epoch 73. No filter for this epoch.
<OggZipDataset 'train' epoch=74>, epoch 74. No filter for this epoch.
<OggZipDataset 'train' epoch=75>, epoch 75. No filter for this epoch.
<OggZipDataset 'train' epoch=76>, epoch 76. No filter for this epoch.
<OggZipDataset 'train' epoch=77>, epoch 77. No filter for this epoch.
<OggZipDataset 'train' epoch=78>, epoch 78. No filter for this epoch.
<OggZipDataset 'train' epoch=79>, epoch 79. No filter for this epoch.
<OggZipDataset 'train' epoch=80>, epoch 80. No filter for this epoch.
<OggZipDataset 'train' epoch=81>, epoch 81. No filter for this epoch.
<OggZipDataset 'train' epoch=82>, epoch 82. No filter for this epoch.
<OggZipDataset 'train' epoch=83>, epoch 83. No filter for this epoch.
<OggZipDataset 'train' epoch=84>, epoch 84. No filter for this epoch.
<OggZipDataset 'train' epoch=85>, epoch 85. No filter for this epoch.
<OggZipDataset 'train' epoch=86>, epoch 86. No filter for this epoch.
<OggZipDataset 'train' epoch=87>, epoch 87. No filter for this epoch.
<OggZipDataset 'train' epoch=88>, epoch 88. No filter for this epoch.
<OggZipDataset 'train' epoch=89>, epoch 89. No filter for this epoch.
<OggZipDataset 'train' epoch=90>, epoch 90. No filter for this epoch.
<OggZipDataset 'train' epoch=91>, epoch 91. No filter for this epoch.
<OggZipDataset 'train' epoch=92>, epoch 92. No filter for this epoch.
<OggZipDataset 'train' epoch=93>, epoch 93. No filter for this epoch.
<OggZipDataset 'train' epoch=94>, epoch 94. No filter for this epoch.
<OggZipDataset 'train' epoch=95>, epoch 95. No filter for this epoch.
<OggZipDataset 'train' epoch=96>, epoch 96. No filter for this epoch.
<OggZipDataset 'train' epoch=97>, epoch 97. No filter for this epoch.
<OggZipDataset 'train' epoch=98>, epoch 98. No filter for this epoch.
<OggZipDataset 'train' epoch=99>, epoch 99. No filter for this epoch.
<OggZipDataset 'train' epoch=100>, epoch 100. No filter for this epoch.
<OggZipDataset 'train' epoch=101>, epoch 101. No filter for this epoch.
<OggZipDataset 'train' epoch=102>, epoch 102. No filter for this epoch.
<OggZipDataset 'train' epoch=103>, epoch 103. No filter for this epoch.
<OggZipDataset 'train' epoch=104>, epoch 104. No filter for this epoch.
<OggZipDataset 'train' epoch=105>, epoch 105. No filter for this epoch.
<OggZipDataset 'train' epoch=106>, epoch 106. No filter for this epoch.
<OggZipDataset 'train' epoch=107>, epoch 107. No filter for this epoch.
<OggZipDataset 'train' epoch=108>, epoch 108. No filter for this epoch.
<OggZipDataset 'train' epoch=109>, epoch 109. No filter for this epoch.
<OggZipDataset 'train' epoch=110>, epoch 110. No filter for this epoch.
<OggZipDataset 'train' epoch=111>, epoch 111. No filter for this epoch.
<OggZipDataset 'train' epoch=112>, epoch 112. No filter for this epoch.
<OggZipDataset 'train' epoch=113>, epoch 113. No filter for this epoch.
<OggZipDataset 'train' epoch=114>, epoch 114. No filter for this epoch.
<OggZipDataset 'train' epoch=115>, epoch 115. No filter for this epoch.
<OggZipDataset 'train' epoch=116>, epoch 116. No filter for this epoch.
<OggZipDataset 'train' epoch=117>, epoch 117. No filter for this epoch.
<OggZipDataset 'train' epoch=118>, epoch 118. No filter for this epoch.
<OggZipDataset 'train' epoch=119>, epoch 119. No filter for this epoch.
<OggZipDataset 'train' epoch=120>, epoch 120. No filter for this epoch.
<OggZipDataset 'train' epoch=121>, epoch 121. No filter for this epoch.
<OggZipDataset 'train' epoch=122>, epoch 122. No filter for this epoch.
<OggZipDataset 'train' epoch=123>, epoch 123. No filter for this epoch.
<OggZipDataset 'train' epoch=124>, epoch 124. No filter for this epoch.
<OggZipDataset 'train' epoch=125>, epoch 125. No filter for this epoch.
<OggZipDataset 'train' epoch=126>, epoch 126. No filter for this epoch.
<OggZipDataset 'train' epoch=127>, epoch 127. No filter for this epoch.
<OggZipDataset 'train' epoch=128>, epoch 128. No filter for this epoch.
<OggZipDataset 'train' epoch=129>, epoch 129. No filter for this epoch.
<OggZipDataset 'train' epoch=130>, epoch 130. No filter for this epoch.
<OggZipDataset 'train' epoch=131>, epoch 131. No filter for this epoch.
<OggZipDataset 'train' epoch=132>, epoch 132. No filter for this epoch.
<OggZipDataset 'train' epoch=133>, epoch 133. No filter for this epoch.
<OggZipDataset 'train' epoch=134>, epoch 134. No filter for this epoch.
<OggZipDataset 'train' epoch=135>, epoch 135. No filter for this epoch.
<OggZipDataset 'train' epoch=136>, epoch 136. No filter for this epoch.
<OggZipDataset 'train' epoch=137>, epoch 137. No filter for this epoch.
<OggZipDataset 'train' epoch=138>, epoch 138. No filter for this epoch.
<OggZipDataset 'train' epoch=139>, epoch 139. No filter for this epoch.
<OggZipDataset 'train' epoch=140>, epoch 140. No filter for this epoch.
<OggZipDataset 'train' epoch=141>, epoch 141. No filter for this epoch.
<OggZipDataset 'train' epoch=142>, epoch 142. No filter for this epoch.
<OggZipDataset 'train' epoch=143>, epoch 143. No filter for this epoch.
<OggZipDataset 'train' epoch=144>, epoch 144. No filter for this epoch.
<OggZipDataset 'train' epoch=145>, epoch 145. No filter for this epoch.
<OggZipDataset 'train' epoch=146>, epoch 146. No filter for this epoch.
<OggZipDataset 'train' epoch=147>, epoch 147. No filter for this epoch.
<OggZipDataset 'train' epoch=148>, epoch 148. No filter for this epoch.
<OggZipDataset 'train' epoch=149>, epoch 149. No filter for this epoch.
<OggZipDataset 'train' epoch=150>, epoch 150. No filter for this epoch.
<OggZipDataset 'train' epoch=151>, epoch 151. No filter for this epoch.
<OggZipDataset 'train' epoch=152>, epoch 152. No filter for this epoch.
<OggZipDataset 'train' epoch=153>, epoch 153. No filter for this epoch.
<OggZipDataset 'train' epoch=154>, epoch 154. No filter for this epoch.
<OggZipDataset 'train' epoch=155>, epoch 155. No filter for this epoch.
<OggZipDataset 'train' epoch=156>, epoch 156. No filter for this epoch.
<OggZipDataset 'train' epoch=157>, epoch 157. No filter for this epoch.
<OggZipDataset 'train' epoch=158>, epoch 158. No filter for this epoch.
<OggZipDataset 'train' epoch=159>, epoch 159. No filter for this epoch.
MEMORY: proc <unknown-dead>(2885245) exited, old: rss=625.7MB pss=494.4MB uss=457.8MB shared=167.9MB
MEMORY: proc <unknown-dead>(2885378) exited, old: rss=630.0MB pss=498.7MB uss=462.2MB shared=167.8MB
MEMORY: proc <unknown-dead>(2885426) exited, old: rss=737.9MB pss=712.5MB uss=711.8MB shared=26.2MB
MEMORY: proc <unknown-dead>(2885440) exited, old: rss=741.3MB pss=715.5MB uss=714.6MB shared=26.6MB
MEMORY: proc <unknown-dead>(2885455) exited, old: rss=737.6MB pss=712.1MB uss=711.3MB shared=26.3MB
MEMORY: proc <unknown-dead>(2885294) exited, old: rss=117.4MB pss=91.8MB uss=91.0MB shared=26.4MB
MEMORY: proc <unknown-dead>(2885308) exited, old: rss=118.9MB pss=93.5MB uss=92.8MB shared=26.1MB
MEMORY: proc <unknown-dead>(2885323) exited, old: rss=118.3MB pss=92.8MB uss=92.0MB shared=26.3MB
MEMORY: proc <unknown-dead>(2885338) exited, old: rss=117.4MB pss=91.9MB uss=91.2MB shared=26.3MB
MEMORY: proc <unknown-dead>(2885063) exited, old: rss=0.9GB pss=0.8GB uss=0.8GB shared=26.4MB
MEMORY: proc <unknown-dead>(2885077) exited, old: rss=0.9GB pss=805.2MB uss=784.6MB shared=102.1MB
MEMORY: proc <unknown-dead>(2885093) exited, old: rss=0.9GB pss=805.1MB uss=784.3MB shared=102.6MB
MEMORY: proc <unknown-dead>(2885108) exited, old: rss=0.9GB pss=804.8MB uss=776.3MB shared=98.8MB
MEMORY: total (main 2884751, 2024-01-20, 07:32:37, 17 procs): pss=9.8GB uss=9.0GB
[2024-01-20 07:32:38,185] INFO: Run time: 20:38:19 CPU: 0.40% RSS: 10.59GB VMS: 85.03GB
```

**Comment by albertz** [comment]
> As this worked, we could also extend our NonDaemonicSpawnProcess atexit handler logic, to not just send a single SIGINT, but instead send one, then wait a bit, check waitpid (with timeout), if not yet finished, send SIGINT again, etc. Maybe after trying this N times, after T seconds, try with SIGTERM, and then SIGKILL, and at some point, just gave up.

That's exactly what I implemented now, and this should solve the issue of the hang in the mainproc here. But we should still figure out why it hangs in the subproc. This is still not clear to me.

(Anyway, leaving it closed now, as the priority is low now. The problem probably existed all the time but was always unnoticed, as a normal daemon proc got just terminated.)
