### ISSUE TITLE
Hang

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#1500]
After getting https://github.com/espnet/espnet/issues/5628, it hanged.

In the log:
```
...
Send signal SIGINT to pid 193510
Send signal SIGINT to pid 193510
  File "/work/tools/users/zeyer/linuxbrew/opt/python@3.11/lib/python3.11/multiprocessing/process.py", line 317, in _bootstrap
    util._exit_function()
  File "/work/tools/users/zeyer/linuxbrew/opt/python@3.11/lib/python3.11/multiprocessing/util.py", line 357, in _exit_function
    p.join()
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/util/multi_proc_non_daemonic_spawn.py", line 94, in join
    super().join(timeout=5)
  File "/work/tools/users/zeyer/linuxbrew/opt/python@3.11/lib/python3.11/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/tools/users/zeyer/linuxbrew/opt/python@3.11/lib/python3.11/multiprocessing/popen_fork.py", line 40, in wait
    if not wait([self.sentinel], timeout):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/tools/users/zeyer/linuxbrew/opt/python@3.11/lib/python3.11/multiprocessing/connection.py", line 932, in wait
    return [key.fileobj for (key, events) in ready]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/tools/users/zeyer/linuxbrew/opt/python@3.11/lib/python3.11/multiprocessing/connection.py", line 932, in <listcomp>
    return [key.fileobj for (key, events) in ready]
    
KeyboardInterrupt
Send signal SIGINT to pid 193406
Send signal SIGINT to pid 193406
MEMORY: proc MPD worker 0(193406) exited, old: rss=728.7MB pss=702.8MB uss=702.6MB shared=26.1MB
MEMORY: proc MPD worker 3(193759) exited, old: rss=728.6MB pss=702.8MB uss=702.6MB shared=26.0MB
MEMORY: total (main 188267, 2024-01-21, 10:41:57, 29 procs): pss=11.7GB uss=10.8GB
MEMORY: proc <unknown-dead>(193511) exited, old: rss=732.4MB pss=706.6MB uss=706.4MB shared=26.0MB
MEMORY: proc <unknown-dead>(193619) exited, old: rss=734.6MB pss=708.8MB uss=708.7MB shared=26.0MB
MEMORY: proc <unknown-dead>(193727) exited, old: rss=735.4MB pss=709.5MB uss=709.4MB shared=26.0MB
Send signal SIGINT to pid 193759
Send signal SIGINT to pid 193621
Send signal SIGINT to pid 193513
Send signal SIGINT to pid 193406
Send signal SIGINT to pid 193726
Send signal SIGINT to pid 193618
Send signal SIGINT to pid 193510
Send signal SIGINT to pid 193409
Send signal SIGINT to pid 193727
...
MEMORY: proc <unknown-dead>(193408) exited, old: rss=735.0MB pss=709.3MB uss=709.1MB shared=25.8MB
MEMORY: total (main 188264, 2024-01-21, 10:41:59, 27 procs): pss=10.4GB uss=9.5GB
Exception ignored in atexit callback: <returnn.util.multi_proc_non_daemonic_spawn._AtExitCleanupProcess object at 0x7fe33a5b7ed0>
Traceback (most recent call last):
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/util/multi_proc_non_daemonic_spawn.py", line 184, in __call__
    time.sleep(4)
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 193168) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace. 
Send signal SIGINT to pid 192331
Exception ignored in atexit callbackException ignored in atexit callback: : <returnn.util.multi_proc_non_daemonic_spawn._AtExitCleanupProcess object at 0x7f7779fdffd0><returnn.util.multi_proc_non_daemonic_spawn._AtExitCleanupProcess object at 0x7f7cb9513f50> 

Traceback (most recent call last):
Traceback (most recent call last):
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/util/multi_proc_non_daemonic_spawn.py", line 184, in __call__
  File "/u/zeyer/setups/combined/2021-05-31/tools/returnn/returnn/util/multi_proc_non_daemonic_spawn.py", line 184, in __call__
    time.sleep(4)
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    time.sleep(4)
  File "/work/tools/users/zeyer/py-envs/py3.11-torch2.1/lib/python3.11/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 193167) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace. 
Send signal SIGINT to pid 192335
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 193165) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace. 
Send signal SIGINT to pid 192334
...
Send signal SIGINT to pid 190084
Send signal SIGINT to pid 189018
Send signal SIGINT to pid 188530
Send signal SIGINT to pid 188527
Send signal SIGINT to pid 188531
Send signal SIGINT to pid 188535
Send signal SIGINT to pid 189022
Send signal SIGINT to pid 189025
Send signal SIGINT to pid 192335
Send signal SIGINT to pid 189473
Send signal SIGINT to pid 190085
Send signal SIGINT to pid 189470
Send signal SIGINT to pid 189023
Send signal SIGINT to pid 189472
Send signal SIGINT to pid 189471
Send signal SIGINT to pid 188539
Send signal SIGINT to pid 189024
[2024-01-21 10:42:27,095] INFO: Run time: 2:52:11 CPU: 0.60% RSS: 19.69GB VMS: 177.84GB
[2024-01-21 10:42:32,111] INFO: Run time: 2:52:16 CPU: 0.20% RSS: 5.59GB VMS: 47.64GB
```

Alive procs:
```
zeyer@cn-244 ~ % ps a --forest -u $(whoami) -o pid,comm
    PID COMMAND
 198320 sshd
 198321  \_ zsh
 198339      \_ ps
 188214 slurm_script
 188219  \_ python3.11
 188246      \_ python3.11
 188264          \_ python3.11 <defunct>
 188403          |   \_ python3.11 <defunct>
 188265          \_ python3.11
 188404          |   \_ python3.11
 188266          \_ python3.11 <defunct>
 188454          |   \_ python3.11 <defunct>
 188267          \_ python3.11 <defunct>
 188401              \_ python3.11 <defunct>
 198309 systemd
 198310  \_ (sd-pam)
   1772 agetty
```

Sub proc:
```
zeyer@cn-244 ~ % py-spy dump -p 188404
Process 188404: /work/tools/users/zeyer/py-envs/py3.11-torch2.1/bin/python3.11 -c from multiprocessing.resource_tracker import main;main(31)
Python v3.11.2 (/work/tools/users/zeyer/linuxbrew/Cellar/python@3.11/3.11.2_1/bin/python3.11)

Thread 188404 (idle): "MainThread"
    main (multiprocessing/resource_tracker.py:197)
    <module> (<string>:1)
```

Main proc:
```
zeyer@cn-244 ~ % py-spy dump -p 188265
Error: Failed to find a python interpreter in the .data section
zeyer@cn-244 ~ % py-spy dump -p 188265
Error: Failed to find a python interpreter in the .data section
zeyer@cn-244 ~ % pystack remote 188265



^CTraceback (most recent call last):
  File "/work/tools/users/zeyer/linuxbrew/opt/python@3.11/lib/python3.11/logging/__init__.py", line 1544, in log
    def log(self, level, msg, *args, **kwargs):

KeyboardInterrupt
Exception ignored in: 'pystack._pystack.log_with_python'
Traceback (most recent call last):
  File "/work/tools/users/zeyer/linuxbrew/opt/python@3.11/lib/python3.11/logging/__init__.py", line 1544, in log
    def log(self, level, msg, *args, **kwargs):

KeyboardInterrupt: 
WARNING(process_remote): The interpreter is shutting itself down so it is possible that no Python stack trace is available for inspection. You can still use --native-all  to force displaying all the threads.
```

I even cannot attach with GDB.

Also, maybe a hardware issue:
```
zeyer@cn-244 ~ % nvidia-smi                        
Unable to determine the device handle for GPU0000:03:00.0: Unknown Error
```

**Comment by albertz** [comment]
And `dmesg`:
```
[  +0.000844] nvidia 0000:03:00.0: AER: can't recover (no error_detected callback)
[  +0.000001] snd_hda_intel 0000:03:00.1: AER: can't recover (no error_detected callback)
[  +0.000008] pcieport 0000:00:03.0: AER: device recovery failed
[  +0.000001] pcieport 0000:00:03.0: AER: Multiple Uncorrected (Fatal) error received: 0000:00:03.0
[  +0.000004] pcieport 0000:00:03.0: PCIe Bus Error: severity=Uncorrected (Fatal), type=Transaction Layer, (Requester ID)
[  +0.000898] pcieport 0000:00:03.0:   device [8086:6f08] error status/mask=00004020/00000000
[  +0.000889] pcieport 0000:00:03.0:    [ 5] SDES                  
[  +0.000894] pcieport 0000:00:03.0:    [14] CmpltTO                (First)
[  +0.000921] nvidia 0000:03:00.0: AER: can't recover (no error_detected callback)
[  +0.000002] snd_hda_intel 0000:03:00.1: AER: can't recover (no error_detected callback)
[  +1.050439] pcieport 0000:00:03.0: AER: Root Port link has been reset (0)
[  +0.000041] pcieport 0000:00:03.0: AER: device recovery failed
```

**Comment by albertz** [comment]
I guess nothing we can do, it's just a hardware issue.
