### ISSUE TITLE
`FileCache`: Race condition when removing empty directories

### ISSUE THREAD

**Issue by NeoLegends** [rwth-i6/returnn#1550]
The empty dir check causes issues w/ file caching. I'm adding this condition to the retryable exceptions.

```
Process DistributeFilesDataset train file cache:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/returnn/returnn/datasets/distrib_files.py", line 734, in _file_cache_proc_loop
    res, files = file_cache.handle_cached_files_in_config(**kwargs)
  File "/returnn/returnn/util/file_cache.py", line 272, in handle_cached_files_in_config
    return tree.map_structure(_handle_value, config), res_files
  File "/usr/local/lib/python3.10/dist-packages/tree/__init__.py", line 435, in map_structure
    [func(*args) for args in zip(*map(flatten, structures))])
  File "/usr/local/lib/python3.10/dist-packages/tree/__init__.py", line 435, in <listcomp>
    [func(*args) for args in zip(*map(flatten, structures))])
  File "/returnn/returnn/util/file_cache.py", line 267, in _handle_value
    res = self.get_file(value.filename)
  File "/returnn/returnn/util/file_cache.py", line 121, in get_file
    raise e
  File "/returnn/returnn/util/file_cache.py", line 115, in get_file
    self._copy_file_if_needed(src_filename, dst_filename)
  File "/returnn/returnn/util/file_cache.py", line 316, in _copy_file_if_needed
    _copy_with_prealloc(src_filename, dst_tmp_filename)
  File "/returnn/returnn/util/file_cache.py", line 348, in _copy_with_prealloc
    with open(dst, "wb") as dst_file:
FileNotFoundError: [Errno 2] No such file or directory: '[redacted]'
Waiting for lock-file: /tmp/wmichel/returnn/file_cache/dir.lock
Waiting for lock-file: /tmp/wmichel/returnn/file_cache/dir.lock
FileCache: Copy file [redacted] to cache
FileCache: Remove empty dir [redacted]
EOFError:
This exception is thrown by __iter__ of ChunkingIterDataPipe()
Unhandled exception <class 'EOFError'> in thread <_MainThread(MainThread, started 139974150349248)>, proc 584170.
```

**Comment by NeoLegends** [comment]
cc @michelwi

**Comment by albertz** [comment]
I wonder how this could happen. The cleanup logic to remove empty dirs should actually check how old those dirs are, and thus not remove recently used dirs. This seems to me the actual main issue here.

**Comment by NeoLegends** [comment]
Maybe a strange FS configuration?

**Comment by albertz** [comment]
I would rather expect a bug in our code. I don't think such issues happen with a local FS. Maybe we don't touch all relevant dirs after using them? Actually, before we did the file-based lock, and the `_FileCacheProc` thus should have kept the dirs up-to-date. But after you changed that, maybe that was not the case anymore.

**Comment by NeoLegends** [comment]
See also https://github.com/rwth-i6/returnn/pull/1551#issuecomment-2182704936 and the discussion at https://github.com/rwth-i6/returnn/pull/1551#discussion_r1648771205.
