### ISSUE TITLE
DistributeFilesDataset has issues with DataLoader and `num_workers > 0`

### ISSUE THREAD

**Issue by NeoLegends** [rwth-i6/returnn#1554]
There are issues w/ pickling the dataset when transferring it to a child process.

```
EXCEPTION
Traceback (most recent call last):
  File "/.../work/i6_core/tools/git/CloneGitRepositoryJob.H9Cu9IA2vYwT/output/returnn/rnn.py", line 11, in <module>
    line: main()
    locals:
      main = <local> <function main at 0x7f19426253f0>
  File "/.../work/i6_core/tools/git/CloneGitRepositoryJob.H9Cu9IA2vYwT/output/returnn/returnn/__main__.py", line 736, in main
    line: execute_main_task()
    locals:
      execute_main_task = <global> <function execute_main_task at 0x7f19426252d0>
  File "/.../work/i6_core/tools/git/CloneGitRepositoryJob.H9Cu9IA2vYwT/output/returnn/returnn/__main__.py", line 542, in execute_main_task
    line: engine.train()
    locals:
      engine = <global> <returnn.torch.engine.Engine object at 0x7f18394ba590>
      engine.train = <global> <bound method Engine.train of <returnn.torch.engine.Engine object at 0x7f18394ba590>>
  File "/.../work/i6_core/tools/git/CloneGitRepositoryJob.H9Cu9IA2vYwT/output/returnn/returnn/torch/engine.py", line 236, in Engine.train
    line: self.train_epoch()
    locals:
      self = <local> <returnn.torch.engine.Engine object at 0x7f18394ba590>
      self.train_epoch = <local> <bound method Engine.train_epoch of <returnn.torch.engine.Engine object at 0x7f18394ba590>>
  File "/.../work/i6_core/tools/git/CloneGitRepositoryJob.H9Cu9IA2vYwT/output/returnn/returnn/torch/engine.py", line 342, in Engine.train_epoch
    line: data_iter = iter(self._train_dataloader)
    locals:
      data_iter = <not found>
      iter = <builtin> <built-in function iter>
      self = <local> <returnn.torch.engine.Engine object at 0x7f18394ba590>
      self._train_dataloader = <local> <torch.utils.data.dataloader.DataLoader object at 0x7f183040ee60>
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 434, in DataLoader.__iter__
    line: self._iterator = self._get_iterator()
    locals:
      self = <local> <torch.utils.data.dataloader.DataLoader object at 0x7f183040ee60>
      self._iterator = <local> None
      self._get_iterator = <local> <bound method DataLoader._get_iterator of <torch.utils.data.dataloader.DataLoader object at 0x7f183040ee60>>
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 387, in DataLoader._get_iterator
    line: return _MultiProcessingDataLoaderIter(self)
    locals:
      _MultiProcessingDataLoaderIter = <global> <class 'torch.utils.data.dataloader._MultiProcessingDataLoaderIter'>
      self = <local> <torch.utils.data.dataloader.DataLoader object at 0x7f183040ee60>
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1040, in _MultiProcessingDataLoaderIter.__init__
    line: w.start()
    locals:
      w = <local> <NonDaemonicSpawnProcess name='NonDaemonicSpawnProcess-2' parent=1032586 initial>
      w.start = <local> <bound method NonDaemonicSpawnProcess.start of <NonDaemonicSpawnProcess name='NonDaemonicSpawnProcess-2' parent=1032586 initial>>
  File "/.../work/i6_core/tools/git/CloneGitRepositoryJob.H9Cu9IA2vYwT/output/returnn/returnn/util/multi_proc_non_daemonic_spawn.py", line 62, in NonDaemonicSpawnProcess.start
    line: super().start()
    locals:
      super = <builtin> <class 'super'>
      start = <not found>
  File "/usr/lib/python3.10/multiprocessing/process.py", line 121, in BaseProcess.start
    line: self._popen = self._Popen(self)
    locals:
      self = <local> <NonDaemonicSpawnProcess name='NonDaemonicSpawnProcess-2' parent=1032586 initial>
      self._popen = <local> None
      self._Popen = <local> <function SpawnProcess._Popen at 0x7f1859229090>
  File "/usr/lib/python3.10/multiprocessing/context.py", line 288, in SpawnProcess._Popen
    line: return Popen(process_obj)
    locals:
      Popen = <local> <class 'multiprocessing.popen_spawn_posix.Popen'>
      process_obj = <local> <NonDaemonicSpawnProcess name='NonDaemonicSpawnProcess-2' parent=1032586 initial>
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in Popen.__init__
    line: super().__init__(process_obj)
    locals:
      super = <builtin> <class 'super'>
      __init__ = <not found>
      process_obj = <local> <NonDaemonicSpawnProcess name='NonDaemonicSpawnProcess-2' parent=1032586 initial>
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 19, in Popen.__init__
    line: self._launch(process_obj)
    locals:
      self = <local> <multiprocessing.popen_spawn_posix.Popen object at 0x7f17f41bfdc0>
      self._launch = <local> <bound method Popen._launch of <multiprocessing.popen_spawn_posix.Popen object at 0x7f17f41bfdc0>>
      process_obj = <local> <NonDaemonicSpawnProcess name='NonDaemonicSpawnProcess-2' parent=1032586 initial>
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in Popen._launch
    line: reduction.dump(process_obj, fp)
    locals:
      reduction = <global> <module 'multiprocessing.reduction' from '/usr/lib/python3.10/multiprocessing/reduction.py'>
      reduction.dump = <global> <function dump at 0x7f1859205750>
      process_obj = <local> <NonDaemonicSpawnProcess name='NonDaemonicSpawnProcess-2' parent=1032586 initial>
      fp = <local> <_io.BytesIO object at 0x7f17f41fa660>
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    line: ForkingPickler(file, protocol).dump(obj)
    locals:
      ForkingPickler = <global> <class 'multiprocessing.reduction.ForkingPickler'>
      file = <local> <_io.BytesIO object at 0x7f17f41fa660>
      protocol = <local> None
      dump = <global> <function dump at 0x7f1859205750>
      obj = <local> <NonDaemonicSpawnProcess name='NonDaemonicSpawnProcess-2' parent=1032586 initial>
  File "/.../work/i6_core/tools/git/CloneGitRepositoryJob.H9Cu9IA2vYwT/output/returnn/returnn/util/multi_proc_non_daemonic_spawn.py", line 128, in NonDaemonicSpawnProcess.__reduce__
    line: reduction.dump((reconstruct_func, reconstruct_args, reconstruct_state), buffer)
    locals:
      reduction = <global> <module 'multiprocessing.reduction' from '/usr/lib/python3.10/multiprocessing/reduction.py'>
      reduction.dump = <global> <function dump at 0x7f1859205750>
      reconstruct_func = <local> <function _reconstructor at 0x7f1958671bd0>
      reconstruct_args = <local> (<class 'returnn.util.multi_proc_non_daemonic_spawn.NonDaemonicSpawnProcess'>, <class 'object'>, None)
      reconstruct_state = <local> {'_identity': (2,), '_config': {'authkey': b"\x83\x0e\x84\xae\xc3\x88c\x1b\x9f\xbb'\xc6V\x03\x13wj\x87~\x07\x19VK\x83\xd74\x02\x9eND\x12\xdb", 'semprefix': '/mp'}, '_parent_pid': 1032586, '_parent_name': 'MainProcess', '_popen': None, '_closed': False, '_target': <function _worker_loop at 0x7f185..., len = 10
      buffer = <local> <_io.BytesIO object at 0x7f17f41fa980>
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    line: ForkingPickler(file, protocol).dump(obj)
    locals:
      ForkingPickler = <global> <class 'multiprocessing.reduction.ForkingPickler'>
      file = <local> <_io.BytesIO object at 0x7f17f41fa980>
      protocol = <local> None
      dump = <global> <function dump at 0x7f1859205750>
      obj = <local> (<function _reconstructor at 0x7f1958671bd0>, (<class 'returnn.util.multi_proc_non_daemonic_spawn.NonDaemonicSpawnProcess'>, <class 'object'>, None), {'_identity': (2,), '_config': {'authkey': b"\x83\x0e\x84\xae\xc3\x88c\x1b\x9f\xbb'\xc6V\x03\x13wj\x87~\x07\x19VK\x83\xd74\x02\x9eND\x12\xdb", 'sem...
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/datapipes/datapipe.py", line 172, in IterDataPipe.__reduce_ex__
    line: return super().__reduce_ex__(*args, **kwargs)
    locals:
      super = <builtin> <class 'super'>
      __reduce_ex__ = <not found>
      args = <local> (4,)
      kwargs = <local> {}
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/datapipes/datapipe.py", line 350, in _DataPipeSerializationWrapper.__getstate__
    line: value = dill.dumps(self._datapipe)
    locals:
      value = <not found>
      dill = <global> <module 'dill' from '/usr/local/lib/python3.10/dist-packages/dill/__init__.py'>
      dill.dumps = <global> <function dumps at 0x7f1858c08d30>
      self = <not found>
      self._datapipe = <not found>
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 280, in dumps
    line: dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
    locals:
      dump = <global> <function dump at 0x7f1858c08ca0>
      obj = <local> BatchingIterDataPipe
      file = <local> <_io.BytesIO object at 0x7f1852152e80>
      protocol = <local> None
      byref = <local> None
      fmode = <local> None
      recurse = <local> None
      kwds = <local> {}
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 252, in dump
    line: Pickler(file, protocol, **_kwds).dump(obj)
    locals:
      Pickler = <global> <class 'dill._dill.Pickler'>
      file = <local> <_io.BytesIO object at 0x7f1852152e80>
      protocol = <local> 4
      _kwds = <local> {'byref': None, 'fmode': None, 'recurse': None}
      dump = <global> <function dump at 0x7f1858c08ca0>
      obj = <local> BatchingIterDataPipe
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 420, in Pickler.dump
    line: StockPickler.dump(self, obj)
    locals:
      StockPickler = <global> <class 'pickle._Pickler'>
      StockPickler.dump = <global> <function _Pickler.dump at 0x7f195847d510>
      self = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      obj = <local> BatchingIterDataPipe
  File "/usr/lib/python3.10/pickle.py", line 487, in _Pickler.dump
    line: self.save(obj)
    locals:
      self = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      self.save = <local> <bound method Pickler.save of <dill._dill.Pickler object at 0x7f17f42002b0>>
      obj = <local> BatchingIterDataPipe
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 414, in Pickler.save
    line: StockPickler.save(self, obj, save_persistent_id)
    locals:
      StockPickler = <global> <class 'pickle._Pickler'>
      StockPickler.save = <global> <function _Pickler.save at 0x7f195847d750>
      self = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      obj = <local> BatchingIterDataPipe
      save_persistent_id = <local> True
  File "/usr/lib/python3.10/pickle.py", line 603, in _Pickler.save
    line: self.save_reduce(obj=obj, *rv)
    locals:
      self = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      self.save_reduce = <local> <bound method _Pickler.save_reduce of <dill._dill.Pickler object at 0x7f17f42002b0>>
      obj = <local> BatchingIterDataPipe
      rv = <local> (<function __newobj__ at 0x7f1958671cf0>, (<class 'returnn.torch.data.pipeline.BatchingIterDataPipe'>,), {'_dataset': ChunkingIterDataPipe, '_max_batch_size': NumbersDict({'classes': 5000, 'data': 800000}), '_max_seqs': 9223372036854775807}, None, None)
  File "/usr/lib/python3.10/pickle.py", line 717, in _Pickler.save_reduce
    line: save(state)
    locals:
      save = <local> <bound method Pickler.save of <dill._dill.Pickler object at 0x7f17f42002b0>>
      state = <local> {'_dataset': ChunkingIterDataPipe, '_max_batch_size': NumbersDict({'classes': 5000, 'data': 800000}), '_max_seqs': 9223372036854775807}
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 414, in Pickler.save
    line: StockPickler.save(self, obj, save_persistent_id)
    locals:
      StockPickler = <global> <class 'pickle._Pickler'>
      StockPickler.save = <global> <function _Pickler.save at 0x7f195847d750>
      self = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      obj = <local> {'_dataset': ChunkingIterDataPipe, '_max_batch_size': NumbersDict({'classes': 5000, 'data': 800000}), '_max_seqs': 9223372036854775807}
      save_persistent_id = <local> True
  File "/usr/lib/python3.10/pickle.py", line 560, in _Pickler.save
    line: f(self, obj)  # Call unbound method with explicit self
    locals:
      f = <local> <function save_module_dict at 0x7f1858c0add0>
      self = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      obj = <local> {'_dataset': ChunkingIterDataPipe, '_max_batch_size': NumbersDict({'classes': 5000, 'data': 800000}), '_max_seqs': 9223372036854775807}
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 1217, in save_module_dict
    line: StockPickler.save_dict(pickler, obj)
    locals:
      StockPickler = <global> <class 'pickle._Pickler'>
      StockPickler.save_dict = <global> <function _Pickler.save_dict at 0x7f195847dfc0>
      pickler = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      obj = <local> {'_dataset': ChunkingIterDataPipe, '_max_batch_size': NumbersDict({'classes': 5000, 'data': 800000}), '_max_seqs': 9223372036854775807}
  File "/usr/lib/python3.10/pickle.py", line 972, in _Pickler.save_dict
    line: self._batch_setitems(obj.items())
    locals:
      self = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      self._batch_setitems = <local> <bound method _Pickler._batch_setitems of <dill._dill.Pickler object at 0x7f17f42002b0>>
      obj = <local> {'_dataset': ChunkingIterDataPipe, '_max_batch_size': NumbersDict({'classes': 5000, 'data': 800000}), '_max_seqs': 9223372036854775807}
      obj.items = <local> <built-in method items of dict object at 0x7f18303ce5c0>
  File "/usr/lib/python3.10/pickle.py", line 998, in _Pickler._batch_setitems
    line: save(v)
    locals:
      save = <local> <bound method Pickler.save of <dill._dill.Pickler object at 0x7f17f42002b0>>
      v = <local> ChunkingIterDataPipe
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 414, in Pickler.save
    line: StockPickler.save(self, obj, save_persistent_id)
    locals:
      StockPickler = <global> <class 'pickle._Pickler'>
      StockPickler.save = <global> <function _Pickler.save at 0x7f195847d750>
      self = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      obj = <local> ChunkingIterDataPipe
      save_persistent_id = <local> True
  File "/usr/lib/python3.10/pickle.py", line 603, in _Pickler.save
    line: self.save_reduce(obj=obj, *rv)
    locals:
      self = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      self.save_reduce = <local> <bound method _Pickler.save_reduce of <dill._dill.Pickler object at 0x7f17f42002b0>>
      obj = <local> ChunkingIterDataPipe
      rv = <local> (<function __newobj__ at 0x7f1958671cf0>, (<class 'returnn.torch.data.pipeline.ChunkingIterDataPipe'>,), {'_dataset': ReturnnDatasetIterDataPipe, '_chunk_size': NumbersDict({'classes': 500, 'data': 80240}), '_chunk_step': NumbersDict({'classes': 250, 'data': 40000}), '_min_chunk_size': NumbersDic...
  File "/usr/lib/python3.10/pickle.py", line 717, in _Pickler.save_reduce
    line: save(state)
    locals:
      save = <local> <bound method Pickler.save of <dill._dill.Pickler object at 0x7f17f42002b0>>
      state = <local> {'_dataset': ReturnnDatasetIterDataPipe, '_chunk_size': NumbersDict({'classes': 500, 'data': 80240}), '_chunk_step': NumbersDict({'classes': 250, 'data': 40000}), '_min_chunk_size': NumbersDict({'classes': 1, 'data': 241})}
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 414, in Pickler.save
    line: StockPickler.save(self, obj, save_persistent_id)
    locals:
      StockPickler = <global> <class 'pickle._Pickler'>
      StockPickler.save = <global> <function _Pickler.save at 0x7f195847d750>
      self = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      obj = <local> {'_dataset': ReturnnDatasetIterDataPipe, '_chunk_size': NumbersDict({'classes': 500, 'data': 80240}), '_chunk_step': NumbersDict({'classes': 250, 'data': 40000}), '_min_chunk_size': NumbersDict({'classes': 1, 'data': 241})}
      save_persistent_id = <local> True
  File "/usr/lib/python3.10/pickle.py", line 560, in _Pickler.save
    line: f(self, obj)  # Call unbound method with explicit self
    locals:
      f = <local> <function save_module_dict at 0x7f1858c0add0>
      self = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      obj = <local> {'_dataset': ReturnnDatasetIterDataPipe, '_chunk_size': NumbersDict({'classes': 500, 'data': 80240}), '_chunk_step': NumbersDict({'classes': 250, 'data': 40000}), '_min_chunk_size': NumbersDict({'classes': 1, 'data': 241})}
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 1217, in save_module_dict
    line: StockPickler.save_dict(pickler, obj)
    locals:
      StockPickler = <global> <class 'pickle._Pickler'>
      StockPickler.save_dict = <global> <function _Pickler.save_dict at 0x7f195847dfc0>
      pickler = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      obj = <local> {'_dataset': ReturnnDatasetIterDataPipe, '_chunk_size': NumbersDict({'classes': 500, 'data': 80240}), '_chunk_step': NumbersDict({'classes': 250, 'data': 40000}), '_min_chunk_size': NumbersDict({'classes': 1, 'data': 241})}
  File "/usr/lib/python3.10/pickle.py", line 972, in _Pickler.save_dict
    line: self._batch_setitems(obj.items())
    locals:
      self = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      self._batch_setitems = <local> <bound method _Pickler._batch_setitems of <dill._dill.Pickler object at 0x7f17f42002b0>>
      obj = <local> {'_dataset': ReturnnDatasetIterDataPipe, '_chunk_size': NumbersDict({'classes': 500, 'data': 80240}), '_chunk_step': NumbersDict({'classes': 250, 'data': 40000}), '_min_chunk_size': NumbersDict({'classes': 1, 'data': 241})}
      obj.items = <local> <built-in method items of dict object at 0x7f18304f9480>
  File "/usr/lib/python3.10/pickle.py", line 998, in _Pickler._batch_setitems
    line: save(v)
    locals:
      save = <local> <bound method Pickler.save of <dill._dill.Pickler object at 0x7f17f42002b0>>
      v = <local> ReturnnDatasetIterDataPipe
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 414, in Pickler.save
    line: StockPickler.save(self, obj, save_persistent_id)
    locals:
      StockPickler = <global> <class 'pickle._Pickler'>
      StockPickler.save = <global> <function _Pickler.save at 0x7f195847d750>
      self = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      obj = <local> ReturnnDatasetIterDataPipe
      save_persistent_id = <local> True
  File "/usr/lib/python3.10/pickle.py", line 603, in _Pickler.save
    line: self.save_reduce(obj=obj, *rv)
    locals:
      self = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      self.save_reduce = <local> <bound method _Pickler.save_reduce of <dill._dill.Pickler object at 0x7f17f42002b0>>
      obj = <local> ReturnnDatasetIterDataPipe
      rv = <local> (<function __newobj__ at 0x7f1958671cf0>, (<class 'returnn.torch.data.returnn_dataset_wrapper.ReturnnDatasetIterDataPipe'>,), {'_dataset': <DistributeFilesDataset 'train' epoch=None>, '_reset_callback': <returnn.torch.data.returnn_dataset_wrapper.ReturnnDatasetResetMpSharedEpochCallback object at...
  File "/usr/lib/python3.10/pickle.py", line 717, in _Pickler.save_reduce
    line: save(state)
    locals:
      save = <local> <bound method Pickler.save of <dill._dill.Pickler object at 0x7f17f42002b0>>
      state = <local> {'_dataset': <DistributeFilesDataset 'train' epoch=None>, '_reset_callback': <returnn.torch.data.returnn_dataset_wrapper.ReturnnDatasetResetMpSharedEpochCallback object at 0x7f183941dd80>}
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 414, in Pickler.save
    line: StockPickler.save(self, obj, save_persistent_id)
    locals:
      StockPickler = <global> <class 'pickle._Pickler'>
      StockPickler.save = <global> <function _Pickler.save at 0x7f195847d750>
      self = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      obj = <local> {'_dataset': <DistributeFilesDataset 'train' epoch=None>, '_reset_callback': <returnn.torch.data.returnn_dataset_wrapper.ReturnnDatasetResetMpSharedEpochCallback object at 0x7f183941dd80>}
      save_persistent_id = <local> True
  File "/usr/lib/python3.10/pickle.py", line 560, in _Pickler.save
    line: f(self, obj)  # Call unbound method with explicit self
    locals:
      f = <local> <function save_module_dict at 0x7f1858c0add0>
      self = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      obj = <local> {'_dataset': <DistributeFilesDataset 'train' epoch=None>, '_reset_callback': <returnn.torch.data.returnn_dataset_wrapper.ReturnnDatasetResetMpSharedEpochCallback object at 0x7f183941dd80>}
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 1217, in save_module_dict
    line: StockPickler.save_dict(pickler, obj)
    locals:
      StockPickler = <global> <class 'pickle._Pickler'>
      StockPickler.save_dict = <global> <function _Pickler.save_dict at 0x7f195847dfc0>
      pickler = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      obj = <local> {'_dataset': <DistributeFilesDataset 'train' epoch=None>, '_reset_callback': <returnn.torch.data.returnn_dataset_wrapper.ReturnnDatasetResetMpSharedEpochCallback object at 0x7f183941dd80>}
  File "/usr/lib/python3.10/pickle.py", line 972, in _Pickler.save_dict
    line: self._batch_setitems(obj.items())
    locals:
      self = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      self._batch_setitems = <local> <bound method _Pickler._batch_setitems of <dill._dill.Pickler object at 0x7f17f42002b0>>
      obj = <local> {'_dataset': <DistributeFilesDataset 'train' epoch=None>, '_reset_callback': <returnn.torch.data.returnn_dataset_wrapper.ReturnnDatasetResetMpSharedEpochCallback object at 0x7f183941dd80>}
      obj.items = <local> <built-in method items of dict object at 0x7f1830410280>
  File "/usr/lib/python3.10/pickle.py", line 998, in _Pickler._batch_setitems
    line: save(v)
    locals:
      save = <local> <bound method Pickler.save of <dill._dill.Pickler object at 0x7f17f42002b0>>
      v = <local> <DistributeFilesDataset 'train' epoch=None>
  File "/usr/local/lib/python3.10/dist-packages/dill/_dill.py", line 414, in Pickler.save
    line: StockPickler.save(self, obj, save_persistent_id)
    locals:
      StockPickler = <global> <class 'pickle._Pickler'>
      StockPickler.save = <global> <function _Pickler.save at 0x7f195847d750>
      self = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      obj = <local> <DistributeFilesDataset 'train' epoch=None>
      save_persistent_id = <local> True
  File "/usr/lib/python3.10/pickle.py", line 578, in _Pickler.save
    line: rv = reduce(self.proto)
    locals:
      rv = <local> NotImplemented
      reduce = <local> <built-in method __reduce_ex__ of DistributeFilesDataset object at 0x7f18393a3700>
      self = <local> <dill._dill.Pickler object at 0x7f17f42002b0>
      self.proto = <local> 4
  File "/.../work/i6_core/tools/git/CloneGitRepositoryJob.H9Cu9IA2vYwT/output/returnn/returnn/datasets/basic.py", line 240, in Dataset.__reduce__
    line: kwargs[arg] = getattr(self, arg)
    locals:
      kwargs = <local> {'files': [....
      arg = <local> 'distrib_shard_files', len = 19
      getattr = <builtin> <built-in function getattr>
      self = <local> <DistributeFilesDataset 'train' epoch=None>
AttributeError: 'DistributeFilesDataset' object has no attribute 'distrib_shard_files'
```

**Comment by NeoLegends** [comment]
cc @michelwi
