### ISSUE TITLE
DistributeFilesDataset Sharding with PT Dataloader breaks

### ISSUE THREAD

**Issue by michelwi** [rwth-i6/returnn#1556]
When I activate `"distrib_shard_files": True` and at the same time `torch_dataloader_opts = {"num_workers": 1}` on a 2 GPU multi-GPU-training, I consistently get the error
```
DistNetworkError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:52703 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:52703 (errno: 98 - Address already in use).
```

<details>

<summary>Full Trace</summary>

```
Starting training at epoch 1, global train step 0
start epoch 1 global train step 0 with effective learning rate 1e-05 ...
start epoch 1 global train step 0 with effective learning rate 1e-05 ...
[2024-06-27 18:26:58,574] INFO: Run time: 0:02:46 CPU: 0.60% RSS: 3.13GB VMS: 63.41GB
Memory usage (cuda:1): alloc cur 809.8MB alloc peak 809.8MB reserved cur 0.9GB reserved peak 0.9GB
Memory usage (cuda:0): alloc cur 809.8MB alloc peak 809.8MB reserved cur 0.9GB reserved peak 0.9GB
[2024-06-27 18:27:03,605] INFO: Run time: 0:02:51 CPU: 0.40% RSS: 4.00GB VMS: 72.14GB
[W socket.cpp:464] [c10d] The server socket has failed to bind to [::]:52703 (errno: 98 - Address already in use).
[W socket.cpp:464] [c10d] The server socket has failed to bind to 0.0.0.0:52703 (errno: 98 - Address already in use).
[E socket.cpp:500] [c10d] The server socket has failed to listen on any local network address.
Exception ignored in: <function DistributeFilesDataset.__del__ at 0x7efddeb3a170>
Traceback (most recent call last):
  File "/nas/models/asr/am/EN/16kHz/20240625_wmichel_en_model_training/work/i6_core/tools/git/CloneGitRepositoryJob.fmS5DKDpgA6Q/output/returnn/returnn/datasets/distrib_files.py", line 223, in __del__
    for k, worker in self._workers.items():
AttributeError: 'DistributeFilesDataset' object has no attribute '_workers'
EXCEPTION
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    -- code not available --
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    line: exitcode = _main(fd, parent_sentinel)
    locals:
      exitcode = <not found>
      _main = <global> <function _main at 0x7efefdbf9a20>
      fd = <local> 71
      parent_sentinel = <local> 3
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
    line: self = reduction.pickle.load(from_parent)
    locals:
      self = <not found>
      reduction = <global> <module 'multiprocessing.reduction' from '/usr/lib/python3.10/multiprocessing/reduction.py'>
      reduction.pickle = <global> <module 'pickle' from '/usr/lib/python3.10/pickle.py'>
      reduction.pickle.load = <global> <built-in function load>
      from_parent = <local> <_io.BufferedReader name=71>
   File "/nas/models/asr/am/EN/16kHz/20240625_wmichel_en_model_training/work/i6_core/tools/git/CloneGitRepositoryJob.fmS5DKDpgA6Q/output/returnn/returnn/util/multi_proc_non_daemonic_spawn.py", line 156, in NonDaemonicSpawnProcess._reconstruct_with_pre_init_func
    line: reconstruct_func, reconstruct_args, reconstruct_state = pickle.load(buffer)
    locals:
      reconstruct_func = <not found>
      reconstruct_args = <not found>
      reconstruct_state = <not found>
      pickle = <global> <module 'pickle' from '/usr/lib/python3.10/pickle.py'>
      pickle.load = <global> <built-in function load>
      buffer = <local> <_io.BytesIO object at 0x7efee7bcbdd0>
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/datapipes/datapipe.py", line 361, in _DataPipeSerializationWrapper.__setstate__
    line: self._datapipe = pickle.loads(value)
    locals:
      self = <local> _IterDataPipeSerializationWrapper
      self._datapipe = <local> !AttributeError: '_IterDataPipeSerializationWrapper' object has no attribute '_datapipe
      pickle = <global> <module 'pickle' from '/usr/lib/python3.10/pickle.py'>
      pickle.loads = <global> <built-in function loads>
      value = <local> b"\x80\x04\x95\\\x00\x01\x00\x00\x00\x00\x00\x8c\x1breturnn.torch.data.pipeline\x94\x8c\x14BatchingIterDataPipe\x94\x93\x94)\x81\x94}\x94(\x8c\x08_dataset\x94h\x00\x8c\x14ChunkingIterDataPipe\x94\x93\x94)\x81\x94}\x94(h\x05\x8c*returnn.torch.data.returnn_dataset_wrapper\x94\x8c\x1aReturnnDatasetI..., len = 229349
  File "/nas/models/asr/am/EN/16kHz/20240625_wmichel_en_model_training/work/i6_core/tools/git/CloneGitRepositoryJob.fmS5DKDpgA6Q/output/returnn/returnn/datasets/basic.py", line 220, in Dataset._create_from_reduce
    line: ds = cls(**kwargs)
    locals:
      ds = <not found>
      cls = <local> <class 'returnn.datasets.distrib_files.DistributeFilesDataset'>
      kwargs = <local> {'files': [('/nas/data/speech/EN_US/16kHz/Deluxe/corpus/batch.1.v1/hdf-raw_wav.16kHz.split-962/Deluxe-batch.1.v1.hdf.1', '/nas/data/speech/EN_US/16kHz/Deluxe/corpus/batch.1.v1/hdf-conformer_quantized_20240503.split-962/Deluxe-batch.1.v1.hdf.1'), ('/nas/data/speech/EN_US/16kHz/Deluxe/corpus/batch...., len = 22
  File "/nas/models/asr/am/EN/16kHz/20240625_wmichel_en_model_training/work/i6_core/tools/git/CloneGitRepositoryJob.fmS5DKDpgA6Q/output/returnn/returnn/datasets/distrib_files.py", line 163, in DistributeFilesDataset.__init__
    line: self._shard_index, self._num_shards = _get_rank_and_size() if distrib_shard_files else (0, 1)
    locals:
      self = <local> <DistributeFilesDataset 'train' epoch=None>
      self._shard_index = <local> !AttributeError: 'DistributeFilesDataset' object has no attribute '_shard_index'
      self._num_shards = <local> !AttributeError: 'DistributeFilesDataset' object has no attribute '_num_shards'
      _get_rank_and_size = <global> <function _get_rank_and_size at 0x7efddeb3a680>
      distrib_shard_files = <local> True
  File "/nas/models/asr/am/EN/16kHz/20240625_wmichel_en_model_training/work/i6_core/tools/git/CloneGitRepositoryJob.fmS5DKDpgA6Q/output/returnn/returnn/datasets/distrib_files.py", line 433, in _get_rank_and_size
    line: ctx = returnn.torch.distributed.get_ctx(config=config)
    locals:
      ctx = <not found>
      returnn = <local> <module 'returnn' from '/nas/models/asr/am/EN/16kHz/20240625_wmichel_en_model_training/work/i6_core/tools/git/CloneGitRepositoryJob.fmS5DKDpgA6Q/output/returnn/returnn/__init__.py'>
      returnn.torch = <local> <module 'returnn.torch' from '/nas/models/asr/am/EN/16kHz/20240625_wmichel_en_model_training/work/i6_core/tools/git/CloneGitRepositoryJob.fmS5DKDpgA6Q/output/returnn/returnn/torch/__init__.py'>
      returnn.torch.distributed = <local> <module 'returnn.torch.distributed' from '/nas/models/asr/am/EN/16kHz/20240625_wmichel_en_model_training/work/i6_core/tools/git/CloneGitRepositoryJob.fmS5DKDpgA6Q/output/returnn/returnn/torch/distributed.py'>
      returnn.torch.distributed.get_ctx = <local> <function get_ctx at 0x7efddeb17d90>
      config = <local> <returnn.config.Config object at 0x7efee7b9ae90>
  File "/nas/models/asr/am/EN/16kHz/20240625_wmichel_en_model_training/work/i6_core/tools/git/CloneGitRepositoryJob.fmS5DKDpgA6Q/output/returnn/returnn/torch/distributed.py", line 148, in get_ctx
    line: _ctx = DistributedContext(opts)
    locals:
      _ctx = <global> None
      DistributedContext = <global> <class 'returnn.torch.distributed.DistributedContext'>
      opts = <local> {'param_sync_step': 100, 'reduce_type': 'param'}
  File "/nas/models/asr/am/EN/16kHz/20240625_wmichel_en_model_training/work/i6_core/tools/git/CloneGitRepositoryJob.fmS5DKDpgA6Q/output/returnn/returnn/torch/distributed.py", line 33, in DistributedContext.__init__
    line: dist.init_process_group(backend=self._opts.get("backend", None))
    locals:
      dist = <local> <module 'torch.distributed' from '/usr/local/lib/python3.10/dist-packages/torch/distributed/__init__.py'>
      dist.init_process_group = <local> <function init_process_group at 0x7efdfec8eb00>
      backend = <not found>
      self = <local> !AttributeError: 'DistributedContext' object has no attribute '_size'
      self._opts = <local> CollectionReadCheckCovered({'param_sync_step': 100, 'reduce_type': 'param'}, truth_value=True), len = 2
      self._opts.get = <local> <bound method CollectionReadCheckCovered.get of CollectionReadCheckCovered({'param_sync_step': 100, 'reduce_type': 'param'}, truth_value=True)>
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 75, in init_process_group
    line: return func(*args, **kwargs)
    locals:
      func = <local> <function init_process_group at 0x7efdfec8ea70>
      args = <local> ()
      kwargs = <local> {'backend': None}
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 89, in _store_based_barrier
    line: func_return = func(*args, **kwargs)
    locals:
      func_return = <not found>
      func = <local> <function init_process_group at 0x7efdfec8e9e0>
      args = <local> ()
      kwargs = <local> {'backend': None}
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1305, in init_process_group
    line: store, rank, world_size = next(rendezvous_iterator)
    locals:
      store = <local> None
      rank = <local> -1
      world_size = <local> -1
      next = <builtin> <built-in function next>
      rendezvous_iterator = <local> <generator object _env_rendezvous_handler at 0x7efddeb29540>
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/rendezvous.py", line 246, in _env_rendezvous_handler
    line: store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout, use_libuv)
    locals:
      store = <not found>
      _create_c10d_store = <global> <function _create_c10d_store at 0x7efdfee33e20>
      master_addr = <local> 'g-16.apptek.local', len = 17
      master_port = <local> 52703
      rank = <local> 0
      world_size = <local> 2
      timeout = <local> datetime.timedelta(seconds=1800)
      use_libuv = <local> False
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/rendezvous.py", line 174, in _create_c10d_store
    line: return TCPStore(
              hostname, port, world_size, start_daemon, timeout, multi_tenant=True, use_libuv=use_libuv
          )
    locals:
      TCPStore = <global> <class 'torch._C._distributed_c10d.TCPStore'>
      hostname = <local> 'g-16.apptek.local', len = 17
      port = <local> 52703
      world_size = <local> 2
      start_daemon = <local> True
      timeout = <local> datetime.timedelta(seconds=1800)
      multi_tenant = <not found>
      use_libuv = <local> False
DistNetworkError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:52703 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:52703 (errno: 98 - Address already in use).
[PID 208574, PPID 208329] Error in NonDaemonicSpawnProcess._reconstruct_with_pre_init_func: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:52703 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:52703 (errno: 98 - Address already in use).
RuntimeError: DataLoader worker (pid(s) 208574) exited unexpectedly
Unhandled exception <class 'RuntimeError'> in thread <_MainThread(MainThread, started 140379905746752)>, proc 208329.
```

</details>

If I either deactivate sharding in the dataset or set `num_workers` to 0 the error goes away.
I have also retried the failing configuration tree times to verify this was not a fluke.

**Comment by NeoLegends** [comment]
I think I know what this is

**Comment by albertz** [comment]
Two things:
```
AttributeError: 'DistributeFilesDataset' object has no attribute '_workers'
```
Because of early exception in `__init__`. But anyway, we should avoid this error by checking `hasattr` or so in `__del__`. But that's not really the main issue here.

The main issue is that we call `_get_rank_and_size` in the sub proc. Instead, this should be passed from the parent to the sub proc in serialization. We can pass some `_rank` and `_size` as args and if they are passed, use them. That should already fix it.

**Comment by NeoLegends** [comment]
>The main issue is that we call _get_rank_and_size in the sub proc. Instead, this should be passed from the parent to the sub proc in serialization. We can pass some _rank and _size as args and if they are passed, use them. That should already fix it.

~~I feel like we should rather fix the DistributedContext to properly work in and child process, no?~~

Never mind, I don't think this is feasible because torch will always try to "properly" initialize a process and make it part of the worker group, even if we just want to access some worker group metadata like the size and rank of the parent.
