### ISSUE TITLE
DeepCopyError in gradient checkpointing when using `param_variational_noise`

### ISSUE THREAD

**Issue by mmz33** [rwth-i6/returnn#1629]
Related to #1616 

Full error log can be found [here](https://gist.github.com/mmz33/0f0b895243aabf0bd6b3b970d669a52e)

Error:

```
EXCEPTION
Traceback (most recent call last):
  File "/u/zeineldeen/dev/returnn/returnn/tf/engine.py", line 665, in Runner.run
    line: fetches_dict = self._get_fetches_dict()
    locals:
      fetches_dict = <local> None
      self = <local> <returnn.tf.engine.Runner object at 0x7f3b15568190>
      self._get_fetches_dict = <local> <bound method Runner._get_fetches_dict of <returnn.tf.engine.Runner object at 0x7f3b15568190>>
  File "/u/zeineldeen/dev/returnn/returnn/tf/engine.py", line 166, in Runner._get_fetches_dict
    line: optim_op = self.engine.updater.get_optim_op(callback_on_new=callback_on_new)
    locals:
      optim_op = <local> None
      self = <local> <returnn.tf.engine.Runner object at 0x7f3b15568190>
      self.engine = <local> <returnn.tf.engine.Engine object at 0x7f3b6ef83700>
      self.engine.updater = <local> <returnn.tf.updater.Updater object at 0x7f3a4f363b80>
      self.engine.updater.get_optim_op = <local> <bound method Updater.get_optim_op of <returnn.tf.updater.Updater object at 0x7f3a4f363b80>>
      callback_on_new = <local> <function Runner._get_fetches_dict.<locals>.callback_on_new at 0x7f3a48d26e60>
  File "/u/zeineldeen/dev/returnn/returnn/tf/updater.py", line 406, in Updater.get_optim_op
    line: self.create_optim_op()
    locals:
      self = <local> <returnn.tf.updater.Updater object at 0x7f3a4f363b80>
      self.create_optim_op = <local> <bound method Updater.create_optim_op of <returnn.tf.updater.Updater object at 0x7f3a4f363b80>>
  File "/u/zeineldeen/dev/returnn/returnn/tf/updater.py", line 264, in Updater.create_optim_op
    line: prepare_gradient_checkpointing()
    locals:
      prepare_gradient_checkpointing = <local> <function prepare_gradient_checkpointing at 0x7f3a4dc6c1f0>
  File "/u/zeineldeen/dev/returnn/returnn/tf/util/gradient_checkpoint.py", line 195, in prepare_gradient_checkpointing
    line: _set_wrapped_grad_func(op_)
    locals:
      _set_wrapped_grad_func = <local> <function prepare_gradient_checkpointing.<locals>._set_wrapped_grad_func at 0x7f3a48d271c0>
      op_ = <local> <tf.Operation 'conv0/W_variational_noise/cond/add_1' type=AddV2>
  File "/u/zeineldeen/dev/returnn/returnn/tf/util/gradient_checkpoint.py", line 169, in prepare_gradient_checkpointing.<locals>._set_wrapped_grad_func
    line: _wrapped_op = _WrappedOp()
    locals:
      _wrapped_op = <not found>
      _WrappedOp = <local> <class 'returnn.tf.util.gradient_checkpoint.prepare_gradient_checkpointing.<locals>._set_wrapped_grad_func.<locals>._WrappedOp'>
  File "/u/zeineldeen/dev/returnn/returnn/tf/util/gradient_checkpoint.py", line 147, in prepare_gradient_checkpointing.<locals>._set_wrapped_grad_func.<locals>._WrappedOp.__init__
    line: self._inputs = tuple(_map_tensor(x) for x in op.inputs)
    locals:
      self = <local> <returnn.tf.util.gradient_checkpoint.prepare_gradient_checkpointing.<locals>._set_wrapped_grad_func.<locals>._WrappedOp object at 0x7f3a49246b00>
      self._inputs = <local> !AttributeError: '_WrappedOp' object has no attribute '_inputs'
      tuple = <builtin> <class 'tuple'>
      _map_tensor = <local> <function prepare_gradient_checkpointing.<locals>._map_tensor at 0x7f3a48d27130>
      x = <not found>
      op = <local> <tf.Operation 'conv0/W_variational_noise/cond/add_1' type=AddV2>
      op.inputs = <local> (<tf.Tensor 'conv0/W_variational_noise/cond/ReadVariableOp:0' shape=(3, 3, 1, 32) dtype=float32>, <tf.Tensor 'conv0/W_variational_noise/cond/add:0' shape=(3, 3, 1, 32) dtype=float32>)
  File "/u/zeineldeen/dev/returnn/returnn/tf/util/gradient_checkpoint.py", line 147, in <genexpr>
    line: self._inputs = tuple(_map_tensor(x) for x in op.inputs)
    locals:
      self = <not found>
      self._inputs = <not found>
      tuple = <builtin> <class 'tuple'>
      _map_tensor = <local> <function prepare_gradient_checkpointing.<locals>._map_tensor at 0x7f3a48d27130>
      x = <local> <tf.Tensor 'conv0/W_variational_noise/cond/ReadVariableOp:0' shape=(3, 3, 1, 32) dtype=float32>
      op = <not found>
      op.inputs = <not found>
  File "/u/zeineldeen/dev/returnn/returnn/tf/util/gradient_checkpoint.py", line 127, in prepare_gradient_checkpointing.<locals>._map_tensor
    line: x_op_copy = _copy_op(x.op)
    locals:
      x_op_copy = <not found>
      _copy_op = <local> <function prepare_gradient_checkpointing.<locals>._copy_op at 0x7f3a48d27010>
      x = <local> <tf.Tensor 'conv0/W_variational_noise/cond/ReadVariableOp:0' shape=(3, 3, 1, 32) dtype=float32>
      x.op = <local> <tf.Operation 'conv0/W_variational_noise/cond/ReadVariableOp' type=ReadVariableOp>
  File "/u/zeineldeen/dev/returnn/returnn/tf/util/gradient_checkpoint.py", line 114, in prepare_gradient_checkpointing.<locals>._copy_op
    line: _set_wrapped_grad_func(new_op)
    locals:
      _set_wrapped_grad_func = <local> <function prepare_gradient_checkpointing.<locals>._set_wrapped_grad_func at 0x7f3a48d271c0>
      new_op = <local> <tf.Operation 'conv0/W_variational_noise/cond/ReadVariableOp/Switch_1' type=Switch>
  File "/u/zeineldeen/dev/returnn/returnn/tf/util/gradient_checkpoint.py", line 169, in prepare_gradient_checkpointing.<locals>._set_wrapped_grad_func
    line: _wrapped_op = _WrappedOp()
    locals:
      _wrapped_op = <not found>
      _WrappedOp = <local> <class 'returnn.tf.util.gradient_checkpoint.prepare_gradient_checkpointing.<locals>._set_wrapped_grad_func.<locals>._WrappedOp'>
  File "/u/zeineldeen/dev/returnn/returnn/tf/util/gradient_checkpoint.py", line 147, in prepare_gradient_checkpointing.<locals>._set_wrapped_grad_func.<locals>._WrappedOp.__init__
    line: self._inputs = tuple(_map_tensor(x) for x in op.inputs)
    locals:
      self = <local> <returnn.tf.util.gradient_checkpoint.prepare_gradient_checkpointing.<locals>._set_wrapped_grad_func.<locals>._WrappedOp object at 0x7f3a49246cb0>
      self._inputs = <local> !AttributeError: '_WrappedOp' object has no attribute '_inputs'
      tuple = <builtin> <class 'tuple'>
      _map_tensor = <local> <function prepare_gradient_checkpointing.<locals>._map_tensor at 0x7f3a48d27130>
      x = <not found>
      op = <local> <tf.Operation 'conv0/W_variational_noise/cond/ReadVariableOp/Switch_1' type=Switch>
      op.inputs = <local> (<tf.Tensor 'conv0/W_variational_noise/cond/ReadVariableOp/Switch:1' shape=() dtype=resource>, <tf.Tensor 'conv0/W_variational_noise/cond/pred_id:0' shape=() dtype=bool>)
  File "/u/zeineldeen/dev/returnn/returnn/tf/util/gradient_checkpoint.py", line 147, in <genexpr>
    line: self._inputs = tuple(_map_tensor(x) for x in op.inputs)
    locals:
      self = <not found>
      self._inputs = <not found>
      tuple = <builtin> <class 'tuple'>
      _map_tensor = <local> <function prepare_gradient_checkpointing.<locals>._map_tensor at 0x7f3a48d27130>
      x = <local> <tf.Tensor 'conv0/W_variational_noise/cond/ReadVariableOp/Switch:1' shape=() dtype=resource>
      op = <not found>
      op.inputs = <not found>
  File "/u/zeineldeen/dev/returnn/returnn/tf/util/gradient_checkpoint.py", line 127, in prepare_gradient_checkpointing.<locals>._map_tensor
    line: x_op_copy = _copy_op(x.op)
    locals:
      x_op_copy = <not found>
      _copy_op = <local> <function prepare_gradient_checkpointing.<locals>._copy_op at 0x7f3a48d27010>
      x = <local> <tf.Tensor 'conv0/W_variational_noise/cond/ReadVariableOp/Switch:1' shape=() dtype=resource>
      x.op = <local> <tf.Operation 'conv0/W_variational_noise/cond/ReadVariableOp/Switch' type=Switch>
  File "/u/zeineldeen/dev/returnn/returnn/tf/util/gradient_checkpoint.py", line 92, in prepare_gradient_checkpointing.<locals>._copy_op
    line: raise _DeepCopyError(op)
    locals:
      _DeepCopyError = <local> <class 'returnn.tf.util.gradient_checkpoint.prepare_gradient_checkpointing.<locals>._DeepCopyError'>
      op = <local> <tf.Operation 'conv0/W_variational_noise/cond/ReadVariableOp/Switch' type=Switch>
_DeepCopyError: deep copy err: name: "conv0/W_variational_noise/cond/ReadVariableOp/Switch"
op: "Switch"
input: "conv0/W"
input: "conv0/W_variational_noise/cond/pred_id"
attr {
  key: "T"
  value {
    type: DT_RESOURCE
  }
}
attr {
  key: "_class"
  value {
    list {
      s: "loc:@conv0/W"
    }
  }
}
```

Returnn network config: https://gist.github.com/mmz33/840033656b97b7e6e415c9a2b46fe75a

**Comment by albertz** [comment]
What TF version?

**Comment by mmz33** [comment]
I was testing with TF 2.9. It works now. Thank you!

**Comment by albertz** [comment]
Ok good to know.

Can you say whether checkpointing actually works? I.e. there should not really be more memory consumption (or only very minor) when you enable variational noise. Is that true?

**Comment by mmz33** [comment]
I just tested it locally and stopped the process. I will let you know when i submit a train job if grad checkpointing is actually working.
