### ISSUE TITLE
Error running demo of IAM script

### ISSUE THREAD

**Issue by sanakhamekhem** [rwth-i6/returnn#20]
I attempted to run the example in the demos/mdlstm/IAM folder. Here is the terminal output when a run the go.sh file:

```
CRNN starting up, version 20171107.125510--git-ef4f6a7-dirty, pid 21149, cwd /home/scr/person/invite/chiekahm/home/sanaw/returnn/demos/mdlstm/IAM
CRNN command line options: ['config_demo']
Theano: 0.9.0 (<site-package> in /home/scr/person/invite/chiekahm/.local/lib/python2.7/site-packages/theano)
pynvml not available, memory information missing
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: Tesla K80 (CNMeM is disabled, cuDNN not available)
Device gpuX proc starting up, pid 21224
Device gpuX proc: THEANO_FLAGS = 'compiledir_format=compiledir_%(platform)s-%(processor)s-%(python_version)s-%(python_bitwidth)s--dev-gpuZ,device=gpu,floatX=float32,force_device=True'
Device train-network: Used data keys: ['classes', 'data', 'sizes']

ectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).\n/usr/bin/ld\xc2\xa0: ne peut trouver -lcudnn\ncollect2: error: ld returned 1 exit status\n")
Device proc gpuX (gpuZ) died: ProcConnectionDied('recv_bytes EOFError: ',)
Theano flags: compiledir_format=compiledir_%(platform)s-%(processor)s-%(python_version)s-%(python_bitwidth)s--dev-gpuZ,device=gpu,floatX=float32,force_device=True
EXCEPTION
Traceback (most recent call last):
  File "/home/scr/person/invite/chiekahm/home/sanaw/returnn/Device.py", line 332, in startProc
    line: self._startProc(*args, **kwargs)
    locals:
      self = <local> <Device.Device object at 0x7fbba87b1a10>
      self._startProc = <local> <bound method Device._startProc of <Device.Device object at 0x7fbba87b1a10>>
      args = <local> ('gpuZ',)
      kwargs = <local> {}
  File "/home/scr/person/invite/chiekahm/home/sanaw/returnn/Device.py", line 386, in _startProc
    line: interrupt_main()
    locals:
      interrupt_main = <global> <function interrupt_main at 0x7fbba9310500>
  File "/home/scr/person/invite/chiekahm/home/sanaw/returnn/Util.py", line 625, in interrupt_main
    line: sys.exit(1)  # And exit the thread.
    locals:
      sys = <global> <module 'sys' (built-in)>
      sys.exit = <global> <built-in function exit>
SystemExit: 1
KeyboardInterrupt
EXCEPTION
Traceback (most recent call last):
  File "../../../rnn.py", line 519, in main
    line: init(commandLineOptions=argv[1:])
    locals:
      init = <global> <function init at 0x7fbba87ac8c0>
      commandLineOptions = <not found>
      argv = <local> ['../../../rnn.py', 'config_demo'], _[0]: {len = 15}
  File "../../../rnn.py", line 335, in init
    line: devices = initDevices()
    locals:
      devices = <not found>
      initDevices = <global> <function initDevices at 0x7fbba87ac500>
  File "../../../rnn.py", line 151, in initDevices
    line: sleep(0.25)
    locals:
      sleep = <global> <built-in function sleep>
KeyboardInterrupt
Quitting
```

**Comment by albertz** [comment]
The main error, which is partly crippled in your output, is this:

    ne peut trouver -lcudnn
    collect2: error: ld returned 1 exit status

This means, it did not found cuDNN.

**Comment by pvoigtlaender** [comment]
You need to set some environment variables, so it can correctly link to cudnn.
You can try to put something like this (for your version of cudnn and your username and location of cudnn) into your ~/.bashrc (assuming that the .so files are in /home/voigtlaender/cudnn_v5/)

```
#cuddn v5.1
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/voigtlaender/cudnn_v5/
export LIBRARY_PATH=$LIBRARY_PATH:/home/voigtlaender/cudnn_v5/
export CPATH=$CPATH:/home/voigtlaender/cudnn_v5/
```

**Comment by sanakhamekhem** [comment]
Thank you for your responses, it is working now.
