### ISSUE TITLE
Device gpuX proc exception: 'tuple' object does not support item assignment

### ISSUE THREAD

**Issue by Marcovaldong** [rwth-i6/returnn#219]
@albertz 

When I run the demo of IAM, I got the current error, is there somewhere error in my environment or this code? 

```
(mdlstm) [sqdong@gpu88 IAM]$ python ../../../rnn.py config_demo 
RETURNN starting up, version 20190909.093342--git-df173de-dirty, date/time 2019-09-10-21-58-06 (UTC+0800), pid 107800, cwd /ssd4/exec/sqdong/IAM/returnn_IAM/demos/mdlstm/IAM, Python /ssd4/exec/sqdong/environments/anaconda3/envs/mdlstm/bin/python
RETURNN command line options: ['config_demo']
Hostname: gpu88.corp.yodao.com
Theano: 0.9.0 (<site-package> in /ssd4/exec/sqdong/environments/anaconda3/envs/mdlstm/lib/python2.7/site-packages/theano)
==================================================
<Config.Config instance at 0x7f9dc2c907e8>
==================================================
pynvml not available, memory information missing
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX 1080 Ti (CNMeM is enabled with initial size: 80.0% of memory, cuDNN 6021)
/ssd4/exec/sqdong/environments/anaconda3/envs/mdlstm/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py:631: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.1.
  warnings.warn(warn)
Device gpuX proc starting up, pid 107912
Device gpuX proc: THEANO_FLAGS = 'compiledir_format=compiledir_%(platform)s-%(processor)s-%(python_version)s-%(python_bitwidth)s--dev-gpuZ,device=gpu,force_device=True'
Device gpuX proc exception: 'tuple' object does not support item assignment
Unhandled exception <type 'exceptions.TypeError'> in thread <_MainThread(MainThread, started 139719755163456)>, proc 107912.

Thread current, main, <_MainThread(MainThread, started 139719755163456)>:
(Excluded thread.)

That were all threads.
EXCEPTION
Traceback (most recent call last):
  File "/ssd4/exec/sqdong/IAM/returnn_IAM/Device.py", line 882, in process
    line: self.process_inner(device, config, self.update_specs, asyncTask)
    locals:
      self = <local> <Device.Device object at 0x7f12be1ee210>
      self.process_inner = <local> <bound method Device.process_inner of <Device.Device object at 0x7f12be1ee210>>
      device = <local> 'gpuX'
      config = <local> <Config.Config instance at 0x7f12be1fb050>
      self.update_specs = <local> {'layers': [], 'block_size': 0, 'update_params': {}, 'update_rule': 'global'}
      asyncTask = <local> <TaskSystem.AsyncTask instance at 0x7f130099dfc8>
  File "/ssd4/exec/sqdong/IAM/returnn_IAM/Device.py", line 935, in process_inner
    line: self.initialize(config, update_specs=update_specs)
    locals:
      self = <local> <Device.Device object at 0x7f12be1ee210>
      self.initialize = <local> <bound method Device.initialize of <Device.Device object at 0x7f12be1ee210>>
      config = <local> <Config.Config instance at 0x7f12be1fb050>
      update_specs = <local> {'layers': [], 'block_size': 0, 'update_params': {}, 'update_rule': 'global'}
  File "/ssd4/exec/sqdong/IAM/returnn_IAM/Device.py", line 296, in initialize
    line: self.trainnet = LayerNetwork.from_config_topology(config, train_flag=True, eval_flag=False)
    locals:
      self = <local> <Device.Device object at 0x7f12be1ee210>
      self.trainnet = <local> !AttributeError: 'Device' object has no attribute 'trainnet'
      LayerNetwork = <global> <class 'Network.LayerNetwork'>
      LayerNetwork.from_config_topology = <global> <bound method type.from_config_topology of <class 'Network.LayerNetwork'>>
      config = <local> <Config.Config instance at 0x7f12be1fb050>
      train_flag = <not found>
      eval_flag = <local> False
  File "/ssd4/exec/sqdong/IAM/returnn_IAM/Network.py", line 120, in from_config_topology
    line: return cls.from_json_and_config(json_content, config, mask=mask, **kwargs)
    locals:
      cls = <local> <class 'Network.LayerNetwork'>
      cls.from_json_and_config = <local> <bound method type.from_json_and_config of <class 'Network.LayerNetwork'>>
      json_content = <local> {'mdlstm0': {'dropout': 0.25, 'from': ['conv0'], 'class': 'mdlstm', 'n_out': 30}, 'conv2': {'from': ['mdlstm1'], 'dropout': 0.25, 'pool_size': [2, 2], 'filter': [3, 3], 'n_features': 75, 'class': 'conv2'}, 'conv1': {'from': ['mdlstm0'], 'dropout': 0.25, 'pool_size': [2, 2], 'filter': [3, 3], 'n_f..., len = 13
      config = <local> <Config.Config instance at 0x7f12be1fb050>
      mask = <local> None
      kwargs = <local> {'train_flag': True, 'eval_flag': False}
  File "/ssd4/exec/sqdong/IAM/returnn_IAM/Network.py", line 175, in from_json_and_config
    line: network = cls.from_json(json_content, **dict_joined(kwargs, cls.init_args_from_config(config)))
    locals:
      network = <not found>
      cls = <local> <class 'Network.LayerNetwork'>
      cls.from_json = <local> <bound method type.from_json of <class 'Network.LayerNetwork'>>
      json_content = <local> {'mdlstm0': {'dropout': 0.25, 'from': ['conv0'], 'class': 'mdlstm', 'n_out': 30}, 'conv2': {'from': ['mdlstm1'], 'dropout': 0.25, 'pool_size': [2, 2], 'filter': [3, 3], 'n_features': 75, 'class': 'conv2'}, 'conv1': {'from': ['mdlstm0'], 'dropout': 0.25, 'pool_size': [2, 2], 'filter': [3, 3], 'n_f..., len = 13
      dict_joined = <global> <function dict_joined at 0x7f12be360488>
      kwargs = <local> {'train_flag': True, 'mask': None, 'eval_flag': False}
      cls.init_args_from_config = <local> <bound method type.init_args_from_config of <class 'Network.LayerNetwork'>>
      config = <local> <Config.Config instance at 0x7f12be1fb050>
  File "/ssd4/exec/sqdong/IAM/returnn_IAM/Network.py", line 393, in from_json
    line: traverse(json_content, layer_name, trg, index)
    locals:
      traverse = <local> <function traverse at 0x7f12bbb28de8>
      json_content = <local> {'mdlstm0': {'dropout': 0.25, 'from': ['conv0'], 'class': 'mdlstm', 'n_out': 30}, 'conv2': {'from': ['mdlstm1'], 'dropout': 0.25, 'pool_size': [2, 2], 'filter': [3, 3], 'n_features': 75, 'class': 'conv2'}, 'conv1': {'from': ['mdlstm0'], 'dropout': 0.25, 'pool_size': [2, 2], 'filter': [3, 3], 'n_f..., len = 13
      layer_name = <local> 'output', len = 6
      trg = <local> 'classes', len = 7
      index = <local> j_classes
  File "/ssd4/exec/sqdong/IAM/returnn_IAM/Network.py", line 373, in traverse
    line: return network.make_classifier(**params)
    locals:
      network = <local> <Network.LayerNetwork object at 0x7f12bbb1e810>
      network.make_classifier = <local> <bound method LayerNetwork.make_classifier of <Network.LayerNetwork object at 0x7f12bbb1e810>>
      params = <local> {'loss': 'ctc', 'network': <Network.LayerNetwork object at 0x7f12bbb1e810>, 'index': i, 'dropout': 0.25, 'mask': None, 'sources': [<<class 'NetworkTwoDLayer.TwoDLSTMLayer'> class:mdlstm name:mdlstm4>], 'y_in': {'classes': y_classes, 'data': x, 'sizes': y_sizes}, 'target': 'classes', 'train_flag':..., len = 11
  File "/ssd4/exec/sqdong/IAM/returnn_IAM/Network.py", line 573, in make_classifier
    line: self.n_out[target][0] += 1
    locals:
      self = <local> <Network.LayerNetwork object at 0x7f12bbb1e810>
      self.n_out = <local> {'classes': (79, 1), 'data': (1, 2), 'sizes': (2, 1)}
      target = <local> 'classes', len = 7
TypeError: 'tuple' object does not support item assignment
Device proc gpuX (gpuZ) died: ProcConnectionDied('recv_bytes EOFError: ',)
Theano flags: compiledir_format=compiledir_%(platform)s-%(processor)s-%(python_version)s-%(python_bitwidth)s--dev-gpuZ,device=gpu,force_device=True
EXCEPTION
Traceback (most recent call last):
  File "/ssd4/exec/sqdong/IAM/returnn_IAM/Device.py", line 184, in startProc
    line: self._startProc(*args, **kwargs)
    locals:
      self = <local> <Device.Device object at 0x7f9d7cbb5cd0>
      self._startProc = <local> <bound method Device._startProc of <Device.Device object at 0x7f9d7cbb5cd0>>
      args = <local> ('gpuZ',)
      kwargs = <local> {}
  File "/ssd4/exec/sqdong/IAM/returnn_IAM/Device.py", line 238, in _startProc
    line: interrupt_main()
    locals:
      interrupt_main = <global> <function interrupt_main at 0x7f9dc2c2e320>
  File "/ssd4/exec/sqdong/IAM/returnn_IAM/Util.py", line 1171, in interrupt_main
    line: sys.exit(1)  # And exit the thread.
    locals:
      sys = <global> <module 'sys' (built-in)>
      sys.exit = <global> <built-in function exit>
SystemExit: 1
KeyboardInterrupt
EXCEPTION
Traceback (most recent call last):
  File "../../../rnn.py", line 645, in main
    line: init(command_line_options=argv[1:])
    locals:
      init = <global> <function init at 0x7f9dc2c657d0>
      command_line_options = <not found>
      argv = <local> ['../../../rnn.py', 'config_demo'], _[0]: {len = 15}
  File "../../../rnn.py", line 402, in init
    line: devices = init_theano_devices()
    locals:
      devices = <not found>
      init_theano_devices = <global> <function init_theano_devices at 0x7f9dc2c65410>
  File "../../../rnn.py", line 169, in init_theano_devices
    line: time.sleep(0.25)
    locals:
      time = <global> <module 'time' from '/ssd4/exec/sqdong/environments/anaconda3/envs/mdlstm/lib/python2.7/lib-dynload/time.so'>
      time.sleep = <global> <built-in function sleep>
KeyboardInterrupt
Quitting
```

**Comment by albertz** [comment]
@Marcovaldong Why did you tag me? I'm not so much involved in that experiment. @pvoigtlaender is the author. The problem might also be due to some recent changes by @doetsch @doetsch-apptek .

**Comment by doetsch** [comment]
This is a very old setup which uses the old, deprecated Theano backend. Maybe try an older commit, e.g. 015e1993f2edfa912f4d0e0b89ea13121d6dd860 or some other commit around that time. There are currently no plans to support this setup in the new backend.

**Comment by Marcovaldong** [comment]
@doetsch  My current variable is CentOS7 + CUDA8.0+CuDNN 6.0.21 + Theano0.9 + pygpu0.6.5, is that suitable for mdlstm of IAM experiment?

**Comment by Marcovaldong** [comment]
@doetsch  I downgraded cuDNN to v5.1.10, then I can run the script successfully.
