### ISSUE TITLE
Distributed Training- InvalidArgumentError: Cannot assign a device for operation GetDeviceAttr_2: node GetDeviceAttr_2

### ISSUE THREAD

**Issue by manish-kumar-garg** [rwth-i6/returnn#263]
I am trying to run training using multiple GPUs on single machine.
I have installed tensorflow==1.15 and horovod.

Below are the lines added to librispeech full setup config.
```
use_horovod = True
horovod_reduce_type = "grad"
horovod_scale_lr = False
```
Below steps are followed after this.
```
export CUDA_VISIBLE_DEVICES=0,1
mpirun -np 2 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x HOROVOD_TIMELINE -x DEBUG -mca pml ob1 -mca btl ^openib python3 returnn/rnn.py returnn-distribued.config ++use_horovod 1

```
Below is the full stdout
```
Horovod: Hostname ip-10-1-21-241, pid 127361, using GPU 0.
Horovod: Hostname ip-10-1-21-241, pid 127362, using GPU 1.
Horovod: Reduce type: grad
Setup TF inter and intra global thread pools, num_threads None, session opts {'gpu_options': {'visible_device_list': '1'}, 'log_device_placement': False, 'device_count': {'GPU': 0}}.
Setup TF inter and intra global thread pools, num_threads None, session opts {'gpu_options': {'visible_device_list': '0'}, 'log_device_placement': False, 'device_count': {'GPU': 0}}.
CUDA_VISIBLE_DEVICES is set to '0,1'.
CUDA_VISIBLE_DEVICES is set to '0,1'.
TF session gpu_options.visible_device_list is set to '1'.
Collecting TensorFlow device list...
TF session gpu_options.visible_device_list is set to '0'.
Collecting TensorFlow device list...
OpCodeCompiler call: /usr/local/cuda-10.0/bin/nvcc -shared -O2 -std=c++11 -I /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/include -I /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/include/external/nsync/public -I /usr/local/cuda-10.0/include -L /usr/local/cuda-10.0/lib64 -x cu -v -DGOOGLE_CUDA=1 -Xcompiler -fPIC -Xcompiler -v -D_GLIBCXX_USE_CXX11_ABI=0 -DNDEBUG=1 -g /tmp/ubuntu/returnn_tf_cache/ops/GetDeviceAttr/7b755c0064/GetDeviceAttr.cc -o /tmp/ubuntu/returnn_tf_cache/ops/GetDeviceAttr/7b755c0064/GetDeviceAttr.so -L/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core -l:libtensorflow_framework.so.1
Waiting for lock-file: /tmp/ubuntu/returnn_tf_cache/ops/GetDeviceAttr/7b755c0064/lock_file
Unhandled exception <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'> in thread <_MainThread(MainThread, started 140588158043968)>, proc 127362.

Thread current, main, <_MainThread(MainThread, started 140588158043968)>:
(Excluded thread.)

That were all threads.
EXCEPTION
Traceback (most recent call last):
  File "returnn/rnn.py", line 654, in <module>
    line: main(sys.argv)
    locals:
      main = <local> <function main at 0x7fdd316ea1e0>
      sys = <local> <module 'sys' (built-in)>
      sys.argv = <local> ['returnn/rnn.py', 'returnn-distributed.config'], _[0]: {len = 14}
  File "returnn/rnn.py", line 641, in main
    line: init(command_line_options=argv[1:])
    locals:
      init = <global> <function init at 0x7fdd316e2ea0>
      command_line_options = <not found>
      argv = <local> ['returnn/rnn.py', 'returnn-distributed.config'], _[0]: {len = 14}
  File "returnn/rnn.py", line 390, in init
    line: init_backend_engine()
    locals:
      init_backend_engine = <global> <function init_backend_engine at 0x7fdd316e2e18>
  File "returnn/rnn.py", line 366, in init_backend_engine
    line: print_available_devices(tf_session_opts=tf_session_opts, file=log.v2)
    locals:
      print_available_devices = <local> <function print_available_devices at 0x7fdc9245e598>
      tf_session_opts = <local> {'gpu_options': {'visible_device_list': '1'}}
      file = <not found>
      log = <global> <Log.Log object at 0x7fdce4d04128>
      log.v2 = <global> <Log.Stream object at 0x7fdc92452dd8>
  File "/home/ubuntu/rwth-i6/returnn-experiments/2018-asr-attention/librispeech/full-setup-attention/returnn/TFUtil.py", line 3452, in print_available_devices
    line: devs = get_tf_list_local_devices(tf_session_opts=tf_session_opts)
    locals:
      devs = <not found>
      get_tf_list_local_devices = <global> <function get_tf_list_local_devices at 0x7fdc9245e268>
      tf_session_opts = <local> {'gpu_options': {'visible_device_list': '1'}}
  File "/home/ubuntu/rwth-i6/returnn-experiments/2018-asr-attention/librispeech/full-setup-attention/returnn/TFUtil.py", line 3409, in get_tf_list_local_devices
    line: dev.set_physical_device_desc(session=session)
    locals:
      dev = <local> <_DeviceAttributes name: '/job:localhost/replica:0/task:0/device:XLA_GPU:1', device_type: 'XLA_GPU', memory_limit_bytes: 17179869184, physical_device_desc: None>
      dev.set_physical_device_desc = <local> <bound method _DeviceAttributes.set_physical_device_desc of <_DeviceAttributes name: '/job:localhost/replica:0/task:0/device:XLA_GPU:1', device_type: 'XLA_GPU', memory_limit_bytes: 17179869184, physical_device_desc: None>>
      session = <local> <tensorflow.python.client.session.Session object at 0x7fdc923fc940>
  File "/home/ubuntu/rwth-i6/returnn-experiments/2018-asr-attention/librispeech/full-setup-attention/returnn/TFUtil.py", line 3359, in set_physical_device_desc
    line: physical_device_desc = session.run(get_device_attr(self.name))
    locals:
      physical_device_desc = <not found>
      session = <local> <tensorflow.python.client.session.Session object at 0x7fdc923fc940>
      session.run = <local> <bound method BaseSession.run of <tensorflow.python.client.session.Session object at 0x7fdc923fc940>>
      get_device_attr = <global> <function get_device_attr at 0x7fdc9246b400>
      self = <local> <_DeviceAttributes name: '/job:localhost/replica:0/task:0/device:XLA_GPU:1', device_type: 'XLA_GPU', memory_limit_bytes: 17179869184, physical_device_desc: None>
      self.name = <local> '/job:localhost/replica:0/task:0/device:XLA_GPU:1', len = 48
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    line: result = self._run(None, fetches, feed_dict, options_ptr,
                             run_metadata_ptr)
    locals:
      result = <not found>
      self = <local> <tensorflow.python.client.session.Session object at 0x7fdc923fc940>
      self._run = <local> <bound method BaseSession._run of <tensorflow.python.client.session.Session object at 0x7fdc923fc940>>
      fetches = <local> <tf.Tensor 'GetDeviceAttr_2:0' shape=() dtype=string>
      feed_dict = <local> None
      options_ptr = <local> None
      run_metadata_ptr = <local> None
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    line: results = self._do_run(handle, final_targets, final_fetches,
                                 feed_dict_tensor, options, run_metadata)
    locals:
      results = <not found>
      self = <local> <tensorflow.python.client.session.Session object at 0x7fdc923fc940>
      self._do_run = <local> <bound method BaseSession._do_run of <tensorflow.python.client.session.Session object at 0x7fdc923fc940>>
      handle = <local> None
      final_targets = <local> []
      final_fetches = <local> [<tf.Tensor 'GetDeviceAttr_2:0' shape=() dtype=string>]
      feed_dict_tensor = <local> ObjectIdentityDictionary({}), len = 0
      options = <local> None
      run_metadata = <local> None
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    line: return self._do_call(_run_fn, feeds, fetches, targets, options,
                               run_metadata)
    locals:
      self = <local> <tensorflow.python.client.session.Session object at 0x7fdc923fc940>
      self._do_call = <local> <bound method BaseSession._do_call of <tensorflow.python.client.session.Session object at 0x7fdc923fc940>>
      _run_fn = <local> <function BaseSession._do_run.<locals>._run_fn at 0x7fdc9246c9d8>
      feeds = <local> {}
      fetches = <local> [<tensorflow.python.pywrap_tensorflow_internal.TF_Output; proxy of <Swig Object of type 'TF_Output *' at 0x7fdc92431c30> >]
      targets = <local> []
      options = <local> None
      run_metadata = <local> None
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    line: raise type(e)(node_def, op, message)
    locals:
      type = <builtin> <class 'type'>
      e = <not found>
      node_def = <local> None
      op = <local> None
      message = <local> 'Cannot assign a device for operation GetDeviceAttr_2: node GetDeviceAttr_2 (defined at /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748)  was explicitly assigned to /job:localhost/replica:0/task:0/device:GPU:1 but available devic..., len = 581
InvalidArgumentError: Cannot assign a device for operation GetDeviceAttr_2: node GetDeviceAttr_2 (defined at /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748)  was explicitly assigned to /job:localhost/replica:0/task:0/device:GPU:1 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:GPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:1 ]. Make sure the device specification refers to a valid device.
	 [[GetDeviceAttr_2]]
OpCodeCompiler call: /usr/local/cuda-10.0/bin/nvcc -shared -O2 -std=c++11 -I /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/include -I /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/include/external/nsync/public -I /usr/local/cuda-10.0/include -L /usr/local/cuda-10.0/lib64 -x cu -v -DGOOGLE_CUDA=1 -Xcompiler -fPIC -Xcompiler -v -D_GLIBCXX_USE_CXX11_ABI=0 -DNDEBUG=1 -g /tmp/ubuntu/returnn_tf_cache/ops/GetDeviceAttr/7b755c0064/GetDeviceAttr.cc -o /tmp/ubuntu/returnn_tf_cache/ops/GetDeviceAttr/7b755c0064/GetDeviceAttr.so -L/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core -l:libtensorflow_framework.so.1
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[61158,1],1]
  Exit code:    1
--------------------------------------------------------------------------

```

**Comment by albertz** [comment]
@pavelgolik this looks related to what you reported before, right? It's still not fixed?

**Comment by albertz** [comment]
The issue reported [here](https://github.com/rwth-i6/returnn-experiments/issues/28) looks also related.

**Comment by manish-kumar-garg** [comment]
the workaround works. But after that, the program hangs at below line.and doesn't proceed. 
Stdout here

**Comment by albertz** [comment]
You can send the process SIGUSR1 and it will print its current stack trace. That would be helpful to know where it hangs. Also, are you really sure it hangs forever? Maybe it just takes very long there.

**Comment by manish-kumar-garg** [comment]
I waited for more than half an hour.
stacktrace after sending SIGUSR1 :

```
mpirun: Forwarding signal 10 to job                                                                                                                                                                                                                                                
Current thread 0x00007f2b8b90d740 (most recent call first):                                                                                                                                                                                                                        
  File "/home/ubuntu/anaCurrent thread 0x00007f0adb130740 (most recent call first):                                                                                                                                                                                                
  File "/home/ubuntu/anaconda3/envconda3/envs/tensorflow_p36/lib/python3.6s/tensorflow_p36/lib/python3.6/site-packages/tensorf/site-packages/tensorflow_core/python/clilow_core/python/client/session.pent/session.py", line 1443 in _call_tf_y", line 1443 in _call_tf_sessionrun 
  File "/home/ubuntsessionrun                                                                                                                                                                                                                                                      
  File "/home/ubuntu/anaconda3/envu/anaconda3/envs/tensorflow_ps/tensorflow_p36/lib/python3.636/lib/python3.6/site-packages/tensorflow_core/pytho/site-packages/tensorflow_core/python/client/sessionn/client/session.py", line 1350 in _run_f.py", line 1350 in _run_fn           
  File "/home/ubuntun                                                                                                                                                                                                                                                              
  File "/home/ubuntu/anaconda3/envs/tenso/anaconda3/envs/tensorflow_p36/lib/python3.rflow_p36/lib/python3.6/site-package6/site-packages/tensorflow_core/s/tensorflow_core/python/clientpython/client/session.py", line 1365 in _do_ca/session.py", line 1365 in _do_call           
  File "/homell                                                                                                                                                                                                                                                                    
  File "/home/ubuntu/anacond/ubuntu/anaconda3/envs/ta3/envs/tensorflow_p36/ensorflow_p36/lib/pytholib/python3.6/site-packn3.6/site-packages/tensorflowages/tensorflow_core/python/_core/python/client/sessclient/session.py", line 1359 in _doion.py", line 1359 in _do_run
  File "/home/ub_run                                                                                                                                           
  File "/home/ubuntu/anaconda3/envs/tensoruntu/anaconda3/envs/tensorflow_p36/lib/pythflow_p36/lib/python3.6/site-on3.6/site-packages/tensorfpackages/tensorflow_core/pythlow_core/python/client/session/client/session.py", line 1180 in _ron.py", line 1180 in _run
  File "/home/ubuntun                                                                                                                                                                 
  File "/home/ubuntu/anacondau/anaconda3/envs/tens3/envs/tensorflow_p36/orflow_p36/lib/python3.6/site-packages/telib/python3.6/site-packages/tensorflow_corensorflow_core/python/client/s/python/client/session.py", line ession.py", line 956 in run
  File "/home/ubuntu956 in run                                                                                                                                                                                                                                                     
  File "/home/ubuntu/rwth-i6/return/rwth-i6/returnn-experiments/2018n-experiments/2018-asr-attenti-asr-attention/librispeech/fullon/librispeech/full-setup-attent-setup-attention/returnn/TFion/returnn/TFEngine.py", line Engine.py", line 1091 in _init_netw1091 in _init_networ$
  File "/home/uork                                                                                                                                                                                                                                                                 
  File "/home/ubuntu/rwth-i6/returnn-experiments/2018-asr-attention/librispebuntu/rwth-i6/returnn-experiments/2018-asr-attention/librispeech/full-sech/full-setup-attentionetup-attention/returnn//returnn/TFEngine.py", line 934 in iniTFEngine.py", line 934 in init_networkt_ne$work_from_config                                                                                                                                                                                                                                                                   
_from_config                                                                                                                                                                                                                                                                       
  File "/home/  File "/home/ubuntu/rwth-i6/returnubuntu/rwth-i6/returnn-expern-experiments/2018-asiments/2018-asr-attenr-attention/librispeech/full-setuption/librispeech/full-setup-attention/retur-attention/returnn/TFEngine.py", line 891 in init_tnn/TFEngine.py", line 891 i$ init_train_from_confrain_from_config                                                                                                                                                                                                                                              
  File "returnn/rnn.py"ig                                                                                                                                                                                                                                                          
  File "returnn/rnn.py", line 451 in execute, line 451 in execute_main_task                                                                                                           
  File "retu_main_task                                                                                                                                                                
  File "returnn/rnn/rnn.py", line 642 in main                                                                                                                                                                                                                  
rnn.py", line 642 in main                                                                                                                                              
  File "returnn/  File "returnn/rnn.py", line 654 in <module>                                                                                                                              
rnn.py", line 654 in <module>                                                          
```

**Comment by manish-kumar-garg** [comment]
@albertz Any input on this. How to fix?

**Comment by albertz** [comment]
The stacktrace is a bit scrambled. Can you try to get it again? From what I can partly see there, it hangs probably here:
```
      import horovod.tensorflow as hvd
      bcast_op = tf.group(*[
        tf.assign(var, hvd.broadcast(var, root_rank=0))
        for var in self.network.get_params_list() + self.network.get_auxiliary_params()])
      self.tf_session.run(bcast_op)   # <------ here
```
Also, which process is that exactly? There should be 2 processes, one for each GPU (and you see the PID right in the beginning). What is the state of the other process?

**Comment by Ore-an** [comment]
I've also encountered the first part of the problem, 'Cannot assign a device for operation GetDeviceAttr'. From what I gather, it's because no XLA kernel exists for that specific operation. You could use `tf_session_opts = {'allow_soft_placement': True}` in the config instead of the workaround, but I don't know how this affects how ReturNN operates. After setting that option or using the workaround, it runs fine for me without hanging during initialization, so I don't have anything to add to the second problem that popped up.

**Comment by albertz** [comment]
Commit 5f42db8472945 might have fixed that. I'm closing this now. Please reopen and report if there are further problems.
