### ISSUE TITLE
Tf 1.15, logger function getting two arguments (0 or 1 allowed)

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/returnn#271]
I set up my own virtualenv with a selfcompiled version of tensorflow (which was working in other venvs). When starting tensorflow and calling tf.Session the _logger function threw an error.

**Comment by Atticus1806** [comment]
Was able to fix the issue through reinstalling the whole venv, aparently when setting up the venv there were problems.

**Comment by albertz** [comment]
What exactly was the error? Please post it here.

**Comment by Atticus1806** [comment]
TypeError: _logger_find_caller() takes from 0 to 1 positional arguments but 2 were given

Unfortunatly, since it is fixed now and I am already rerunning the experiments I cannot restore more of the stack trace.

**Comment by albertz** [comment]
Ok, that's unfortunate. It would have been good to have the stack trace here.

**Comment by Filco306** [comment]
Perhaps this can help? 

```bash
Traceback (most recent call last):
  File "paraphraser/inference.py", line 142, in <module>
    main()
  File "paraphraser/inference.py", line 131, in main
    paraphraser = Paraphraser(args.checkpoint)
  File "paraphraser/inference.py", line 25, in __init__
    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.5)
  File "/Users/filipcornell/.venvs/text-augmentation-venv/lib/python3.8/site-packages/tensorflow/python/util/deprecation_wrapper.py", line 117, in __getattr__
    logging.warning(
  File "/Users/filipcornell/.venvs/text-augmentation-venv/lib/python3.8/site-packages/tensorflow/python/platform/tf_logging.py", line 166, in warning
    get_logger().warning(msg, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1454, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1573, in _log
    fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
TypeError: _logger_find_caller() takes from 0 to 1 positional arguments but 2 were given
```

I am trying to reproduce results from [this paper]() but run into the same issue. I installed TF 1.14.0 through `pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.14.0-py3-none-any.whl`; when I do `pip freeze` I get `tensorflow @ https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.14.0-py3-none-any.whl` for tensorflow.

**Comment by JackTemaki** [comment]
You are using Python 3.8 with TF1.14, but this is not supported. Check [this](https://www.tensorflow.org/install/source#cpu) list to see which Tensorflow version is compatible to which Python or CUDA version.
