### ISSUE TITLE
Crash when trying to get context for Horovod

### ISSUE THREAD

**Issue by vieting** [rwth-i6/returnn#320]
With the recent changes for Horovod, a very basic config crashed for me. Not sure if there would be an easy fix in the config or we should adapt the code somewhere. As a temporary fix, I used `config = get_global_config(raise_exception=False)` in `get_ctx()` in `TFHorovod.py` and returned `None` if the global config is `None`. But I guess it would be good if you check this and comment about what you think would be most useful here.

```
Traceback (most recent call last):
  File "/work/asr4/vieting/programs/returnn/dev/20200605/returnn/rnn.py", line 651, in <module>
    main(sys.argv)
  File "/work/asr4/vieting/programs/returnn/dev/20200605/returnn/rnn.py", line 639, in main
    execute_main_task()
  File "/work/asr4/vieting/programs/returnn/dev/20200605/returnn/rnn.py", line 449, in execute_main_task
    engine.train()
  File "/work/asr4/vieting/programs/returnn/dev/20200605/returnn/TFEngine.py", line 1430, in train
    self.train_epoch()
  File "/work/asr4/vieting/programs/returnn/dev/20200605/returnn/TFEngine.py", line 1537, in train_epoch
    train=self.network.layers_desc.get("#trainable", True))
  File "/work/asr4/vieting/programs/returnn/dev/20200605/returnn/TFEngine.py", line 81, in __init__
    self.data_provider = self.engine._get_data_provider(dataset_name=dataset_name, dataset=dataset, batches=batches)
  File "/work/asr4/vieting/programs/returnn/dev/20200605/returnn/TFEngine.py", line 1985, in _get_data_provider
    if TFHorovod.get_ctx() and TFHorovod.get_ctx().is_dataset_distribution_shard():
  File "/work/asr4/vieting/programs/returnn/dev/20200605/returnn/TFHorovod.py", line 165, in get_ctx
    config = get_global_config()
  File "/work/asr4/vieting/programs/returnn/dev/20200605/returnn/Config.py", line 547, in get_global_config
    raise Exception("No global config found.")
Exception: No global config found.
```

**Comment by albertz** [comment]
Can you maybe debug a bit why `get_global_config()` does not work in this case? This is somewhat strange. Usually that should work.

**Comment by vieting** [comment]
It seems to be about the python version. I got the error using a virtual environment with python 3.6.1. However, using Eugen's python 3.6.1 which I used to create the environment, the error does not occur and also better_exchook is used. Any ideas what's going wrong?

**Comment by albertz** [comment]
But did you debug it? You could step through the code. You could throw some dummy exception somewhere to just see and understand why better_exchook does not work. You could also just check and step through the `get_global_config` code and see why it does not work.

**Comment by vieting** [comment]
Somehow I cannot reproduce the error and therefore close the issue. Sorry about that!
