### ISSUE TITLE
demos/demo-tf-att-copy.config outdated and not working

### ISSUE THREAD

**Issue by mattiadg** [rwth-i6/returnn#339]
When running `python3 rnn.py demos/demo-tf-att-copy.config` I get the following error. It seems a problem in handling the recursion, I was wondering if it is due to the absence of an initial state for `dt_in`. Or, if the attention layer is producing an output of a wrong shape (I think that a dimension is missing).
Then, I would also change `combine_dims` with `merge_dims` in `att_comb` as it is the current recommended practice.

```
<_SubnetworkRecCell of None>: exception constructing template network (for deps and data shapes)
Most recent construction stack:
<_TemplateLayer 'decoder/output' uninitialized, construction stack None>, kwargs:
{'L2': 0.01,
 'activation': 'tanh',
 'n_out': 20,
 'name': 'output',
 'network': <TFNetwork 'root/decoder:rec-subnet' parent_net=<TFNetwork 'root' train=<tf.Tensor 'globals/train_flag:0' shape=() dtype=bool>> train=<tf.Tensor 'globals/train_fla
g:0' shape=() dtype=bool>>,
 'sources': [<_TemplateLayer 'decoder/att_comb' uninitialized, construction stack 'output'>]}
<_TemplateLayer 'decoder/att_comb' uninitialized, construction stack 'output'>, kwargs:
{'axes': 'non_spatial',
 'name': 'att_comb',
 'network': <TFNetwork 'root/decoder:rec-subnet' parent_net=<TFNetwork 'root' train=<tf.Tensor 'globals/train_flag:0' shape=() dtype=bool>> train=<tf.Tensor 'globals/train_fla
g:0' shape=() dtype=bool>>,
 'sources': [<_TemplateLayer(GaussWindowAttentionLayer)(:template:gauss_window_attention) 'decoder/att' out_type=Data(shape=(5, 20), time_dim_axis=None, batch_shape_meta=[B,5,
F|20]) (construction stack 'att_comb')>]}
Template network so far:
{'att': <_TemplateLayer(GaussWindowAttentionLayer)(:template:gauss_window_attention) 'decoder/att' out_type=Data(shape=(5, 20), time_dim_axis=None, batch_shape_meta=[B,5,F|20]
) (construction stack 'att_comb')>,
 'att_comb': <_TemplateLayer 'decoder/att_comb' uninitialized, construction stack 'output'>,
 'dt': <_TemplateLayer 'decoder/dt' uninitialized, construction stack 't'>,
 'dt_in': <_TemplateLayer 'decoder/dt_in' uninitialized, construction stack 'dt'>,
 'output': <_TemplateLayer 'decoder/output' uninitialized, construction stack None>,
 't': <_TemplateLayer(CombineLayer)(:template:combine) 'decoder/t' out_type=Data(shape=(1,), time_dim_axis=None, batch_shape_meta=[B,F|1]) (construction stack 'att')>}
Collected (unique) exceptions during template construction:
(Note that many of these can be ignored, or are expected.)
EXCEPTION
NetworkConstructionDependencyLoopException: Error: There is a dependency loop on layer 't'.
Construction stack (most recent first):
  t
  att
  att_comb
  output

EXCEPTION
CannotHandleUndefinedSourcesException: 'dt_in': cannot handle undefined sources without defined out_type.
{'L2': 0.01,
 'activation': 'tanh',
 'loss': None,
 'n_out': 20,
 'network': <TFNetwork 'root/decoder:rec-subnet' parent_net=<TFNetwork 'root' train=<tf.Tensor 'globals/train_flag:0' shape=() dtype=bool>> train=<tf.Tensor 'globals/train_flag:0' shape=() dtype=bool>>,
 'size_target': None,
 'sources': [None, None, None],
 'target': None}

EXCEPTION
Traceback (most recent call last):
  File "/home/mdigangi/bin/returnn/returnn/tf/layers/rec.py", line 1239, in __call__
    line: self.net.construct_layer(
net_dict=self.net_dict, name=name,
            get_layer=get_layer, add_layer=get_layer.add_templated_layer)
    locals:
      self = <local> <_SubnetworkRecCell of None>
      self.net = <local> <TFNetwork 'root/decoder:rec-subnet' parent_net=<TFNetwork 'root' train=<tf.Tensor 'globals/train_flag:0' shape=() dtype=bool>> train=<tf.Tensor 'globals/train_flag:0' shape=() dtype=bool>>
      self.net.construct_layer = <local> <bound method TFNetwork.construct_layer of <TFNetwork 'root/decoder:rec-subnet' parent_net=<TFNetwork 'root' train=<tf.Tensor 'globals/train_flag:0' shape=() dtype=bool>> train=<tf.Tensor 'globals/train_flag:0' shape=() dtype=bool>>>
      net_dict = <not found>
      self.net_dict = <local> {'output': {'activation': 'tanh', 'L2': 0.01, 'n_out': 20, 'from': ['att_comb'], 'class': 'linear'}, 'dt_in': {'activation': 'tanh', 'L2': 0.01, 'n_out': 20, 'from': ['prev:output', 'prev:att_comb', 'prev:dt'], 'class': 'linear'}, 't': {'L2': 0.01, 'kind': 'add', 'from': ['prev:t', 'dt'], 'n_out'..., len = 6
      name = <local> 'att_comb', len = 8
      get_layer = <local> <RecLayer construct template GetLayer>(safe False, allow_construct_in_call_nrs None, allow_uninitialized_template False, count 1, parents 'output/att_comb')
      add_layer = <not found>
      get_layer.add_templated_layer = <local> <bound method _SubnetworkRecCell._construct_template.<locals>.GetLayer.add_templated_layer of <RecLayer construct template GetLayer>(safe False, allow_construct_in_call_nrs None, allow_uninitialized_template False, count 1, parents 'output/att_comb')>
  File "/home/mdigangi/bin/returnn/returnn/tf/network.py", line 672, in construct_layer
    line: return add_layer(name=name, layer_class=layer_class, **layer_desc)
    locals:
      add_layer = <local> <bound method _SubnetworkRecCell._construct_template.<locals>.GetLayer.add_templated_layer of <RecLayer construct template GetLayer>(safe False, allow_construct_in_call_nrs None, allow_uninitialized_template False, count 1, parents 'output/att_comb')>
      name = <local> 'att_comb', len = 8
      layer_class = <local> <class 'returnn.tf.layers.basic.CombineDimsLayer'>
      layer_desc = <local> {'axes': 'non_spatial', 'sources': [<_TemplateLayer(GaussWindowAttentionLayer)(:template:gauss_window_attention) 'decoder/att' out_type=Data(shape=(5, 20), time_dim_axis=None, batch_shape_meta=[B,5,F|20]) (construction stack 'att_comb')>]}
  File "/home/mdigangi/bin/returnn/returnn/tf/layers/rec.py", line 1119, in add_templated_layer
    line: output = layer_class.get_out_data_from_opts(**layer_desc)
    locals:
      output = <not found>
      layer_class = <local> <class 'returnn.tf.layers.basic.CombineDimsLayer'>
      layer_class.get_out_data_from_opts = <local> <bound method CombineDimsLayer.get_out_data_from_opts of <class 'returnn.tf.layers.basic.CombineDimsLayer'>>
      layer_desc = <local> {'axes': 'non_spatial', 'sources': [<_TemplateLayer(GaussWindowAttentionLayer)(:template:gauss_window_attention) 'decoder/att' out_type=Data(shape=(5, 20), time_dim_axis=None, batch_shape_meta=[B,5,F|20]) (construction stack 'att_comb')>], 'name': 'att_comb', 'network': <TFNetwork 'root/decoder:r...
  File "/home/mdigangi/bin/returnn/returnn/tf/layers/basic.py", line 4488, in get_out_data_from_opts
    line: assert len(axes) >= 2
    locals:
      len = <builtin> <built-in function len>
      axes = <local> [2]
AssertionError
.
.
.
```

**Comment by albertz** [comment]
(Note: For multi-line code formatting was wrong. Please check Markdown format. I fixed it for you.)

Can you maybe create a branch / PR where you add this as a test case?

What is after the "..."? I think the whole message is relevant.

**Comment by albertz** [comment]
I wonder whether the behavior of "non_spatial" changed at some point. This looks wrong. When you change that to `"axes": "static"`, does it work? Also, use `merge_dims` if you want, but I think this should not matter.

**Comment by mattiadg** [comment]
it works with "static"

**Comment by albertz** [comment]
Already pushed. :)
