### ISSUE TITLE
test_Util.test_cmd_stderr fails: cannot create /dev/stderr: No such device or address

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#424]
For example [here](https://github.com/rwth-i6/returnn/pull/423/checks?check_run_id=1737298616).

```
.../bin/sh: 1: cannot create /dev/stderr: No such device or address
E........S.................
======================================================================
ERROR: test_Util.test_cmd_stderr
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    line: self.test(*self.arg)
    locals:
      self = <local> test_Util.test_cmd_stderr
      self.test = <local> <function test_cmd_stderr at 0x7f234e220950>
      self.arg = <local> ()
  File "/home/runner/work/returnn/returnn/tests/test_Util.py", line 34, in test_cmd_stderr
    line: r = sys_cmd_out_lines("echo x >/dev/stderr")
    locals:
      r = <not found>
      sys_cmd_out_lines = <global> <function sys_cmd_out_lines at 0x7f2386ce3050>
  File "/home/runner/work/returnn/returnn/returnn/util/basic.py", line 210, in sys_cmd_out_lines
    line: raise CalledProcessError(p.returncode, s, stdout)
    locals:
      CalledProcessError = <global> <class 'subprocess.CalledProcessError'>
      p = <local> <subprocess.Popen object at 0x7f234d659050>
      p.returncode = <local> 2
      s = <local> 'echo x >/dev/stderr', len = 19
      stdout = <local> ''
subprocess.CalledProcessError: Command 'echo x >/dev/stderr' returned non-zero exit status 2.
```

**Comment by albertz** [comment]
It might work if we do `echo x >&2` instead of `echo x >/dev/stderr` ([via](https://unix.stackexchange.com/questions/401372/dev-stderr-in-systemd-service)).

@Zettelkasten maybe you can put this into a PR?

**Comment by Zettelkasten** [comment]
This seems to work! I added a PR #424.
