### ISSUE TITLE
Error or Bug when i run config_fwd on my own created Test Set

### ISSUE THREAD

**Issue by prolaser** [rwth-i6/returnn#62]
Hi everyone

I have took some images of handwritten scripts which i have prepared myself. I have then adapted the code from create_IAM_dataset.py to convert my images to hdf5 format and it converted them successfully. Now that I am trying to use config_fwd to get the on my created testset i face an error. Do i need to change anything in config_fwd except the path of eval? here is the error:

RETURNN starting up, version 20180405.225130--git-538ed96-dirty, date/time 2018-09-05-10-04-58 (UTC+0200), pid 13139, cwd /home/arman/returnn/demos/mdlstm/IAM, Python /usr/bin/python
RETURNN command line options: ['config_fwd']
faulthandler import error. No module named faulthandler
Theano: 0.9.0 (<not-under-git> in /usr/local/lib/python2.7/dist-packages/Theano-0.9.0-py2.7.egg/theano)
pynvml not available, memory information missing
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX 960M (CNMeM is enabled with initial size: 80.0% of memory, cuDNN 5110)
Device train-network: Used data keys: ['classes', 'data', 'sizes']
Devices: Used in blocking / single proc mode.                                                                                                                                                               
parsing file features/raw/test.h5
loading file 1/1 features/raw/test.h5
cached 3 seqs 0.005933091044425964 GB (fully loaded, 1.6607335759326816 GB left over)
Unhandled exception <type 'exceptions.AssertionError'> in thread <_MainThread(MainThread, started 139787278063360)>, proc 13139.

Thread current, main, <_MainThread(MainThread, started 139787278063360)>:
(Excluded thread.)

That were all threads.
EXCEPTION
Traceback (most recent call last):
  File "../../../rnn.py", line 559, in <module>
    line: main(sys.argv)
    locals:
      main = <local> <function main at 0x7f2287e4b410>
      sys = <local> <module 'sys' (built-in)>
      sys.argv = <local> ['../../../rnn.py', 'config_fwd'], _[0]: {len = 15}
  File "../../../rnn.py", line 546, in main
    line: init(commandLineOptions=argv[1:])
    locals:
      init = <global> <function init at 0x7f2287e4b1b8>
      commandLineOptions = <not found>
      argv = <local> ['../../../rnn.py', 'config_fwd'], _[0]: {len = 15}
  File "../../../rnn.py", line 345, in init
    line: initData()
    locals:
      initData = <global> <function initData at 0x7f2287e4aed8>
  File "../../../rnn.py", line 242, in initData
    line: train_data, extra_train = load_data(config, train_cache_bytes, 'train')
    locals:
      train_data = <global> None
      extra_train = <not found>
      load_data = <global> <function load_data at 0x7f2287e4ae60>
      config = <global> <Config.Config instance at 0x7f2287eb8c68>
      train_cache_bytes = <local> 7151908220
  File "../../../rnn.py", line 216, in load_data
    line: data = init_dataset_via_str(config_str, config=config, cache_byte_size=cache_byte_size, **kwargs)
    locals:
      data = <not found>
      init_dataset_via_str = <global> <function init_dataset_via_str at 0x7f22881bca28>
      config_str = <local> 'features/raw/train.1.h5', len = 23
      config = <local> <Config.Config instance at 0x7f2287eb8c68>
      cache_byte_size = <local> 7151908220
      kwargs = <local> {'name': 'train'}
  File "/home/arman/returnn/Dataset.py", line 856, in init_dataset_via_str
    line: assert os.path.exists(f)
    locals:
      os = <global> <module 'os' from '/usr/lib/python2.7/os.pyc'>
      os.path = <global> <module 'posixpath' from '/usr/lib/python2.7/posixpath.pyc'>
      os.path.exists = <global> <function exists at 0x7f22c305ced8>
      f = <local> 'features/raw/train.1.h5', len = 23
AssertionError

**Comment by prolaser** [comment]
and this is the error while i turn multiprocessing = true in config_fwd

RETURNN starting up, version 20180405.225130--git-538ed96-dirty, date/time 2018-09-05-10-07-38 (UTC+0200), pid 13293, cwd /home/arman/returnn/demos/mdlstm/IAM, Python /usr/bin/python
RETURNN command line options: ['config_fwd']
faulthandler import error. No module named faulthandler
Theano: 0.9.0 (<not-under-git> in /usr/local/lib/python2.7/dist-packages/Theano-0.9.0-py2.7.egg/theano)
pynvml not available, memory information missing
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX 960M (CNMeM is enabled with initial size: 80.0% of memory, cuDNN 5110)
Device gpuX proc starting up, pid 13327
Device gpuX proc: THEANO_FLAGS = 'compiledir_format=compiledir_%(platform)s-%(processor)s-%(python_version)s-%(python_bitwidth)s--dev-gpuZ,device=gpu,force_device=True'
faulthandler import error. No module named faulthandler
Device train-network: Used data keys: ['classes', 'data', 'sizes']
Device gpu0 proc, pid 13327 is ready for commands.                                                                                                                                                          
Devices: Used in multiprocessing mode.
parsing file features/raw/test.h5
loading file 1/1 features/raw/test.h5
cached 3 seqs 0.005933091044425964 GB (fully loaded, 1.6607335759326816 GB left over)
EXCEPTION
Traceback (most recent call last):
  File "../../../rnn.py", line 559, in <module>
    line: main(sys.argv)
    locals:
      main = <local> <function main at 0x7feb4fd65410>
      sys = <local> <module 'sys' (built-in)>
      sys.argv = <local> ['../../../rnn.py', 'config_fwd'], _[0]: {len = 15}
  File "../../../rnn.py", line 546, in main
    line: init(commandLineOptions=argv[1:])
    locals:
      init = <global> <function init at 0x7feb4fd651b8>
      commandLineOptions = <not found>
      argv = <local> ['../../../rnn.py', 'config_fwd'], _[0]: {len = 15}
  File "../../../rnn.py", line 345, in init
    line: initData()
    locals:
      initData = <global> <function initData at 0x7feb4fd64ed8>
  File "../../../rnn.py", line 242, in initData
    line: train_data, extra_train = load_data(config, train_cache_bytes, 'train')
    locals:
      train_data = <global> None
      extra_train = <not found>
      load_data = <global> <function load_data at 0x7feb4fd64e60>
      config = <global> <Config.Config instance at 0x7feb4fdd2c68>
      train_cache_bytes = <local> 7151908220
  File "../../../rnn.py", line 216, in load_data
    line: data = init_dataset_via_str(config_str, config=config, cache_byte_size=cache_byte_size, **kwargs)
    locals:
      data = <not found>
      init_dataset_via_str = <global> <function init_dataset_via_str at 0x7feb500d6a28>
      config_str = <local> 'features/raw/train.1.h5', len = 23
      config = <local> <Config.Config instance at 0x7feb4fdd2c68>
      cache_byte_size = <local> 7151908220
      kwargs = <local> {'name': 'train'}
  File "/home/arman/returnn/Dataset.py", line 856, in init_dataset_via_str
    line: assert os.path.exists(f)
    locals:
      os = <global> <module 'os' from '/usr/lib/python2.7/os.pyc'>
      os.path = <global> <module 'posixpath' from '/usr/lib/python2.7/posixpath.pyc'>
      os.path.exists = <global> <function exists at 0x7feb8af76ed8>
      f = <local> 'features/raw/train.1.h5', len = 23
AssertionError
Device gpuX proc, pid 13327: Parent seem to have died: recv_bytes EOFError:
