### ISSUE TITLE
MergeDimsLayer: problem with 2 dimensional dynamic axes

### ISSUE THREAD

**Issue by robin-p-schmitt** [rwth-i6/returnn#662]
If one of the output axes of the layer has a dynamic size with shape `[B,T]` (or, in general, a shape with more than one dimension), it will trigger an error:

```
2021-09-17 14:58:36,854 returnn INFO: layer <network via test_MergeDimsLayer_2d_dynamic_merge_axis>/'data' output: Data{'data', [B,T|'time:var:extern_data:data'[B],F|F'feature:data'(5)]}
2021-09-17 14:58:36,855 returnn INFO: layer <network via test_MergeDimsLayer_2d_dynamic_merge_axis>/'start0' output: Data{'start0_output', [B], dtype='int32'}
2021-09-17 14:58:36,859 returnn INFO: layer <network via test_MergeDimsLayer_2d_dynamic_merge_axis>/'start1' output: Data{'start1_output', [T|F|'time:var:extern_data:data'[B]], dtype='int32'}
2021-09-17 14:58:36,864 returnn INFO: layer <network via test_MergeDimsLayer_2d_dynamic_merge_axis>/'start' output: Data{'start_output', [B,T|F|'time:var:extern_data:data'[B]], dtype='int32'}
2021-09-17 14:58:36,867 returnn INFO: layer <network via test_MergeDimsLayer_2d_dynamic_merge_axis>/'slices' output: Data{'slices_gather_output', [B,T|'time:var:extern_data:data'[B],'sliced-time:slices'[?],F|F'feature:data'(5)]}
2021-09-17 14:58:36,881 returnn INFO: layer <network via test_MergeDimsLayer_2d_dynamic_merge_axis>/'output' output: Data{'output_output', [B,T|'time:var:extern_data:data'[B],F|F'output_merge_dims'[?]]}
Exception creating layer <network via test_MergeDimsLayer_2d_dynamic_merge_axis>/'output' of class MergeDimsLayer with opts:
{'_name': 'output',
 '_network': <TFNetwork '<network via test_MergeDimsLayer_2d_dynamic_merge_axis>' train>,
 'axes': ['f', 'dyn:-1'],
 'name': 'output',
 'network': <TFNetwork '<network via test_MergeDimsLayer_2d_dynamic_merge_axis>' train>,
 'output': Data{'output_output', [B,T|'time:var:extern_data:data'[B],F|F'output_merge_dims'[?]]},
 'sources': [<SliceNdLayer 'slices' out_type=Data{[B,T|'time:var:extern_data:data'[B],'sliced-time:slices'[B,'time:var:extern_data:data'[B]],F|F'feature:data'(5)]}>]}
EXCEPTION
Traceback (most recent call last):
  File "/home/robin/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/212.4746.96/plugins/python/helpers/pycharm/_jb_unittest_runner.py", line 35, in <module>
    line: sys.exit(main(argv=args, module=None, testRunner=unittestpy.TeamcityTestRunner, buffer=not JB_DISABLE_BUFFERING))
    locals:
      sys = <local> <module 'sys' (built-in)>
      sys.exit = <local> <built-in function exit>
      main = <local> <class 'unittest.main.TestProgram'>
      argv = <not found>
      args = <local> ['python -m unittest', 'test_TFNetworkLayer.test_MergeDimsLayer_2d_dynamic_merge_axis'], _[0]: {len = 18}
      module = <not found>
      testRunner = <not found>
      unittestpy = <local> <module 'teamcity.unittestpy' from '/home/robin/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/212.4746.96/plugins/python/helpers/pycharm/teamcity/unittestpy.py'>
      unittestpy.TeamcityTestRunner = <local> <class 'teamcity.unittestpy.TeamcityTestRunner'>
      buffer = <not found>
      JB_DISABLE_BUFFERING = <local> False
  File "/home/robin/miniconda3/envs/i6_env/lib/python3.9/unittest/main.py", line 100, in TestProgram.__init__
    line: self.parseArgs(argv)
    locals:
      self = <local> <unittest.main.TestProgram object at 0x7fa2fbb8afa0>
      self.parseArgs = <local> <bound method TestProgram.parseArgs of <unittest.main.TestProgram object at 0x7fa2fbb8afa0>>
      argv = <local> ['python -m unittest', 'test_TFNetworkLayer.test_MergeDimsLayer_2d_dynamic_merge_axis'], _[0]: {len = 18}
  File "/home/robin/miniconda3/envs/i6_env/lib/python3.9/unittest/main.py", line 147, in TestProgram.parseArgs
    line: self.createTests()
    locals:
      self = <local> <unittest.main.TestProgram object at 0x7fa2fbb8afa0>
      self.createTests = <local> <bound method TestProgram.createTests of <unittest.main.TestProgram object at 0x7fa2fbb8afa0>>
  File "/home/robin/miniconda3/envs/i6_env/lib/python3.9/unittest/main.py", line 158, in TestProgram.createTests
    line: self.test = self.testLoader.loadTestsFromNames(self.testNames,
                                                         self.module)
    locals:
      self = <local> <unittest.main.TestProgram object at 0x7fa2fbb8afa0>
      self.test = <local> !AttributeError: 'TestProgram' object has no attribute 'test'
      self.testLoader = <local> <unittest.loader.TestLoader object at 0x7fa2fbb32f70>
      self.testLoader.loadTestsFromNames = <local> <bound method TestLoader.loadTestsFromNames of <unittest.loader.TestLoader object at 0x7fa2fbb32f70>>
      self.testNames = <local> ['test_TFNetworkLayer.test_MergeDimsLayer_2d_dynamic_merge_axis'], _[0]: {len = 61}
      self.module = <local> None
  File "/home/robin/miniconda3/envs/i6_env/lib/python3.9/unittest/loader.py", line 220, in TestLoader.loadTestsFromNames
    line: suites = [self.loadTestsFromName(name, module) for name in names]
    locals:
      suites = <not found>
      self = <local> <unittest.loader.TestLoader object at 0x7fa2fbb32f70>
      self.loadTestsFromName = <local> <bound method TestLoader.loadTestsFromName of <unittest.loader.TestLoader object at 0x7fa2fbb32f70>>
      name = <not found>
      module = <local> None
      names = <local> ['test_TFNetworkLayer.test_MergeDimsLayer_2d_dynamic_merge_axis'], _[0]: {len = 61}
  File "/home/robin/miniconda3/envs/i6_env/lib/python3.9/unittest/loader.py", line 220, in <listcomp>
    line: suites = [self.loadTestsFromName(name, module) for name in names]
    locals:
      suites = <not found>
      self = <local> <unittest.loader.TestLoader object at 0x7fa2fbb32f70>
      self.loadTestsFromName = <local> <bound method TestLoader.loadTestsFromName of <unittest.loader.TestLoader object at 0x7fa2fbb32f70>>
      name = <local> 'test_TFNetworkLayer.test_MergeDimsLayer_2d_dynamic_merge_axis', len = 61
      module = <local> None
      names = <not found>
  File "/home/robin/miniconda3/envs/i6_env/lib/python3.9/unittest/loader.py", line 205, in TestLoader.loadTestsFromName
    line: test = obj()
    locals:
      test = <not found>
      obj = <local> <function test_MergeDimsLayer_2d_dynamic_merge_axis at 0x7fa359f1d3a0>
  File "/mnt/projects/i6/returnn/tests/test_TFNetworkLayer.py", line 1698, in test_MergeDimsLayer_2d_dynamic_merge_axis
    line: net.construct_from_dict({
            "start0": {"class": "range_in_axis", "from": "data", "axis": "b"},
            "start1": {"class": "range_in_axis", "from": "data", "axis": "t"},
            "start": {"class": "combine", "from": ["start0", "start1"], "kind": "add"},
            "slices": {"class": "slice_nd", "from": "data", "start": "start", "size": None},
            "output": {"class": "merge_dims", "from": ["slices"], "axes": ["f", "dyn:-1"]}
          })
    locals:
      net = <local> <TFNetwork '<network via test_MergeDimsLayer_2d_dynamic_merge_axis>' train>
      net.construct_from_dict = <local> <bound method TFNetwork.construct_from_dict of <TFNetwork '<network via test_MergeDimsLayer_2d_dynamic_merge_axis>' train>>
  File "/mnt/projects/i6/returnn/returnn/tf/network.py", line 605, in TFNetwork.construct_from_dict
    line: self.construct_layer(net_dict, name, get_layer=get_layer)
    locals:
      self = <local> <TFNetwork '<network via test_MergeDimsLayer_2d_dynamic_merge_axis>' train>
      self.construct_layer = <local> <bound method TFNetwork.construct_layer of <TFNetwork '<network via test_MergeDimsLayer_2d_dynamic_merge_axis>' train>>
      net_dict = <local> {'start0': {'class': 'range_in_axis', 'from': 'data', 'axis': 'b'}, 'start1': {'class': 'range_in_axis', 'from': 'data', 'axis': 't'}, 'start': {'class': 'combine', 'from': ['start0', 'start1'], 'kind': 'add'}, 'slices': {'class': 'slice_nd', 'from': 'data', 'start': 'start', 'size': None}, 'outp...
      name = <local> 'output', len = 6
      get_layer = <local> None
  File "/mnt/projects/i6/returnn/returnn/tf/network.py", line 931, in TFNetwork.construct_layer
    line: return add_layer(name=name_with_prefix, layer_class=layer_class, **layer_desc)
    locals:
      add_layer = <local> <bound method TFNetwork.add_layer of <TFNetwork '<network via test_MergeDimsLayer_2d_dynamic_merge_axis>' train>>
      name = <local> 'output', len = 6
      name_with_prefix = <local> 'output', len = 6
      layer_class = <local> <class 'returnn.tf.layers.basic.MergeDimsLayer'>
      layer_desc = <local> {'axes': ['f', 'dyn:-1'], '_network': <TFNetwork '<network via test_MergeDimsLayer_2d_dynamic_merge_axis>' train>, '_name': 'output', 'sources': [<SliceNdLayer 'slices' out_type=Data{[B,T|'time:var:extern_data:data'[B],'sliced-time:slices'[B,'time:var:extern_data:data'[B]],F|F'feature:data'(5)]}>]}
  File "/mnt/projects/i6/returnn/returnn/tf/network.py", line 1077, in TFNetwork.add_layer
    line: layer = self._create_layer(name=name, layer_class=layer_class, **layer_desc)
    locals:
      layer = <not found>
      self = <local> <TFNetwork '<network via test_MergeDimsLayer_2d_dynamic_merge_axis>' train>
      self._create_layer = <local> <bound method TFNetwork._create_layer of <TFNetwork '<network via test_MergeDimsLayer_2d_dynamic_merge_axis>' train>>
      name = <local> 'output', len = 6
      layer_class = <local> <class 'returnn.tf.layers.basic.MergeDimsLayer'>
      layer_desc = <local> {'axes': ['f', 'dyn:-1'], '_network': <TFNetwork '<network via test_MergeDimsLayer_2d_dynamic_merge_axis>' train>, '_name': 'output', 'sources': [<SliceNdLayer 'slices' out_type=Data{[B,T|'time:var:extern_data:data'[B],'sliced-time:slices'[B,'time:var:extern_data:data'[B]],F|F'feature:data'(5)]}>]}
  File "/mnt/projects/i6/returnn/returnn/tf/network.py", line 998, in TFNetwork._create_layer
    line: layer = layer_class(**layer_desc)
    locals:
      layer = <not found>
      layer_class = <local> <class 'returnn.tf.layers.basic.MergeDimsLayer'>
      layer_desc = <local> {'axes': ['f', 'dyn:-1'], '_network': <TFNetwork '<network via test_MergeDimsLayer_2d_dynamic_merge_axis>' train>, '_name': 'output', 'sources': [<SliceNdLayer 'slices' out_type=Data{[B,T|'time:var:extern_data:data'[B],'sliced-time:slices'[B,'time:var:extern_data:data'[B]],F|F'feature:data'(5)]}>..., len = 7
  File "/mnt/projects/i6/returnn/returnn/tf/layers/basic.py", line 2600, in MergeDimsLayer.__init__
    line: self.output.size_placeholder = self._get_output_sizes(merge_axes=axes)
    locals:
      self = <local> <MergeDimsLayer 'output' out_type=Data{[B,T|'time:var:extern_data:data'[B],F|F'output_merge_dims'[?]]}>
      self.output = <local> Data{'output_output', [B,T|'time:var:extern_data:data'[B],F|F'output_merge_dims'[?]]}
      self.output.size_placeholder = <local> {0: <tf.Tensor 'extern_data/placeholders/data/data_dim0_size:0' shape=(?,) dtype=int32>}, len = 1
      self._get_output_sizes = <local> <bound method MergeDimsLayer._get_output_sizes of <MergeDimsLayer 'output' out_type=Data{[B,T|'time:var:extern_data:data'[B],F|F'output_merge_dims'[?]]}>>
      merge_axes = <not found>
      axes = <local> [2, 3]
  File "/mnt/projects/i6/returnn/returnn/tf/util/data.py", line 2506, in Data.size_placeholder
    line: self.set_dynamic_size(axis=self.get_batch_axis(axis_wo_b), sizes=size)
    locals:
      self = <local> Data{'output_output', [B,T|'time:var:extern_data:data'[B],F|F'output_merge_dims'[?]]}
      self.set_dynamic_size = <local> <bound method Data.set_dynamic_size of Data{'output_output', [B,T|'time:var:extern_data:data'[B],F|F'output_merge_dims'[?]]}>
      axis = <not found>
      self.get_batch_axis = <local> <bound method Data.get_batch_axis of Data{'output_output', [B,T|'time:var:extern_data:data'[B],F|F'output_merge_dims'[?]]}>
      axis_wo_b = <local> 1
      sizes = <local> {0: <tf.Tensor 'extern_data/placeholders/data/data_dim0_size:0' shape=(?,) dtype=int32>, 1: <tf.Tensor 'output/mul:0' shape=(?, ?) dtype=int32>}
      size = <local> <tf.Tensor 'output/mul:0' shape=(?, ?) dtype=int32>
  File "/mnt/projects/i6/returnn/returnn/tf/util/data.py", line 3128, in Data.set_dynamic_size
    line: new_tag = tag.set_tag_on_size_tensor(sizes, batch=self.batch)
    locals:
      new_tag = <not found>
      tag = <local> DimensionTag{F'output_merge_dims'[?]}
      tag.set_tag_on_size_tensor = <local> <bound method DimensionTag.set_tag_on_size_tensor of DimensionTag{F'output_merge_dims'[?]}>
      sizes = <local> <tf.Tensor 'output/mul:0' shape=(?, ?) dtype=int32>
      batch = <not found>
      self = <local> Data{'output_output', [B,T|'time:var:extern_data:data'[B],F|F'output_merge_dims'[?]]}
      self.batch = <local> BatchInfo{B}
  File "/mnt/projects/i6/returnn/returnn/tf/util/data.py", line 317, in DimensionTag.set_tag_on_size_tensor
    line: self.dyn_size = x
    locals:
      self = <local> DimensionTag{F'output_merge_dims'[?]}
      self.dyn_size = <local> None
      x = <local> <tf.Tensor 'output/mul:0' shape=(?, ?) dtype=int32>
  File "/mnt/projects/i6/returnn/returnn/tf/util/data.py", line 209, in DimensionTag.dyn_size
    line: assert isinstance(dyn_size, tf.Tensor) and dyn_size.shape.ndims == 1
    locals:
      isinstance = <builtin> <built-in function isinstance>
      dyn_size = <local> <tf.Tensor 'output/mul:0' shape=(?, ?) dtype=int32>
      tf = <global> <module 'tensorflow' from '/home/robin/miniconda3/envs/i6_env/lib/python3.9/site-packages/tensorflow/__init__.py'>
      tf.Tensor = <global> <class 'tensorflow.python.framework.ops.Tensor'>
      dyn_size.shape = <local> TensorShape([Dimension(None), Dimension(None)]), len = 2
      dyn_size.shape.ndims = <local> 2
AssertionError
```

This is the test code I used:

```
def test_MergeDimsLayer_2d_dynamic_merge_axis():
  with make_scope():
    n_out = 5
    config = Config({
      "debug_print_layer_output_template": True,
      "extern_data": {
        "data": {"dim": n_out},}})
    net = TFNetwork(config=config, train_flag=True)
    net.construct_from_dict({
      "start0": {"class": "range_in_axis", "from": "data", "axis": "b"},
      "start1": {"class": "range_in_axis", "from": "data", "axis": "t"},
      "start": {"class": "combine", "from": ["start0", "start1"], "kind": "add"},
      "slices": {"class": "slice_nd", "from": "data", "start": "start", "size": None},
      "output": {"class": "merge_dims", "from": ["slices"], "axes": ["f", "dyn:-1"]}
    })
```

The error happens inside of:
 https://github.com/rwth-i6/returnn/blob/1ac7827867f034620b8e06d8910049aa2956f512/returnn/tf/layers/basic.py#L2600

I assume it has something to do with this line in `self._get_output_sizes(merge_axes=axes)`:
https://github.com/rwth-i6/returnn/blob/1ac7827867f034620b8e06d8910049aa2956f512/returnn/tf/layers/basic.py#L2666

Before it is executed, the tensors in `d` might have the `_is_size_of_dim_tag` attribute set. But after `d[j] *= self.input_data.get_dim(axis)`, the attribute is not set anymore. At least this is the case in my test case. Later, in the `size_placeholder` setter, it is tested if the sizes have this attribute. So maybe this is the issue.

**Comment by albertz** [comment]
Ah yea `MergeDimsLayer` assigns to `size_placeholder`. That doesn't work for extended dyn sizes (not of shape [B]). All older code which assigns to `size_placeholder` breaks in this way.
