### ISSUE TITLE
Timeout when trying to run search_single in process pool

### ISSUE THREAD

**Issue by patrick-wilken** [rwth-i6/returnn#80]
I want to run several search instances in parallel. For this I want to use the multiprocessing module. However, all subprocesses timeout after 0.1s. I am sure, this is because in `initThreadJoinHack()` (Util.py, line 663) the `wait` method is overwritten using a timeout of 0.1s.

Minimal script to produce the error (run in RETURNN root dir):

```
#!/usr/bin/env python3
from multiprocessing import Pool
import rnn

rnn.init(configFilename="demos/demo-tf-native-lstm2.12ax.config")
rnn.engine.init_network_from_config()

example_input = [[[0, 0, 0, 0, 0, 0, 0, 0, 0]]]

def helper_func(input):
    return rnn.engine.search_single_seq(input)

pool = Pool(processes=1)
result = pool.map(helper_func, example_input)
print(result)

# print(rnn.engine.search_single_seq(example_input[0]))
```

The output I get is:

```
Hello, experiment: demos/demo-tf-native-lstm2.12ax
RETURNN starting up, version 20181012.011529--git-5d3774d-dirty, date/time 2018-10-16-07-15-51 (UTC-0400), pid 10855, cwd /home/pwilken/src/returnn, Python /home/pwilken/venv_upstream_tf_mkl/bin/python3
TensorFlow: 1.11.0-rc1 (b'v1.9.0-rc2-4872-g40a36ea') (<site-package> in /home/pwilken/venv_upstream_tf_mkl/lib/python3.5/site-packages/tensorflow)
Setup TF inter and intra global thread pools, num_threads None, session opts {'log_device_placement': False, 'device_count': {'GPU': 0}}.
2018-10-16 07:15:55.817609: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
CUDA_VISIBLE_DEVICES is set to '-1'.
Collecting TensorFlow device list...
Local devices available to TensorFlow:
  1/1: name: "/device:CPU:0"
       device_type: "CPU"
       memory_limit: 268435456
       locality {
       }
       incarnation: 11829771652516982419
Train data:
  input: 9 x 1
  output: {'data': [9, 2], 'classes': [2, 1]}
  Task12AXDataset, sequences: 1000, frames: unknown
Dev data:
  Task12AXDataset, sequences: 100, frames: unknown
Device not set explicitly, and no GPU found.
Setup tf.Session with options {'log_device_placement': False, 'device_count': {'GPU': 0}} ...
Network layer topology:
  extern data: data: Data(shape=(None, 9)), classes: Data(shape=(None,), dtype='int32', sparse=True, dim=2, available_for_inference=False)
  used data keys: ['data']
  layer source 'data' #: 9
  layer rec 'fw0' #: 10
  layer softmax 'output' #: 2
net params #: 822
net trainable params: [<tf.Variable 'fw0/rec/W:0' shape=(9, 40) dtype=float32_ref>, <tf.Variable 'fw0/rec/W_re:0' shape=(10, 40) dtype=float32_ref>, <tf.Variable 'fw0/rec/b:0' shape=(40,) dtype=float32_ref>, <tf.Variable 'output/W:0' shape=(10, 2) dtype=float32_ref>, <tf.Variable 'output/b:0' shape=(2,) dtype=float32_ref>]
loading weights from /tmp/pwilken/crnn/demos/demo-tf-native-lstm2.12ax/model.076
Unhandled exception <class 'multiprocessing.context.TimeoutError'> in thread <_MainThread(MainThread, started 140049674413824)>, proc 10855.

Thread <Thread(Thread-1, started daemon 140047619708672)>:
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 367, in _handle_workers
    line: time.sleep(0.1)
    locals:
      time = <global> <module 'time' (built-in)>
      time.sleep = <global> <built-in function sleep>
  File "/usr/lib/python3.5/threading.py", line 862, in run
    line: self._target(*self._args, **self._kwargs)
    locals:
      self = <local> <Thread(Thread-1, started daemon 140047619708672)>
      self._target = <local> <function Pool._handle_workers at 0x7f5f91cc4a60>
      self._args = <local> (<multiprocessing.pool.Pool object at 0x7f5f9127dba8>,)
      self._kwargs = <local> {}
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    line: self.run()
    locals:
      self = <local> <Thread(Thread-1, started daemon 140047619708672)>
      self.run = <local> <bound method Thread.run of <Thread(Thread-1, started daemon 140047619708672)>>
  File "/usr/lib/python3.5/threading.py", line 882, in _bootstrap
    line: self._bootstrap_inner()
    locals:
      self = <local> <Thread(Thread-1, started daemon 140047619708672)>
      self._bootstrap_inner = <local> <bound method Thread._bootstrap_inner of <Thread(Thread-1, started daemon 140047619708672)>>

Thread <Thread(Thread-2, started daemon 140047628101376)>:
  File "/usr/lib/python3.5/threading.py", line 293, in wait
    line: waiter.acquire()
    locals:
      waiter = <local> <locked _thread.lock object at 0x7f5f62709148>
      waiter.acquire = <local> <built-in method acquire of _thread.lock object at 0x7f5f62709148>
  File "/home/pwilken/src/returnn/Util.py", line 662, in cond_wait_hacked
    line: return cond_wait_orig(cond, timeout=timeout)
    locals:
      cond_wait_orig = <local> <function Condition.wait at 0x7f5fd9a72840>
      cond = <local> <Condition(<unlocked _thread.lock object at 0x7f5f62ca39e0>, 1)>
      timeout = <local> None
  File "/usr/lib/python3.5/queue.py", line 164, in get
    line: self.not_empty.wait()
    locals:
      self = <local> <queue.Queue object at 0x7f5f62701780>
      self.not_empty = <local> <Condition(<unlocked _thread.lock object at 0x7f5f62ca39e0>, 1)>
      self.not_empty.wait = <local> <bound method initThreadJoinHack.<locals>.cond_wait_hacked of <Condition(<unlocked _thread.lock object at 0x7f5f62ca39e0>, 1)>>
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 376, in _handle_tasks
    line: for taskseq, set_length in iter(taskqueue.get, None):
    locals:
      taskseq = <local> <generator object Pool._map_async.<locals>.<genexpr> at 0x7f5f627690f8>
      set_length = <local> None
      iter = <builtin> <built-in function iter>
      taskqueue = <local> <queue.Queue object at 0x7f5f62701780>
      taskqueue.get = <local> <bound method Queue.get of <queue.Queue object at 0x7f5f62701780>>
  File "/usr/lib/python3.5/threading.py", line 862, in run
    line: self._target(*self._args, **self._kwargs)
    locals:
      self = <local> <Thread(Thread-2, started daemon 140047628101376)>
      self._target = <local> <function Pool._handle_tasks at 0x7f5f91cc4ae8>
      self._args = <local> (<queue.Queue object at 0x7f5f62701780>, <bound method _ConnectionBase.send of <multiprocessing.connection.Connection object at 0x7f5f62cadb00>>, <multiprocessing.queues.SimpleQueue object at 0x7f5f626efeb8>, [<ForkProcess(ForkPoolWorker-1, started daemon)>], {0: <multiprocessing.pool.MapResult o...
      self._kwargs = <local> {}
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    line: self.run()
    locals:
      self = <local> <Thread(Thread-2, started daemon 140047628101376)>
      self.run = <local> <bound method Thread.run of <Thread(Thread-2, started daemon 140047628101376)>>
  File "/usr/lib/python3.5/threading.py", line 882, in _bootstrap
    line: self._bootstrap_inner()
    locals:
      self = <local> <Thread(Thread-2, started daemon 140047628101376)>
      self._bootstrap_inner = <local> <bound method Thread._bootstrap_inner of <Thread(Thread-2, started daemon 140047628101376)>>

Thread <Thread(Thread-3, started daemon 140047636494080)>:
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    line: chunk = read(handle, remaining)
    locals:
      chunk = <not found>
      read = <local> <built-in function read>
      handle = <local> 7
      remaining = <local> 4
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    line: buf = self._recv(4)
    locals:
      buf = <not found>
      self = <local> <multiprocessing.connection.Connection object at 0x7f5f62701630>
      self._recv = <local> <bound method Connection._recv of <multiprocessing.connection.Connection object at 0x7f5f62701630>>
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    line: buf = self._recv_bytes()
    locals:
      buf = <not found>
      self = <local> <multiprocessing.connection.Connection object at 0x7f5f62701630>
      self._recv_bytes = <local> <bound method Connection._recv_bytes of <multiprocessing.connection.Connection object at 0x7f5f62701630>>
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 429, in _handle_results
    line: task = get()
    locals:
      task = <not found>
      get = <local> <bound method _ConnectionBase.recv of <multiprocessing.connection.Connection object at 0x7f5f62701630>>
  File "/usr/lib/python3.5/threading.py", line 862, in run
    line: self._target(*self._args, **self._kwargs)
    locals:
      self = <local> <Thread(Thread-3, started daemon 140047636494080)>
      self._target = <local> <function Pool._handle_results at 0x7f5f91cc4b70>
      self._args = <local> (<multiprocessing.queues.SimpleQueue object at 0x7f5f626efeb8>, <bound method _ConnectionBase.recv of <multiprocessing.connection.Connection object at 0x7f5f62701630>>, {0: <multiprocessing.pool.MapResult object at 0x7f5f62701f28>})
      self._kwargs = <local> {}
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    line: self.run()
    locals:
      self = <local> <Thread(Thread-3, started daemon 140047636494080)>
      self.run = <local> <bound method Thread.run of <Thread(Thread-3, started daemon 140047636494080)>>
  File "/usr/lib/python3.5/threading.py", line 882, in _bootstrap
    line: self._bootstrap_inner()
    locals:
      self = <local> <Thread(Thread-3, started daemon 140047636494080)>
      self._bootstrap_inner = <local> <bound method Thread._bootstrap_inner of <Thread(Thread-3, started daemon 140047636494080)>>
EXCEPTION
Traceback (most recent call last):
  File "./git_issue.py", line 15, in <module>
    line: result = pool.map(helper_func, example_input)
    locals:
      result = <not found>
      pool = <local> <multiprocessing.pool.Pool object at 0x7f5f9127dba8>
      pool.map = <local> <bound method Pool.map of <multiprocessing.pool.Pool object at 0x7f5f9127dba8>>
      helper_func = <local> <function helper_func at 0x7f5f627291e0>
      example_input = <local> [[[0, 0, 0, 0, 0, 0, 0, 0, 0]]], _[0]: {_[0]: {len = 9}}
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    line: return self._map_async(func, iterable, mapstar, chunksize).get()
    locals:
      self = <local> <multiprocessing.pool.Pool object at 0x7f5f9127dba8>
      self._map_async = <local> <bound method Pool._map_async of <multiprocessing.pool.Pool object at 0x7f5f9127dba8>>
      func = <local> <function helper_func at 0x7f5f627291e0>
      iterable = <local> [[[0, 0, 0, 0, 0, 0, 0, 0, 0]]], _[0]: {_[0]: {len = 9}}
      mapstar = <global> <function mapstar at 0x7f5f91c9ed90>
      chunksize = <local> None
      get = <not found>
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 604, in get
    line: raise TimeoutError
    locals:
      TimeoutError = <global> <class 'multiprocessing.context.TimeoutError'>
TimeoutError

Thread current, main, <_MainThread(MainThread, started 140049674413824)>:
(Excluded thread.)

That were all threads.
```

Running the search without multiprocessing (last line) works, so the error is not related to the search itself.

I tried to "uninstall" the hack before creating the pool by recovering the original `wait` function, but without success. Either I get the timeout or a deadlock.

**Comment by albertz** [comment]
Please try with the update, and if it still fails, reopen.

**Comment by albertz** [comment]
If `timeout is None`, not terminating is the correct behavior.

**Comment by albertz** [comment]
See the documentation of `Condition.wait`.

**Comment by patrick-wilken** [comment]
Ok, I will need a deeper understanding of the threading module. But anyway, the script above does not terminate, it will end up being stuck in this loop.

**Comment by albertz** [comment]
But I don't quite understand why you think this is related at all to `cond_wait_hacked`. The behavior (the hang, i.e. your script not terminating) with `cond_wait_hacked` and with the original `Condition.wait` is the same, or not?

I would rather think (actually pretty sure) that `multiprocessing` together with TensorFlow is probably not supported (nothing Returnn related). What might work is to do the whole `rnn.init`, `rnn.engine.init` etc inside the `helper_func`.

**Comment by patrick-wilken** [comment]
You're right, this is an issue with TF itself (see https://github.com/tensorflow/tensorflow/issues/5448). I got the example working now, pretty tricky because of scopes required by set_start_method and pickling:

```
#!/usr/bin/env python3

import multiprocessing as mp
import rnn

rnn.init(configFilename = "demos/demo-tf-native-lstm2.12ax.config")
rnn.engine.init_network_from_config()
example_input = [[[0, 0, 0, 0, 0, 0, 0, 0, 0]]]

def helper_func(input):  # global, otherwise can't pickle for multiprocessing
    return rnn.engine.search_single_seq(input)

if __name__ == '__main__':
    mp.set_start_method("spawn")

    pool = mp.Pool(processes=1)
    result = pool.map(helper_func, example_input)
    print(result)
```

Initializing the whole network in the subthreads is no option for me, as this would cause too much of a slow down in real use cases.

**Comment by albertz** [comment]
Actually, my commit 232f02d really introduced a deadlock now. In 3877acdd2027d16e, this is hopefully fixed again.

Regarding your issue: mrry summarized it nicely, what I expected (TF is not fork safe), [here](https://github.com/tensorflow/tensorflow/issues/5448#issuecomment-258934405). I.e. `multiprocessing.set_start_method('spawn')` would be the thing to use (as you figured out) for multiprocessing.

Anyway, I wonder why you think that subthreads are not an option. Why do you think you will get too much slowdown? The main calculation happens in TF `session.run`, and that should be able to run in parallel. See for example the code in `HyperParamTuning` which works like this.

**Comment by patrick-wilken** [comment]
I need this for online translation, so in a query there are only a few (or even 1) sentences. You don't want to load the model each time for that.
But what I got working now is to start separate threads that each load the model and then wait for input (using a Queue).
I could not find a solution using one model instance, as 'fork' does not work and 'spawn' would require pickling the TF module/model/session, as I understand it.

Anyway, the solution I have now is pretty much what I wanted to do :) And it works with the current code. However, only because I start the processes before loading the models. When I did it the other way around the timeout error actually recurred with the latest change (for example in the script I posted here).

**Comment by albertz** [comment]
Why should the model be loaded each time? You load the model once, and then call `engine.search` (or so) in each thread. What would be the problem with that way?

**Comment by patrick-wilken** [comment]
My understanding is: Forking a TF model does not work. 'spawn' starts processes with a blank python session, so you have to load the model there or "send" it to the processes. For sending it has to be pickable, which it isn't (or at least it would be hard and ugly).

Whenever I tried to do what you suggested I got an error like "Can't pickle module".

**Comment by albertz** [comment]
I'm not speaking about multiprocessing. I speak about multi-threading. I don't understand why that is not the better solution, and also even much simpler.

**Comment by patrick-wilken** [comment]
Yes, that is simpler and it works. But python can't really parallelize with threading, no? I only observe a small speed improvement, with multi-processing it's surprisingly large.

**Comment by albertz** [comment]
Sure, Python can parallelize. The Python GIL should not be a problem too much, as the heavy work should all be inside TF `session.run`. That is what I wrote already:

> Anyway, I wonder why you think that subthreads are not an option. Why do you think you will get too much slowdown? The main calculation happens in TF session.run, and that should be able to run in parallel. See for example the code in HyperParamTuning which works like this.

There are other things like the number of threads you allocate for the TF thread pools, which you need to increase, otherwise you will limit yourself of course.

**Comment by patrick-wilken** [comment]
Ah, nice, you are right. When I use the threading module as a drop in replacement for multiprocessing I get the same speed if I also set `inter_op_parallelism_threads = <num_cpu_cores>`. I was missing the latter in previous experiments. Thanks!
